### ISSUE TITLE
TypeError [ERR_INVALID_ARG_TYPE]: The "path" argument must be of type string. Received undefined

### ISSUE THREAD

**Issue by DerHerrGammler** [TypeStrong/ts-node#1029]
### Expected Behavior
Just runnig my gulpfile.ts without errors. My code has no errors anymore but i think ts-node has a internal problem.

### Actual Behavior
```
TypeError [ERR_INVALID_ARG_TYPE]: The "path" argument must be of type string. Received undefined
    at validateString (internal/validators.js:117:11)
    at Object.join (path.js:375:7)
    at new I18nHelper (C:\workspace\boapi_master\default_api\src\classes\i18n.class.ts:18:35)
    at Object.<anonymous> (C:\workspace\boapi_master\default_api\src\env.ts:11:23)
    at Module._compile (internal/modules/cjs/loader.js:1158:30)
    at Module.m._compile (C:\workspace\boapi_master\default_api\node_modules\ts-node\src\index.ts:858:23)
    at Module._extensions..js (internal/modules/cjs/loader.js:1178:10)
    at Object.require.extensions.<computed> [as .ts] (C:\workspace\boapi_master\default_api\node_modules\ts-node\src\index.ts:861:12)
    at Module.load (internal/modules/cjs/loader.js:1002:32)
    at Function.Module._load (internal/modules/cjs/loader.js:901:14)
```

### Steps to reproduce the problem
i have no idea why this error is poping up.

### Specifications

* ts-node version: v8.10.1
* node version: v12.16.1
* TypeScript version: v3.8.3
* tsconfig.json, if you're using one:
```
{
    "compilerOptions": {
        "outDir": "./bin",
        "target": "es6",
        "module": "commonjs",
        "allowJs": true,
        "checkJs": true,
        "sourceMap": true,
        "strict": true,
        "noImplicitAny": true,
        "strictNullChecks": true,
        "extendedDiagnostics": false,
        "resolveJsonModule": true,
        "typeRoots": [
            "typings",
            "node_modules/@types"
        ]
    },
    "include": [
        "src/**/*.*",
        "typings/**/*.*",
        "gulpfile.ts"
    ],
    "exclude": [
        "node_modules"
    ]
}
```
* Operating system and version: Win10
* If Windows, are you using WSL or WSL2?: no

**Comment by DerHerrGammler** [comment]
Ok sry guys... i was dump as fuck and just frustated after hours and hours of debugging. It was my code ^^
