### ISSUE TITLE
--files switch is not respected

### ISSUE THREAD

**Issue by geisterfurz007** [TypeStrong/ts-node#1048]
### Expected Behavior

The `--files` flag is respected and ts-node makes use of the include field of tsconfig.json.

### Actual Behavior

The `--files` flag does not seem to have any effect:

<details>
  <summary>Issue in a production example</summary>

```
D:\Projects\JavaScript\com.yestheoryfam-backend>npx tsc --noEmit -p tsconfig.json

D:\Projects\JavaScript\com.yestheoryfam-backend>npx ts-node src/index.ts --files

D:\Projects\JavaScript\com.yestheoryfam-backend\node_modules\ts-node\src\index.ts:434
    return new TSError(diagnosticText, diagnosticCodes)
           ^
TSError: ⨯ Unable to compile TypeScript:
src/middleware/forceValidToken.ts:8:29 - error TS2304: Cannot find name 'KoaState'.

8   ctx: ParameterizedContext<KoaState>,
                              ~~~~~~~~

    at createTSError (D:\Projects\JavaScript\com.yestheoryfam-backend\node_modules\ts-node\src\index.ts:434:12)
    at reportTSError (D:\Projects\JavaScript\com.yestheoryfam-backend\node_modules\ts-node\src\index.ts:438:19)
    at getOutput (D:\Projects\JavaScript\com.yestheoryfam-backend\node_modules\ts-node\src\index.ts:578:36)
    at Object.compile (D:\Projects\JavaScript\com.yestheoryfam-backend\node_modules\ts-node\src\index.ts:775:32)
    at Module.m._compile (D:\Projects\JavaScript\com.yestheoryfam-backend\node_modules\ts-node\src\index.ts:858:43)
    at Module._extensions..js (internal/modules/cjs/loader.js:1167:10)
    at Object.require.extensions.<computed> [as .ts] (D:\Projects\JavaScript\com.yestheoryfam-backend\node_modules\ts-node\src\index.ts:861:12)
    at Module.load (internal/modules/cjs/loader.js:996:32)
    at Function.Module._load (internal/modules/cjs/loader.js:896:14)
    at Module.require (internal/modules/cjs/loader.js:1036:19)

D:\Projects\JavaScript\com.yestheoryfam-backend>npx ts-node src/index.ts --files true

D:\Projects\JavaScript\com.yestheoryfam-backend\node_modules\ts-node\src\index.ts:434
    return new TSError(diagnosticText, diagnosticCodes)
           ^
TSError: ⨯ Unable to compile TypeScript:
src/middleware/forceValidToken.ts:8:29 - error TS2304: Cannot find name 'KoaState'.

8   ctx: ParameterizedContext<KoaState>,
                              ~~~~~~~~

    at createTSError (D:\Projects\JavaScript\com.yestheoryfam-backend\node_modules\ts-node\src\index.ts:434:12)
    at reportTSError (D:\Projects\JavaScript\com.yestheoryfam-backend\node_modules\ts-node\src\index.ts:438:19)
    at getOutput (D:\Projects\JavaScript\com.yestheoryfam-backend\node_modules\ts-node\src\index.ts:578:36)
    at Object.compile (D:\Projects\JavaScript\com.yestheoryfam-backend\node_modules\ts-node\src\index.ts:775:32)
    at Module.m._compile (D:\Projects\JavaScript\com.yestheoryfam-backend\node_modules\ts-node\src\index.ts:858:43)
    at Module._extensions..js (internal/modules/cjs/loader.js:1167:10)
    at Object.require.extensions.<computed> [as .ts] (D:\Projects\JavaScript\com.yestheoryfam-backend\node_modules\ts-node\src\index.ts:861:12)
    at Module.load (internal/modules/cjs/loader.js:996:32)
    at Function.Module._load (internal/modules/cjs/loader.js:896:14)
    at Module.require (internal/modules/cjs/loader.js:1036:19)

D:\Projects\JavaScript\com.yestheoryfam-backend>SET TS_NODE_FILES=true   

D:\Projects\JavaScript\com.yestheoryfam-backend>npx ts-node src/index.ts
Running on port 3000
Database connection established.
```

As you can see, tsc reports not errors compiling the project.
Then running ts-node with the `--files` flag to make sure the types file we use is read by ts-node as well, the compilation fails. The same was attempted with an explicit true after it (although in the CLI options no arguments was listed so I expected this to fail).
Only after setting the environment variable, the include in tsconfig.json was respected.
</details>

### Steps to reproduce the problem

1. Create a project setups that makes use of include to add types in tsconfig.json.
2. Run `ts-node src/index.ts --files` (or whatever file is the entry point) and ts-node complains about missing types. 
3. Set `TS_NODE_FILES=true`
4. Run `ts-node src/index.ts` (or whatever file is the entry point) and ts-node will happily run.

### Minimal reproduction

```
git clone https://github.com/geisterfurz007/ts-node--filter.git
cd ts-node--filter
npm install
npx ts-node src/index.ts --files
SET TS_NODE_FILES=true
npx ts-node src/index.ts
```

### Specifications

* ts-node version: 8.10.1
* node version: 13.12.0
* TypeScript version: 3.9.3
* tsconfig.json, if you're using one:
```
{
  "compilerOptions": {
    "target": "es5" /* Specify ECMAScript target version: 'ES3' (default), 'ES5', 'ES2015', 'ES2016', 'ES2017', 'ES2018', 'ES2019', 'ES2020', or 'ESNEXT'. */,
    "module": "commonjs" /* Specify module code generation: 'none', 'commonjs', 'amd', 'system', 'umd', 'es2015', 'es2020', or 'ESNext'. */,
    "strict": true /* Enable all strict type-checking options. */,
    "esModuleInterop": true /* Enables emit interoperability between CommonJS and ES Modules via creation of namespace objects for all imports. Implies 'allowSyntheticDefaultImports'. */,
    "skipLibCheck": true /* Skip type checking of declaration files. */,
    "forceConsistentCasingInFileNames": true /* Disallow inconsistently-cased references to the same file. */
  },
  "include": ["./src", "types.ts"]
}
```
* Operating system and version: Windows 10 Pro 10.0.18363
* If Windows, are you using WSL or WSL2?: No

**Comment by cspotcode** [comment]
You're passing `--files` after the name of the script.  This means the `--files` flag is being passed to your script, not to `ts-node`.

**Comment by geisterfurz007** [comment]
Ah shit, big sorry! I completely missed that, thanks!
