### ISSUE TITLE
Error while using import

### ISSUE THREAD

**Issue by Thomas1664** [TypeStrong/ts-node#1078]
### Expected Behavior
Compile typescript files as expected

### Actual Behavior
Fails to compile with following error message:
```
 return new TSError(diagnosticText, diagnosticCodes)
           ^
TSError: ⨯ Unable to compile TypeScript:
index.ts:1:8 - error TS1192: Module '"fs"' has no default export.

1 import fs from 'fs'
         ~~

    at createTSError (C:\Users\[USERNAME]\AppData\Roaming\npm\node_modules\ts-node\src\index.ts:434:12)
    at reportTSError (C:\Users\[USERNAME]\AppData\Roaming\npm\node_modules\ts-node\src\index.ts:438:19)
    at getOutput (C:\Users\[USERNAME]\AppData\Roaming\npm\node_modules\ts-node\src\index.ts:578:36)
    at Object.compile (C:\Users\[USERNAME]\AppData\Roaming\npm\node_modules\ts-node\src\index.ts:775:32)
    at Module.m._compile (C:\Users\[USERNAME]\AppData\Roaming\npm\node_modules\ts-node\src\index.ts:858:43)
    at Module._extensions..js (internal/modules/cjs/loader.js:1221:10)
    at Object.require.extensions.<computed> [as .ts] (C:\Users\[USERNAME]\AppData\Roaming\npm\node_modules\ts-node\src\index.ts:861:12)
    at Module.load (internal/modules/cjs/loader.js:1050:32)
    at Function.Module._load (internal/modules/cjs/loader.js:938:14)
    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:71:12)
```

### Steps to reproduce the problem
run ```node run build``` and copy the code below into a file named ```index.ts```:

```
import fs from 'fs'

const file = fs.readFileSync('test/insulin.gb', 'utf-8').toString()
```

### Specifications
package.json:
```
{
  "name": [...],
  "version": "0.0.1",
  "description": [...],
  "main": "index.ts",
  "scripts": {
    "build": "ts-node index.ts"
  },
  "author": [...],
  "license": "ISC",
  "devDependencies": {
    "@types/node": "^14.0.23",
    "ts-node": "^8.10.2",
    "typescript": "^3.9.7"
  }
}
```

* ts-node version: v8.10.2
* node version: v14.5.0
* TypeScript version: v3.9.7
* tsconfig.json, if you're using one:
```
{
  "compilerOptions": {
    "target": "es2015",
    "module": "es2020",
    "strict": true,
     "moduleResolution": "node",
    "esModuleInterop": true,
    "skipLibCheck": true,
    "forceConsistentCasingInFileNames": true
}
}
```
* Operating system and version: Windows 10 Version 2004, Build 19041.388
* If Windows, are you using WSL or WSL2?:

**Comment by cspotcode** [comment]
Does `tsc` give you the same error?

**Comment by Thomas1664** [comment]
> Does `tsc` give you the same error?

Yes

**Comment by cspotcode** [comment]
Ok, so this is not a `ts-node` issue.  I'll go ahead and close this.

**Comment by blakeembrey** [comment]
@cspotcode Should we add issue guidelines on TypeScript versus TS Node issues? Seems like it’s usually a big source of confusion.

**Comment by cspotcode** [comment]
@blakeembrey Yeah, sounds good.  I'm not always clear exactly why people think `ts-node` will magically fix problems that occur with `tsc`.  I think if I understood that better, I'd have a better idea how to add guidelines.

The cynic in me suspects some people file issues here because they think they're more likely to get a response than at Microsoft/TypeScript, or they hope we'll implement a workaround for something that Microsoft/TypeScript has already said they won't do.

Should we just put a note in the issue template?  Something like "Issues that also happen with tsc are not ts-node issues and indicate an error in your code."  Would that help?
