### ISSUE TITLE
TypeError: formatDiagnostics is not a function

### ISSUE THREAD

**Issue by zeeshanalisyed** [TypeStrong/ts-node#1124]
### Expected Behavior
to run the ts file without any problem
### Actual Behavior
shows an exception 
```
/node/v14.0.0/lib/node_modules/ts-node/src/index.ts:228
    const diagnosticText = formatDiagnostics(diagnostics, diagnosticHost)
                           ^
TypeError: formatDiagnostics is not a function
    at createTSError (/node/v14.0.0/lib/node_modules/ts-node/src/index.ts:228:28)
    at Object.register (/node/v14.0.0/lib/node_modules/ts-node/src/index.ts:234:42)
    at Object.<anonymous> (/node/v14.0.0/lib/node_modules/ts-node/src/bin.ts:108:17)
    at Module._compile (internal/modules/cjs/loader.js:1185:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1205:10)
    at Module.load (internal/modules/cjs/loader.js:1034:32)
    at Function.Module._load (internal/modules/cjs/loader.js:923:14)
    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:71:12)
    at internal/main/run_main_module.js:17:47
```
### Steps to reproduce the problem

1. Install 14.0.0 node version
2. install 4.0.2 typescript version globally
2. install ts-node globally
3. check with the given ts-config
4. run ts-node [filename].ts
### Specifications

* ts-node version: 9.0.0, 8.0.0, and 8.0.1
* node version: 14.0.0,13.0.1
* TypeScript version: 4.0.2
* tsconfig.json, if you're using one:
```
{
  "compilerOptions": {
    "esModuleInterop": true,
    "noImplicitAny": true,
    "module": "commonjs",
    "moduleResolution": "node",
    "experimentalDecorators": true,
    "pretty": true,
    "types": [
      "jest",
      "node"
    ],
    "sourceMap": true,
    "target": "es6",
    "lib": [
      "es2019"
    ],
    "baseUrl": "./"
  },
  "include": ["src/**/*.ts", "tests/**/*.ts"],
  "exclude": [
    "node_modules"
  ]
}
```
* Operating system and version: Linux 5.4.0-42-generic x86_64

**Comment by cspotcode** [comment]
I need to confirm something: what's the output of `ts-node -vv`?

**Comment by zeeshanalisyed** [comment]
> ts-node -vv

/home/zeeshan/.nvm/versions/node/v14.0.0/lib/node_modules/ts-node/src/index.ts:228
    const diagnosticText = formatDiagnostics(diagnostics, diagnosticHost)
                           ^
TypeError: formatDiagnostics is not a function
    at createTSError (/home/zeeshan/.nvm/versions/node/v14.0.0/lib/node_modules/ts-node/src/index.ts:228:28)
    at Object.register (/home/zeeshan/.nvm/versions/node/v14.0.0/lib/node_modules/ts-node/src/index.ts:234:42)
    at Object.<anonymous> (/home/zeeshan/.nvm/versions/node/v14.0.0/lib/node_modules/ts-node/src/bin.ts:108:17)
    at Module._compile (internal/modules/cjs/loader.js:1185:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1205:10)
    at Module.load (internal/modules/cjs/loader.js:1034:32)
    at Function.Module._load (internal/modules/cjs/loader.js:923:14)
    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:71:12)
    at internal/main/run_main_module.js:17:47

**Comment by cspotcode** [comment]
I'm unable to reproduce this.  Here is what I did:
https://github.com/TypeStrong/ts-node-repros/tree/1124

And here is the output:
https://github.com/TypeStrong/ts-node-repros/runs/1129746015?check_suite_focus=true

Should we modify that reproduction to reproduce what you're seeing?
Otherwise, it looks like your development environment is broken in some way.

**Comment by zeeshanalisyed** [comment]
> I'm unable to reproduce this. Here is what I did:
> https://github.com/TypeStrong/ts-node-repros/tree/1124
> 
> And here is the output:
> https://github.com/TypeStrong/ts-node-repros/runs/1129746015?check_suite_focus=true
> 
> Should we modify that reproduction to reproduce what you're seeing?
> Otherwise, it looks like your development environment is broken in some way.

You are absolutely right, I rechecked it again with the simple shell it is working fine, but it only gives problem in visual code terminal

**Comment by AnnikaNissen** [comment]
> You are absolutely right, I rechecked it with the simple shell it is working fine, but it only gives problem in visual code terminal

Did you finde a workaround to make it work in VS Code? I'm experiencing the same issue and it would be great if I could continue to use VS Code.

**Comment by tomitrescak** [comment]
Same here

**Comment by fanyer** [comment]
@zeeshanalisyed  maybe you have multi-version typescript  installed in you machine. especially you install in other node env by nvm or system
