### ISSUE TITLE
ReferenceError: Request is not defined

### ISSUE THREAD

**Issue by Stono** [TypeStrong/ts-node#1134]
I have an issue with `Request` from `WebWorker`.  
It appears to be fine with `tsc` but not `ts-node`.

As an example:

`tsconfig.json`:
```
{
  "compilerOptions": {
    "types": ["@cloudflare/workers-types", "mocha"],
    "module": "CommonJS",
    "target": "es2020",
    "lib": ["es2017", "WebWorker"],
    "rootDir": "./",
    "outDir": "./built",
    "baseUrl": "./",
    "allowJs": true,
    "checkJs": true,
    "alwaysStrict": true,
    "noImplicitAny": false,
    "noImplicitThis": true,
    "strictNullChecks": true,
    "strictFunctionTypes": true,
    "strictPropertyInitialization": true,
    "noEmitOnError": false,
    "sourceMap": false
  },
  "include": ["lib/**/*.ts", "test/**/*.ts"],
  "exclude": ["node_modules"]
}
```

and `lib/example.ts`:
```
const example = new Request({} as any)
console.log(example)
```

`./node_modules/.bin/tsc lib/example.ts ` = completes fine

Intellisense in vscode = fine.

`ts-node` however, does not:

```
❯ ./node_modules/.bin/ts-node --project tsconfig.json lib/example.ts

/Users/karl.stoney/git/autotrader/at-global-worker/lib/example.ts:1
const example = new Request({} as any)
                ^
ReferenceError: Request is not defined
    at Object.<anonymous> (/Users/karl.stoney/git/autotrader/at-global-worker/lib/example.ts:1:17)
    at Module._compile (internal/modules/cjs/loader.js:1251:30)
    at Module.m._compile (/Users/karl.stoney/git/autotrader/at-global-worker/node_modules/ts-node/src/index.ts:1043:23)
    at Module._extensions..js (internal/modules/cjs/loader.js:1272:10)
    at Object.require.extensions.<computed> [as .ts] (/Users/karl.stoney/git/autotrader/at-global-worker/node_modules/ts-node/src/index.ts:1046:12)
    at Module.load (internal/modules/cjs/loader.js:1100:32)
    at Function.Module._load (internal/modules/cjs/loader.js:962:14)
    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:72:12)
    at main (/Users/karl.stoney/git/autotrader/at-global-worker/node_modules/ts-node/src/bin.ts:225:14)
    at Object.<anonymous> (/Users/karl.stoney/git/autotrader/at-global-worker/node_modules/ts-node/src/bin.ts:512:3)
```

As a result, I'm unable to use `ts-node` to run the project or tests.

**Comment by cspotcode** [comment]
Looks like a JavaScript error.  Have you verified that the code executes
correctly with tsc? As opposed to compiling.

**Comment by cspotcode** [comment]
@Stono this looks like a problem with the workers-types

Your code does `new Request()`.  `ts-node` is compiling and running your code.  `tsc` is only compiling your code.  What happens when you run it?  The error you are getting is not a typechecking error; it is a runtime error.  Which means you get that error from `node`, not from `ts-node`.

**Comment by cspotcode** [comment]
I'm gonna go ahead and close this since it looks like an external issue.  If you find any information that shows it's a ts-node issue, and we need to make a bugfix, let us know and we'll reopen the ticket.
