### ISSUE TITLE
Function name mismatch

### ISSUE THREAD

**Issue by ktfth** [TypeStrong/ts-node#1140]
### Expected Behavior

Suggest just the declaration

### Actual Behavior

npm test

> typescript-livro-de-bolso@1.0.0 test /home/kaique/war/typescript-livro-de-bolso
> mocha -r ts-node/register ./**/*.test.ts

TSError: ⨯ Unable to compile TypeScript:
app.test.ts:39:18 - error TS2552: Cannot find name 'match'. Did you mean 'Math'?

39     assert.equal(match('baz', 'foobarbaz'), 'foobarbaz');
                    ~~~~~

  ../../../../usr/local/lib/node_modules/typescript/lib/lib.es5.d.ts:726:13
    726 declare var Math: Math;
                    ~~~~
    'Math' is declared here.

    at createTSError (/usr/local/lib/node_modules/ts-node/src/index.ts:500:12)
    at reportTSError (/usr/local/lib/node_modules/ts-node/src/index.ts:504:19)
    at getOutput (/usr/local/lib/node_modules/ts-node/src/index.ts:739:36)
    at Object.compile (/usr/local/lib/node_modules/ts-node/src/index.ts:955:32)
    at Module.m._compile (/usr/local/lib/node_modules/ts-node/src/index.ts:1043:43)
    at Module._extensions..js (internal/modules/cjs/loader.js:1157:10)
    at Object.require.extensions.<computed> [as .ts] (/usr/local/lib/node_modules/ts-node/src/index.ts:1046:12)
    at Module.load (internal/modules/cjs/loader.js:985:32)
    at Function.Module._load (internal/modules/cjs/loader.js:878:14)
    at Module.require (internal/modules/cjs/loader.js:1025:19)
    at require (internal/modules/cjs/helpers.js:72:18)
    at Object.exports.requireOrImport (/usr/local/lib/node_modules/mocha/lib/esm-utils.js:20:12)
    at Object.exports.loadFilesAsync (/usr/local/lib/node_modules/mocha/lib/esm-utils.js:33:34)
    at Mocha.loadFilesAsync (/usr/local/lib/node_modules/mocha/lib/mocha.js:427:19)
    at singleRun (/usr/local/lib/node_modules/mocha/lib/cli/run-helpers.js:156:15)
    at exports.runMocha (/usr/local/lib/node_modules/mocha/lib/cli/run-helpers.js:225:10)
    at Object.exports.handler (/usr/local/lib/node_modules/mocha/lib/cli/run.js:366:11)
    at /usr/local/lib/node_modules/mocha/node_modules/yargs/lib/command.js:241:49
npm ERR! Test failed.  See above for more details.

### Steps to reproduce the problem

Create a test file with a function not imported at yet with the name match and execute the file with a simple test.

### Minimal reproduction

Create a test file with a function not imported at yet with the name match and execute the file with a simple test.

<!--

This link explains why we ask for a minimal reproduction.  Thank you in advance!
https://gist.github.com/Rich-Harris/88c5fc2ac6dc941b22e7996af05d70ff

You can create a reproduction here:
https://github.com/TypeStrong/ts-node-repros
-->

### Specifications

<!-- `ts-node -vv` will print ts-node, node, and TypeScript versions -->
* ts-node version: ^9.0.0
* node version: v12.18.3
* TypeScript version: 4.0.5

* Operating system and version:

DISTRIB_ID=Ubuntu
DISTRIB_RELEASE=20.04
DISTRIB_CODENAME=focal
DISTRIB_DESCRIPTION="Ubuntu 20.04.1 LTS"
NAME="Ubuntu"
VERSION="20.04.1 LTS (Focal Fossa)"
ID=ubuntu
ID_LIKE=debian
PRETTY_NAME="Ubuntu 20.04.1 LTS"
VERSION_ID="20.04"
HOME_URL="https://www.ubuntu.com/"
SUPPORT_URL="https://help.ubuntu.com/"
BUG_REPORT_URL="https://bugs.launchpad.net/ubuntu/"
PRIVACY_POLICY_URL="https://www.ubuntu.com/legal/terms-and-policies/privacy-policy"
VERSION_CODENAME=focal
UBUNTU_CODENAME=focal

**Comment by cspotcode** [comment]
@ktfth 
This diagnostic is coming from TypeScript, right?  Is `ts-node` somehow altering the diagnostics you're getting from TypeScript?  What diagnostic do you get when running `tsc` without `ts-node`?  What happens if you run `ts-node` again with the `--files` option enabled, either via CLI positional, via env var, or specified via tsconfig file?

**Comment by ktfth** [comment]
This happen with a mocha register, but the exception are showed on typescript compiler level.

**Comment by cspotcode** [comment]
@ktfth ok, do you have answers to the other questions, too?

**Comment by ktfth** [comment]
No, just that. Thank you a lot

**Comment by cspotcode** [comment]
@ktfth What diagnostic do you get when running `tsc` without `ts-node`? What happens if you run again with `ts-node`'s `--files` option enabled, either via environment variable, specified via `tsconfig` file, or passed via arguments to `.register()`?

**Comment by cspotcode** [comment]
Closing because this is how TypeScript behaves, and we're not going to change TypeScript's behavior, making ourselves non-standard.  We faithfully report the diagnostics we receive from TypeScript.

You can submit this request to the TypeScript project if you think it should be behaving differently.  You can also use a custom TypeScript compiler with `ts-node` via our "compiler" option, so you can swap in a compiler that behaves the way you want.
