### ISSUE TITLE
fix: Error: Unknown or unexpected option: --transpiler

### ISSUE THREAD

**Issue by jjangga0214** [TypeStrong/ts-node#1319]
### Expected Behavior

`--transpiler` option should work.

### Actual Behavior

It doesn't.

### Steps to reproduce the problem

```shell
➜  wedding-invitation git:(main) ✗ (☸ |k3d-ateam:local) y ts-node -v
yarn run v1.22.5
$ /media/jjangga/SHARE/outsourcing/wedding-invitation/node_modules/.bin/ts-node -v
v9.1.1
Done in 0.17s.


➜  wedding-invitation git:(main) ✗ (☸ |k3d-ateam:local) y ts-node -T --transpiler ts-node/transpilers/swc-experimental hello.ts
yarn run v1.22.5
$ /media/jjangga/SHARE/outsourcing/wedding-invitation/node_modules/.bin/ts-node -T --transpiler ts-node/transpilers/swc-experimental hello.ts
/media/jjangga/SHARE/outsourcing/wedding-invitation/node_modules/arg/index.js:90
						throw err;
						^

Error: Unknown or unexpected option: --transpiler
    at arg (/media/jjangga/SHARE/outsourcing/wedding-invitation/node_modules/arg/index.js:88:19)
    at main (/media/jjangga/SHARE/outsourcing/wedding-invitation/node_modules/ts-node/dist/bin.js:15:67)
    at Object.<anonymous> (/media/jjangga/SHARE/outsourcing/wedding-invitation/node_modules/ts-node/dist/bin.js:238:5)
    at Module._compile (node:internal/modules/cjs/loader:1109:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1138:10)
    at Module.load (node:internal/modules/cjs/loader:989:32)
    at Function.Module._load (node:internal/modules/cjs/loader:829:14)
    at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:76:12)
    at node:internal/main/run_main_module:17:47 {
  code: 'ARG_UNKNOWN_OPTION'
}
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.

```

### Specifications

* ts-node version: 9.1.1
* node version: 16
* TypeScript version: 4.2.4
* tsconfig.json, if you're using one:
```
{}
```
* Operating system and version: ubuntu 20.04
* If Windows, are you using WSL or WSL2?:

**Comment by cspotcode** [comment]
`--transpiler` exists on our `main` branch and will be published in v10.0.0.  Using it today requires installing `ts-node` from git, which is supported natively by the major package managers.
