### ISSUE TITLE
ts-node: ReferenceError: define is not defined

### ISSUE THREAD

**Issue by bang88** [TypeStrong/ts-node#136]
Hello,

I try to write some tests with typescript use` ts-node` and `mocha` together,it works well **when i use module as commonjs**,but when i change the` tsconfig.json` module to `amd` then run test again,its broken,here is the error log:
```js
E:\demos\official-sdk\test\index.spec.ts:1
import { expect } from 'chai';
^
ReferenceError: define is not defined
    at Object.<anonymous> (E:\demos\official-sdk\test\index.spec.ts:1:1)
    at Module._compile (module.js:541:32)
    at Object.loader (E:\demos\official-sdk\node_modules\ts-node\src\ts-node.ts:225:14)
    at Module.load (module.js:458:32)
    at tryModuleLoad (module.js:417:12)
    at Function.Module._load (module.js:409:3)
    at Module.require (module.js:468:17)
    at require (internal/module.js:20:19)
    at E:\demos\official-sdk\node_modules\mocha\lib\mocha.js:220:27
    at Array.forEach (native)
    at Mocha.loadFiles (E:\demos\official-sdk\node_modules\mocha\lib\mocha.js:217:14)
    at Mocha.run (E:\demos\official-sdk\node_modules\mocha\lib\mocha.js:469:10)
    at Object.<anonymous> (E:\demos\official-sdk\node_modules\mocha\bin\_mocha:404:18)
    at Module._compile (module.js:541:32)
    at Object.Module._extensions..js (module.js:550:10)
    at Module.load (module.js:458:32)
    at tryModuleLoad (module.js:417:12)
    at Function.Module._load (module.js:409:3)
    at Function.Module.runMain (module.js:575:10)
    at startup (node.js:160:18)
    at node.js:449:3
npm ERR! Test failed.  See above for more details.
```
 and the config:

```js

"compilerOptions": {
    "declaration": true,
    "emitDecoratorMetadata": true,
    "experimentalDecorators": true,
    "module": "amd",
    "moduleResolution": "node",
    "outDir": "./build",
    "pretty": true,
    "sourceMap": false 
  }

```

**Comment by blakeembrey** [comment]
Node.js can not execute AMD code.

**Comment by bang88** [comment]
how can i handle this .

**Comment by blakeembrey** [comment]
Don't set module to AMD.

**Comment by bang88** [comment]
😢

**Comment by blakeembrey** [comment]
Why do you want to use AMD? AMD won't be able to execute natively on node.

With issues like these, it's usually easier to give some background on the "why", such that other contributors can help out and point you in the right direction.

**Comment by bang88** [comment]
You are right,I need combine all files into one.

**Comment by blakeembrey** [comment]
Thanks. I think you might be using the wrong tool for this then. `ts-node` is for execute TypeScript on the node runtime without a pre-compilation step (E.g. it's all in memory). Are you trying to generate code for a browser instead? Maybe you want to try https://github.com/TypeStrong/tsify or https://github.com/TypeStrong/ts-loader which are plugins for Browserify and Webpack?

**Comment by bang88** [comment]
Thanks.I will take a look later.I use` ts-node` for commonjs works very well,Maybe i need Webpack like tool to bundle the js files.  😃

**Comment by blakeembrey** [comment]
No worries. Yes, most likely you'll want a "bundler" like Browserify or Webpack to build your project for the browser. There should be plenty of tutorials available 😄
