### ISSUE TITLE
Throw errors but print them without stacktraces

### ISSUE THREAD

**Issue by akatechis** [TypeStrong/ts-node#1374]
### Desired Behavior
I would like to be able to throw errors (eg, ts-node doesn't execute my program if there's a type error), but also omit the stack trace as shown when `{ logError: true }`

### Is this request related to a problem?
Yes, I'm using `ts-node` to run my mocha test suite. In my mocha config file, I have a `bootstrap.ts` script that register ts-node like so:

```typescript
require('ts-node/register')
```

If I then insert a typescript error somewhere in my code, before running my test suite, I see the following output. For example, an unused parameter in a function:

```
$ yarn test
yarn run v1.22.5
$ nyc mocha

TSError: ⨯ Unable to compile TypeScript:
src/turbo-streams.ts:31:37 - error TS6133: 'options' is declared but its value is never read.

31 export function createSocketServer (options: CableOptions): Server {
                                       ~~~~~~~

    at createTSError (C:\Users\Alexandros\workspace\koa-hotwire\node_modules\ts-node\src\index.ts:587:12)
    at reportTSError (C:\Users\Alexandros\workspace\koa-hotwire\node_modules\ts-node\src\index.ts:591:19)
    at getOutput (C:\Users\Alexandros\workspace\koa-hotwire\node_modules\ts-node\src\index.ts:921:36)
    at Object.compile (C:\Users\Alexandros\workspace\koa-hotwire\node_modules\ts-node\src\index.ts:1189:32)
    at Module.m._compile (C:\Users\Alexandros\workspace\koa-hotwire\node_modules\ts-node\src\index.ts:1295:42)
    at module.exports (C:\Users\Alexandros\workspace\koa-hotwire\node_modules\default-require-extensions\js.js:7:9)
    at C:\Users\Alexandros\workspace\koa-hotwire\node_modules\append-transform\index.js:64:4
    at require.extensions.<computed> (C:\Users\Alexandros\workspace\koa-hotwire\node_modules\ts-node\src\index.ts:1298:12)
    at Object.<anonymous> (C:\Users\Alexandros\workspace\koa-hotwire\node_modules\append-transform\index.js:64:4)
    at Module.load (internal/modules/cjs/loader.js:1040:32)
    at Function.Module._load (internal/modules/cjs/loader.js:929:14)
    at Module.require (internal/modules/cjs/loader.js:1080:19)
    at require (internal/modules/cjs/helpers.js:72:18)
    at Object.<anonymous> (C:\Users\Alexandros\workspace\koa-hotwire\src\koa-hotwire.ts:2:346)
    at Module._compile (internal/modules/cjs/loader.js:1176:30)
    at Module.replacementCompile (C:\Users\Alexandros\workspace\koa-hotwire\node_modules\append-transform\index.js:60:13)
    at Module.m._compile (C:\Users\Alexandros\workspace\koa-hotwire\node_modules\ts-node\src\index.ts:1295:23)
    at module.exports (C:\Users\Alexandros\workspace\koa-hotwire\node_modules\default-require-extensions\js.js:7:9)
    at C:\Users\Alexandros\workspace\koa-hotwire\node_modules\append-transform\index.js:64:4
    at require.extensions.<computed> (C:\Users\Alexandros\workspace\koa-hotwire\node_modules\ts-node\src\index.ts:1298:12)
    at Object.<anonymous> (C:\Users\Alexandros\workspace\koa-hotwire\node_modules\append-transform\index.js:64:4)
    at Module.load (internal/modules/cjs/loader.js:1040:32)
    at Function.Module._load (internal/modules/cjs/loader.js:929:14)
    at Module.require (internal/modules/cjs/loader.js:1080:19)
    at require (internal/modules/cjs/helpers.js:72:18)
    at Object.<anonymous> (C:\Users\Alexandros\workspace\koa-hotwire\tests\turbo-frames-test.ts:7:1)
    at Module._compile (internal/modules/cjs/loader.js:1176:30)
    at Module.replacementCompile (C:\Users\Alexandros\workspace\koa-hotwire\node_modules\append-transform\index.js:60:13)
    at Module.m._compile (C:\Users\Alexandros\workspace\koa-hotwire\node_modules\ts-node\src\index.ts:1295:23)
    at module.exports (C:\Users\Alexandros\workspace\koa-hotwire\node_modules\default-require-extensions\js.js:7:9)
    at C:\Users\Alexandros\workspace\koa-hotwire\node_modules\append-transform\index.js:64:4
    at require.extensions.<computed> (C:\Users\Alexandros\workspace\koa-hotwire\node_modules\ts-node\src\index.ts:1298:12)
    at Object.<anonymous> (C:\Users\Alexandros\workspace\koa-hotwire\node_modules\append-transform\index.js:64:4)
    at Module.load (internal/modules/cjs/loader.js:1040:32)
    at Function.Module._load (internal/modules/cjs/loader.js:929:14)
    at Module.require (internal/modules/cjs/loader.js:1080:19)
    at require (internal/modules/cjs/helpers.js:72:18)
    at Object.exports.requireOrImport (C:\Users\Alexandros\workspace\koa-hotwire\node_modules\mocha\lib\esm-utils.js:42:12)
    at Object.exports.loadFilesAsync (C:\Users\Alexandros\workspace\koa-hotwire\node_modules\mocha\lib\esm-utils.js:55:34)
    at Mocha.loadFilesAsync (C:\Users\Alexandros\workspace\koa-hotwire\node_modules\mocha\lib\mocha.js:473:19)
    at singleRun (C:\Users\Alexandros\workspace\koa-hotwire\node_modules\mocha\lib\cli\run-helpers.js:125:15)
    at exports.runMocha (C:\Users\Alexandros\workspace\koa-hotwire\node_modules\mocha\lib\cli\run-helpers.js:190:10)
    at Object.exports.handler (C:\Users\Alexandros\workspace\koa-hotwire\node_modules\mocha\lib\cli\run.js:362:11)
    at C:\Users\Alexandros\workspace\koa-hotwire\node_modules\yargs\build\index.cjs:443:71
```

When working on my code, nearly all of that stack trace is useless to me. The useful part is the filename, line, col and excerpt that is printed at the very beginning. This is what tells me where and what kind of problem my code has.

I tried using the logError option, by changing my bootstrap script:

```typescript
require('ts-node').register({
  logError: true,
})
```

This is almost what I want, as it omits the stack traces, but still executes my test suite:

```
$ yarn test
yarn run v1.22.5
$ nyc mocha
src/turbo-streams.ts:31:37 - error TS6133: 'options' is declared but its value is never read.

31 export function createSocketServer (options: CableOptions): Server {
                                       ~~~~~~~



  turbo-frames
    √ renders pages when using ctx.view in a handler
    √ passes ctx.state to render calls
    √ wraps turboframes in custom elements when requested
    √ optimizes rendering when a specific turbo-frame is requested
    √ returns an error when the requested frame is not in the view
    √ does nothing when the handler doesn't produce a view

  turbo-streams
    √ can send append updates with fragments


  7 passing (61ms)
```

### Alternatives you've considered
Not sure what alternatives are available, seems like there's no option to provide a custom error formatter or event handler,
so there's not much I can do.

**Comment by cspotcode** [comment]
I think this will work for you: https://nodejs.org/api/process.html#process_event_uncaughtexception

**Comment by cspotcode** [comment]
@akatechis Any luck with https://nodejs.org/api/process.html#process_event_uncaughtexception?

I'm going to go ahead and close this issue, but we can re-open it if appropriate.

**Comment by akatechis** [comment]
I'm OK with closing this. I haven't tried the workaround yet, but I suspect I'll just go with the throw behavior, as I'm starting to shift my thinking to consider type errors as "failed tests" (type annotations are kind of like tests that you write to ensure your code only works with certain types).
