### ISSUE TITLE
tsconfig['ts-node'] doesn't override tsconfig properties

### ISSUE THREAD

**Issue by eng-dibo** [TypeStrong/ts-node#1447]
I have a `tsconfig.json` configured to use `module: es2020` and I want to set it to `commonjs` only for `ts-node`, so my `tsconfig.json` looks like:

```
{
   "ts-node": {
    "compilerOptions": {
      "module": "commonjs"
    }
  },

 "compilerOptions": {
      "module": "es2020",
      // ... other options
    }
}
```

now I want to write a webpack config file in typescript, webpack uses `ts-node` to transpile `webpack.config.ts` using the given tsconfig.json file above.

wen I run `wbpack` cmd, I got the error: `Cannot use import statement outside a module`

```
[webpack-cli] Failed to load '/home/webpack.config.ts' config
[webpack-cli] /home/webpack.config.ts:1
(function (exports, require, module, __filename, __dirname) { import config from '../webpack.config';

SyntaxError: Cannot use import statement outside a module
    at new Script (vm.js:84:7)
    at NativeCompileCache._moduleCompile (/home/node_modules/v8-compile-cache/v8-compile-cache.js:240:18)
    at Module._compile (/home/node_modules/v8-compile-cache/v8-compile-cache.js:184:36)
    at Module.m._compile (/home/node_modules/ts-node/src/index.ts:473:23)
    at Module._extensions..js (internal/modules/cjs/loader.js:991:10)
    at Object.require.extensions.<computed> [as .ts] (/home/node_modules/ts-node/src/index.ts:476:12)
    at Module.load (internal/modules/cjs/loader.js:811:32)
    at Function.Module._load (internal/modules/cjs/loader.js:723:14)
    at Module.require (internal/modules/cjs/loader.js:848:19)
    at require (/home/node_modules/v8-compile-cache/v8-compile-cache.js:159:20)
```

when I change the main property `module` (not under ts-node) it works.

note: I don't want to create another tsconfig file for ts-node and using the environment `TS_NODE_PROJECT`, I just want to override some properties for ts-node.

the output of `ts-node --show-config` show that ts-node uses `module: commonjs`

```
{
  "ts-node": {
    "cwd": "/home/sh_eldeeb_2010/@eng-dibo/dibo",
    "projectSearchDir": "/home/sh_eldeeb_2010/@eng-dibo/dibo",
    "require": [],
    "project": "/home/sh_eldeeb_2010/@eng-dibo/dibo/tsconfig.json"
  },
  "compilerOptions": {
    "baseUrl": "./",
    "outDir": "./.ts-node",
    "strict": true,
    "forceConsistentCasingInFileNames": true,
    "noImplicitReturns": true,
    "noFallthroughCasesInSwitch": true,
    "sourceMap": true,
    "declaration": false,
    "downlevelIteration": true,
    "experimentalDecorators": true,
    "moduleResolution": "node",
    "importHelpers": true,
    "target": "es6",
    "module": "commonjs",
    "lib": [
      "es2018",
      "dom"
    ],
    "types": [
      "node"
    ],
    "typeRoots": [
      "/home/sh_eldeeb_2010/@eng-dibo/dibo/node_modules/@types"
    ],
    "removeComments": true,
    "noEmit": false,
    "noEmitOnError": false,
    "noImplicitAny": true,
    "noUnusedLocals": false,
    "noUnusedParameters": false,
    "preserveSymlinks": true,
    "sourceRoot": "",
    "mapRoot": "",
    "emitDecoratorMetadata": true,
    "locale": "en",
    "resolveJsonModule": true,
    "paths": {
      "~~*": [
        "./*"
      ],
      "@engineers/*": [
        "./packages/*"
      ],
      "*": [
        "node_modules/*",
        "types/*"
      ]
    },
    "allowSyntheticDefaultImports": true,
    "esModuleInterop": true,
    "strictPropertyInitialization": false,
    "skipLibCheck": true,
    "inlineSourceMap": false,
    "inlineSources": true
  },
  "exclude": [
    "node_modules",
    "dist",
    "**/*.spec.ts",
    "**/e2e"
  ]
}
```

**Comment by cspotcode** [comment]
Please complete our issue template.

**Comment by cspotcode** [comment]
Closing as there is some information we request in our issue template that appears to have been omitted here.
