### ISSUE TITLE
TypeScript 1.7.x  TypeError: ts.parseConfigFile is not a function 

### ISSUE THREAD

**Issue by xmlking** [TypeStrong/ts-node#15]
I am using typescript@next and got following error:

```bash
/Developer/Work/node/koa-router-decorators/node_modules/ts-node/dist/ts-node.js:32
    return ts.parseConfigFile(config, ts.sys, fileName);
              ^

TypeError: ts.parseConfigFile is not a function
    at readConfig (/Developer/Work/node/koa-router-decorators/node_modules/ts-node/dist/ts-node.js:32:15)
    at Object.register (/Developer/Work/node/koa-router-decorators/node_modules/ts-node/dist/ts-node.js:41:18)
    at Object.<anonymous> (/Developer/Work/node/koa-router-decorators/node_modules/ts-node/register.js:1:77)
    at Module._compile (module.js:435:26)
    at Object.Module._extensions..js (module.js:442:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:311:12)
    at Module.require (module.js:366:17)
    at require (module.js:385:17)
    at /Developer/Work/node/koa-router-decorators/node_modules/mocha/bin/_mocha:296:3
    at Array.forEach (native)
    at Object.<anonymous> (/Developer/Work/node/koa-router-decorators/node_modules/mocha/bin/_mocha:290:19)
    at Module._compile (module.js:435:26)
    at Object.Module._extensions..js (module.js:442:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:311:12)
    at Function.Module.runMain (module.js:467:10)
    at startup (node.js:134:18)
    at node.js:961:3
```

**Comment by xmlking** [comment]
looks like the API has been changed
```js
   //return ts.parseConfigFile(config, ts.sys, fileName);
    return ts.parseJsonConfigFileContent(config, ts.sys, fileName);
```

**Comment by blakeembrey** [comment]
Released with `v0.4.1`

**Comment by calidion** [comment]
I encountered this problem again.

**Comment by blakeembrey** [comment]
@calidion Please state what the problem is. I'm not sure that you'd be using TypeScript 1.7 and, if so, this module is tested with all TypeScript versions since 1.6 and they all pass. Did you install the right module?
