### ISSUE TITLE
Unexpected Reserved Word

### ISSUE THREAD

**Issue by tomitrescak** [TypeStrong/ts-node#152]
Hi, I'm trying to run mocha my tests defined in typescript. Tests contains React files and syntax. Sources are in the folder 'src'. I'm running my mocha as following:

`mocha src/client/**/tests/**/*.ts* --compilers ts:ts-node/register --compilers tsx:ts-node/register -P src` but I'm getting following error:

```
SyntaxError: Unexpected reserved word
    at exports.runInThisContext (vm.js:53:16)
    at Module._compile (module.js:373:25)
    at loader (/Users/tomi/Github/apps/Clara/web/node_modules/ts-node/src/index.ts:286:14)
    at Object.require.extensions.(anonymous function) [as .tsx] (/Users/tomi/Github/apps/Clara/web/node_modules/ts-node/src/index.ts:303:14)
    at Module.load (module.js:343:32)
    at Function.Module._load (module.js:300:12)
    at Module.require (module.js:353:17)
    at require (internal/module.js:12:17)
    at /Users/tomi/Github/apps/Clara/web/node_modules/mocha/lib/mocha.js:220:27
    at Array.forEach (native)
    at Mocha.loadFiles (/Users/tomi/Github/apps/Clara/web/node_modules/mocha/lib/mocha.js:217:14)
    at Mocha.run (/Users/tomi/Github/apps/Clara/web/node_modules/mocha/lib/mocha.js:469:10)
    at Object.<anonymous> (/Users/tomi/Github/apps/Clara/web/node_modules/mocha/bin/_mocha:404:18)
    at Module._compile (module.js:409:26)
    at Object.Module._extensions..js (module.js:416:10)
    at Module.load (module.js:343:32)
    at Function.Module._load (module.js:300:12)
    at Function.Module.runMain (module.js:441:10)
    at startup (node.js:139:18)
    at node.js:968:3
```

Any idea what could be wrong ?

**Comment by tomitrescak** [comment]
Never mind ... I need a post processor to compile from es6.
