### ISSUE TITLE
ReferenceError: fetch is not defined

### ISSUE THREAD

**Issue by zomars** [TypeStrong/ts-node#1685]
### Search Terms

Fetch is undefined when running script that uses `fetch` in the command line like this: `ts-node script-with-fetch.ts`

I've looked up in the issues and didn't find anything like this.

### Expected Behavior

To run fetch as normally.

### Actual Behavior

It throws this error:

```sh
yarn run v1.22.17
$ ts-node ./fetch-test.ts
ReferenceError: fetch is not defined
    at /Users/zomars/Sites/test/fetch-test.ts:7:20
    at step (/Users/zomars/Sites/test/fetch-test.ts:33:23)
    at Object.next (/Users/zomars/Sites/test/fetch-test.ts:14:53)
    at /Users/zomars/Sites/test/fetch-test.ts:8:71
    at new Promise (<anonymous>)
    at __awaiter (/Users/zomars/Sites/test/fetch-test.ts:4:12)
    at checkPremiumUsername (/Users/zomars/Sites/test/fetch-test.ts:41:12)
    at Object.<anonymous> (/Users/zomars/Sites/test/fetch-test.ts:21:1)
    at Module._compile (internal/modules/cjs/loader.js:1072:14)
    at Module.m._compile (/Users/zomars/Sites/test/node_modules/ts-node/src/index.ts:1475:23)
error Command failed with exit code 1.
```

### Minimal reproduction

```ts
export async function testFunction() {
  const response = await fetch("https://jsonplaceholder.typicode.com/todos/1", {
    credentials: "include",
    headers: {
      "Content-Type": "application/json",
    },
    method: "POST",
    mode: "cors",
  });

  const json = await response.json();
  return json;
}

testFunction()
  .then((response) => {
    console.log(response);
  })
  .catch((e) => {
    console.error(e);
    process.exit(1);
  });
```

https://github.com/TypeStrong/ts-node-repros/pull/22

### Specifications

ts-node v10.6.0
node v14.17.6
compiler v4.5.5
```
{}
```
* Operating system and version: macOS 12

**Comment by cspotcode** [comment]
What about when you run that code in node v14.17.6?

**Comment by zomars** [comment]
I see... same result:

```
$ node ./fetch-test.js
ReferenceError: fetch is not defined
    at checkPremiumUsername (/Users/zomars/Sites/test/fetch-test.js:2:20)
    at Object.<anonymous> (/Users/zomars/Sites/test/fetch-test.js:16:1)
    at Module._compile (internal/modules/cjs/loader.js:1072:14)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1101:10)
    at Module.load (internal/modules/cjs/loader.js:937:32)
    at Function.Module._load (internal/modules/cjs/loader.js:778:12)
    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:76:12)
    at internal/main/run_main_module.js:17:47
error Command failed with exit code 1.
```

**Comment by cspotcode** [comment]
Yeah, it's a node issue, nothing wrong with ts-node.

**Comment by zomars** [comment]
@cspotcode what would be the best way to use native `fetch` using `ts-node` upgrading node itself to 16?

**Comment by cspotcode** [comment]
What versions of node expose native fetch?

**Comment by zomars** [comment]
It seems like `17.5` will try with that.
