### ISSUE TITLE
jest@28 support

### ISSUE THREAD

**Issue by kirillgroshkov** [TypeStrong/ts-node#1730]
Jest 28 has [landed](https://jestjs.io/blog/2022/04/25/jest-28).

Doesn't work with current `ts-jest` as-is, gives this error:

```
 FAIL  src/test/env.test.ts
  ● Test suite failed to run

    ● Invalid return value:
      Code transformer's `process` method must return an object containing `code` key 
      with processed string. If `processAsync` method is implemented it must return 
      a Promise resolving to an object containing `code` key with processed string.
      Code Transformation Documentation:
      https://jestjs.io/docs/code-transformation
      
      at ScriptTransformer._buildTransformResult (node_modules/@jest/transform/build/ScriptTransformer.js:504:15)
      at ScriptTransformer.transformSource (node_modules/@jest/transform/build/ScriptTransformer.js:623:17)
      at ScriptTransformer._transformAndBuildScript (node_modules/@jest/transform/build/ScriptTransformer.js:760:40)
      at ScriptTransformer.transform (node_modules/@jest/transform/build/ScriptTransformer.js:817:19)
```

Created this issue to track when jest28 support will land here.

Thanks.

**Comment by kirillgroshkov** [comment]
Sorry, posted to the wrong repo, closing!
