### ISSUE TITLE
Import resolves to local file instead of node module

### ISSUE THREAD

**Issue by andrejleitner** [TypeStrong/ts-node#1732]
### Expected Behavior

Import resolves correctly to node module.

### Actual Behavior

Import resolves to the local file instead.

```sh
Some .ts code reproducing a bug
>>> newrelic: {"config":{"app_name":["ts-node-repros"],"license_key":"some-license-key"}}

newrelic.noticeError(new Error('some error'));
         ^
TypeError: newrelic.noticeError is not a function
    at Object.<anonymous> (~/github/ts-node-repros/example.ts:7:10)
    at Module._compile (node:internal/modules/cjs/loader:1101:14)
    at Module.m._compile (~/github/ts-node-repros/node_modules/ts-node/src/index.ts:1455:23)
    at Module._extensions..js (node:internal/modules/cjs/loader:1153:10)
    at Object.require.extensions.<computed> [as .ts] (~/github/ts-node-repros/node_modules/ts-node/src/index.ts:1458:12)
    at Module.load (node:internal/modules/cjs/loader:981:32)
    at Function.Module._load (node:internal/modules/cjs/loader:822:12)
    at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:81:12)
    at phase4 (~/github/ts-node-repros/node_modules/ts-node/src/bin.ts:567:12)
    at bootstrap (~/github/ts-node-repros/node_modules/ts-node/src/bin.ts:85:10)
```
### Minimal reproduction

https://github.com/TypeStrong/ts-node-repros/pull/29

### Specifications

* ts-node version: `10.7.0`
* node version: `16.13.1`
* TypeScript version: `4.6.3`
* tsconfig.json, if you're using one: https://github.com/TypeStrong/ts-node-repros/pull/29/files#diff-b55cdbef4907b7045f32cc5360d48d262cca5f94062e353089f189f4460039e0
* Operating system and version: macOS 12.3.1
* If Windows, are you using WSL or WSL2?: N/A

**Comment by cspotcode** [comment]
Is this a bug in tsconfig-paths?

**Comment by andrejleitner** [comment]
You're right, it seems to work correctly without `tsconfig-paths`.

Cross-posting here: https://github.com/dividab/tsconfig-paths/issues/209

**Comment by cspotcode** [comment]
In that case, I'm going to close this issue since no code change is required in ts-node.

**Comment by andrejleitner** [comment]
Ok, in the meantime do you know about any alternative to `tsconfig-paths`?
