### ISSUE TITLE
MODULE_NOT_FOUND error for existing module ( in node_modules )

### ISSUE THREAD

**Issue by ThePlenkov** [TypeStrong/ts-node#1750]
Hi! I'm struggling with a very weird issue.

I've developed a simple module, which only has 1 ts file with types:
https://github.com/theplenkov-npm/gitlab-graphql-types

this file is generated during publishing that's why is not in the source code - but you can see it in node_modules

So when you install such a module - you can freely use types from it in ts files. You can write code, compile it using tsc - it all works.

However when I run same code via ts-node I have an error like this:
```
Error: Cannot find module 'gitlab-graphql-types'
Require stack:
- /workspace/commands/gitlab/[eval].ts
    at Function.Module._resolveFilename (node:internal/modules/cjs/loader:933:15)
    at Function.Module._resolveFilename.sharedData.moduleResolveFilenameHook.installedValue [as _resolveFilename] (/workspace/commands/gitlab/node_modules/@cspotcode/source-map-support/source-map-support.js:679:30)
    at Function.Module._load (node:internal/modules/cjs/loader:778:27)
    at Module.require (node:internal/modules/cjs/loader:1005:19)
    at /workspace/commands/gitlab/[eval].ts:1:1
    at Script.runInThisContext (node:vm:129:12)
    at runInContext (/workspace/commands/gitlab/node_modules/ts-node/src/repl.ts:636:19)
    at Object.execCommand (/workspace/commands/gitlab/node_modules/ts-node/src/repl.ts:602:28)
    at /workspace/commands/gitlab/node_modules/ts-node/src/repl.ts:624:47
    at Array.reduce (<anonymous>) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [ '/workspace/commands/gitlab/[eval].ts' ]
```

I've prepared a simple example:
https://gitpod.io#snapshot/2124fbf1-1fb2-4aad-86f5-1f9b201a30e2

just try to go to:
```
cd test/ts-node
npm install
npm test
```

It's running a simple eval command but even that doesn't work.  

Could you please have a look? THis is only ts-node issue - not typescript. Thanks!

**Comment by ThePlenkov** [comment]
If i set traceResolution: true in tsconfig - i can also see an output like this:
```
File '/workspace/gitlab-graphql-types/test/ts-node/node_modules/gitlab-graphql-types/graphql.d.ts' exist - use it as a name resolution result.
Resolving real path for '/workspace/gitlab-graphql-types/test/ts-node/node_modules/gitlab-graphql-types/graphql.d.ts', result '/workspace/gitlab-graphql-types/test/ts-node/node_modules/gitlab-graphql-types/graphql.d.ts'.
```

**Comment by ThePlenkov** [comment]
wait - it's working - i imported the file wrongly
