### ISSUE TITLE
Investigate weird stack positions for thrown TSErrors

### ISSUE THREAD

**Issue by cspotcode** [TypeStrong/ts-node#1784]
An example pulled from the tests:
D:\\a\\ts-node\\ts-node\\tests\\node_modules\\ts-node\\src\\index.ts:147

That line number does not make sense in either the source ts nor the emitted js.

Is this a trace-mapping bug?

```
Error (JestAssertionError) {
    message: `␊
    expect(received).toBe(expected) // Object.is equality␊
    ␊
    Expected: null␊
    Received: [Error: Command failed: "D:\\a\\ts-node\\ts-node\\tests\\node_modules\\.bin\\ts-node" --esm ./index.mjs␊
    D:\\a\\ts-node\\ts-node\\tests\\node_modules\\ts-node\\src\\index.ts:147␊
    const shouldDebug = yn(env.TS_NODE_DEBUG);␊
                                              ^␊
    TSError: ⨯ Unable to compile TypeScript:␊
    static_import_from_mts.mts(13,25): error TS2339: Property 'default' does not exist on type 'typeof import("D:/a/ts-node/ts-node/tests/tmp/package-json-type=module_allowJs=false_typecheck_tsconfig-module=Node16/mts", { assert: { "resolution-mode": "import" } })'.·␊
    static_import_from_mts.mts(17,23): error TS2339: Property 'default' does not exist on type 'typeof import("D:/a/ts-node/ts-node/tests/tmp/package-json-type=module_allowJs=false_typecheck_tsconfig-module=Node16/ts", { assert: { "resolution-mode": "import" } })'.·␊
    static_import_from_mts.mts(19,25): error TS2339: Property 'default' does not exist on type 'typeof import("D:/a/ts-node/ts-node/tests/tmp/package-json-type=module_allowJs=false_typecheck_tsconfig-module=Node16/tsx", { assert: { "resolution-mode": "import" } })'.··␊
        at createTSError (D:\\a\\ts-node\\ts-node\\tests\\node_modules\\ts-node\\src\\index.ts:147:43)␊
        at reportTSError (D:\\a\\ts-node\\ts-node\\tests\\node_modules\\ts-node\\src\\index.ts:147:43)␊
        at getOutput (D:\\a\\ts-node\\ts-node\\tests\\node_modules\\ts-node\\dist\\index.js:69:657)␊
        at Object.compile (D:\\a\\ts-node\\ts-node\\tests\\node_modules\\ts-node\\src\\index.ts:453:18)␊
        at transformSource (D:\\a\\ts-node\\ts-node\\tests\\node_modules\\ts-node\\src\\esm.ts:119:2)␊
        at D:\\a\\ts-node\\ts-node\\tests\\node_modules\\ts-node\\src\\esm.ts:114:65␊
        at async addShortCircuitFlag (D:\\a\\ts-node\\ts-node\\tests\\node_modules\\ts-node\\src\\esm.ts:119:2)␊
        at async ESMLoader.load (node:internal/modules/esm/loader:584:20)␊
        at async ESMLoader.moduleProvider (node:internal/modules/esm/loader:435:11)␊
        at async link (node:internal/modules/esm/module_job:70:21) {␊
      diagnosticCodes: [ 2339, 2339, 2339 ]␊
    }␊
    ]␊
```

**Comment by cspotcode** [comment]
Doesn't repro locally so might be isolated to the test suite, perhaps a doubly-registered source-map-support?
