### ISSUE TITLE
Maximum call stack size exceeded when using node 18.6

### ISSUE THREAD

**Issue by faradaytrs** [TypeStrong/ts-node#1848]
### Search Terms

I have a project with kinda a lot of dependencies but i think problem are not them,  after upgrade to node 18.6 i can't start my project anymore.

### Expected Behavior

Running normally

### Actual Behavior

````bash
yarn run v1.22.19
$ NODE_OPTIONS='--es-module-specifier-resolution=node --loader ts-node/esm' nodemon --watch src -e js,ts,json -r dotenv/config src/server.ts --exec="yarn lint && node"
(node:36907) ExperimentalWarning: Custom ESM Loaders is an experimental feature. This feature could change at any time
(Use `node --trace-warnings ...` to show where the warning was created)
(node:36907) ExperimentalWarning: The Node.js specifier resolution flag is experimental. It could change or be removed at any time.
[nodemon] 2.0.19
[nodemon] to restart at any time, enter `rs`
[nodemon] watching path(s): src/**/*
[nodemon] watching extensions: js,ts,json
[nodemon] starting `ts-node -r dotenv/config src/server.ts "--exec=yarn lint && node"`
(node:36924) ExperimentalWarning: Custom ESM Loaders is an experimental feature. This feature could change at any time
(Use `node --trace-warnings ...` to show where the warning was created)
(node:36924) ExperimentalWarning: The Node.js specifier resolution flag is experimental. It could change or be removed at any time.
Exception in PromiseRejectCallback:
node:internal/modules/esm/loader:178
      return output;

RangeError: Maximum call stack size exceeded
Exception in PromiseRejectCallback:
/Users/imax/PhpstormProjects/atlas-api/node_modules/ts-node/dist/esm.js:120
                const { source: rawSource } = await defaultLoad(url, {
                                                    ^

RangeError: Maximum call stack size exceeded
RangeError: Maximum call stack size exceeded
    at validateArgs (node:internal/modules/esm/loader:590:27)
    at nextLoad (node:internal/modules/esm/loader:155:7)
    at /Users/imax/PhpstormProjects/atlas-api/node_modules/ts-node/src/esm.ts:255:45
    at addShortCircuitFlag (/Users/imax/PhpstormProjects/atlas-api/node_modules/ts-node/src/esm.ts:409:21)
    at load (/Users/imax/PhpstormProjects/atlas-api/node_modules/ts-node/src/esm.ts:239:12)
    at nextLoad (node:internal/modules/esm/loader:173:28)
    at /Users/imax/PhpstormProjects/atlas-api/node_modules/ts-node/src/esm.ts:255:45
    at addShortCircuitFlag (/Users/imax/PhpstormProjects/atlas-api/node_modules/ts-node/src/esm.ts:409:21)
    at load (/Users/imax/PhpstormProjects/atlas-api/node_modules/ts-node/src/esm.ts:239:12)
    at nextLoad (node:internal/modules/esm/loader:173:28)
[nodemon] app crashed - waiting for file changes before starting...
^C
andrei:atlas-api imax$ 
````

### Specifications

* ts-node version:
* node version:
* TypeScript version:
* tsconfig.json, if you're using one:
```
{
    "compilerOptions": {
        "target": "ES2022",
        "module": "esnext",
        "moduleResolution": "node",
        "lib": ["ES2021"],
        "allowJs": true,
        "allowSyntheticDefaultImports": true,
        "outDir": "build",
        "preserveSymlinks": true,
        "rootDir": "src",
        "strict": true,
        "declaration": true,
        "noImplicitAny": true,
        "skipLibCheck": true,
        "esModuleInterop": true,
        "resolveJsonModule": true,
        "noUnusedLocals": true,
        "forceConsistentCasingInFileNames": true,
        "importHelpers": true
        // "types": ["src/global.d.ts"]
    },
    "include": ["src/**/*", "src/types/package.json"],
    "exclude": [
        "src/test/**/*",
        "src/console/**/*",
        "src/test/**/*",
        "src/run-scripts/**/*"
    ],
    "ts-node": {
        "swc": true
    }
}

```
* package.json:
```
{
    "name": "atlas-api",
    "version": "9.4.7",
    "main": "build/server.js",
    "license": "MIT",
    "type": "module",
    "private": true,
    "engines": {
        "node": ">=18.0.0"
    },
    "dependencies": {
        "@alicloud/dysmsapi20170525": "2.0.16",
        "@ant-design/colors": "6.0.0",
        "@aws-sdk/client-s3": "3.135.0",
        "@aws-sdk/client-sns": "3.131.0",
        "@aws-sdk/lib-storage": "3.135.0",
        "@globuslimited/caprica": "0.7.1",
        "@globuslimited/holidays": "2.1.2",
        "@google-cloud/recaptcha-enterprise": "3.0.1",
        "@google-cloud/speech": "4.10.2",
        "@google-cloud/storage": "6.2.3",
        "@google-cloud/translate": "7.0.0",
        "@google-cloud/vision": "2.4.2",
        "@msgpack/msgpack": "2.7.2",
        "@prisma/client": "4.1.0",
        "@socket.io/admin-ui": "0.4.0",
        "@socket.io/mongo-adapter": "0.2.1",
        "@socket.io/mongo-emitter": "0.1.0",
        "axios": "0.27.2",
        "body-parser": "1.20.0",
        "cheerio": "1.0.0-rc.12",
        "compression": "1.7.4",
        "cors": "2.8.5",
        "dayjs": "1.11.4",
        "exceljs": "4.3.0",
        "express": "4.18.1",
        "form-data": "4.0.0",
        "formidable": "2.0.1",
        "google-auth-library": "8.1.1",
        "googleapis": "105.0.0",
        "immer": "9.0.15",
        "joi": "17.6.0",
        "jsonwebtoken": "8.5.1",
        "libphonenumber-js": "1.10.9",
        "messagebird": "3.8.1",
        "mime-types": "2.1.35",
        "mongodb": "4.8.0",
        "murmurhash": "2.0.1",
        "node-cron": "3.0.1",
        "object-hash": "3.0.0",
        "query-string": "7.1.1",
        "ramda": "0.28.0",
        "sharp": "0.30.7",
        "socket.io": "4.5.1",
        "tencentcloud-sdk-nodejs": "4.0.388",
        "ua-parser-js": "1.0.2",
        "uuid": "8.3.2"
    },
    "devDependencies": {
        "@swc/core": "1.2.218",
        "@types/compression": "1.7.2",
        "@types/express": "4.17.13",
        "@types/formidable": "2.0.5",
        "@types/jsonwebtoken": "8.5.8",
        "@types/mime-types": "2.1.1",
        "@types/node": "18.6.1",
        "@types/object-hash": "2.2.1",
        "@types/ramda": "0.28.15",
        "@types/sharp": "0.30.4",
        "@types/supertest": "2.0.12",
        "@types/ua-parser-js": "0.7.36",
        "@types/uuid": "8.3.4",
        "@vercel/nft": "0.21.0",
        "dotenv": "16.0.1",
        "eslint": "8.20.0",
        "eslint-config-prettier": "8.5.0",
        "eslint-plugin-eslint-comments": "3.2.0",
        "eslint-plugin-functional": "4.2.2",
        "eslint-plugin-immutable": "1.0.0",
        "eslint-plugin-node": "11.1.0",
        "eslint-plugin-prettier": "4.2.1",
        "husky": "8.0.1",
        "prettier": "2.7.1",
        "pretty-quick": "3.1.3",
        "prisma": "4.1.0",
        "release-it": "15.1.4",
        "supertest": "6.2.4",
        "ts-node": "10.9.1",
        "typescript": "4.7.4",
        "undici": "5.8.0",
        "vitest": "0.19.1"
    },
    "scripts": {
        "start": "NODE_OPTIONS='--es-module-specifier-resolution=node --loader ts-node/esm' nodemon --watch src -e js,ts,json -r dotenv/config src/server.ts --exec=\"yarn lint && node\"",
        "lint": "eslint src",
        "reloaddb": "bash reloaddb.sh",
        "release": "set -a && source .env && set +a && release-it",
        "prettier": "prettier --write src",
        "build": "tsc",
        "start:prod": "node --es-module-specifier-resolution=node build/server.js",
        "execute:local": "node --es-module-specifier-resolution=node -r dotenv/config",
        "execute": "node --es-module-specifier-resolution=node",
        "prepare": "husky install",
        "postinstall": "prisma generate",
        "pretty-quick": "pretty-quick",
        "test": "vitest",
        "bundle": "node ./prepare-for-production.mjs"
    },
    "prettier": {
        "printWidth": 80,
        "trailingComma": "all",
        "tabWidth": 4,
        "singleQuote": false,
        "bracketSpacing": false,
        "useTabs": false,
        "bracketSameLine": false,
        "arrowParens": "always",
        "semi": true,
        "quoteProps": "as-needed"
    },
    "release-it": {
        "git": {
            "commit": true,
            "tag": true,
            "push": true
        },
        "github": {
            "release": true
        },
        "npm": {
            "publish": false
        },
        "hooks": {
            "before:init": [
                "yarn lint",
                "tsc --noEmit"
            ]
        }
    }
}

```
* Operating system and version:
* If Windows, are you using WSL or WSL2?:
MacOs 12.5

**Comment by cspotcode** [comment]
Upgrade to the latest ts-node

**Comment by faradaytrs** [comment]
@cspotcode but i use latest version which is 10.9.1 and i still have this error.

**Comment by cspotcode** [comment]
I see some requested information was omitted from the issue template.  The reproduction is also far too big for anyone to run; it'll need to be shrunk down.

It should meet the requirements described here:
https://en.wikipedia.org/wiki/Minimal_reproducible_example

**Comment by hughrawlinson** [comment]
I'm having this same issue too, but I can't repro it outside of my project repo.

In my project repo, the smallest "repro" I can do is to create an empty file `blank.ts` and run it:

```
./node_modules/.bin/ts-node-esm --experimental-specifier-resolution node bin/blank.ts
```

I expect the command to run the file and exit 0, but instead I get

```
Exception in PromiseRejectCallback:
/Users/hrawlinson/code/docs-mdx-serializer/node_modules/ts-node/dist/esm.js:133
            return { format, source };

RangeError: Maximum call stack size exceeded
Exception in PromiseRejectCallback:
/Users/hrawlinson/code/docs-mdx-serializer/node_modules/ts-node/dist/esm.js:219
    const ret = await fn();
                      ^

RangeError: Maximum call stack size exceeded
RangeError: Maximum call stack size exceeded
    at nextLoad (node:internal/modules/esm/loader:151:5)
    at /Users/hrawlinson/code/docs-mdx-serializer/node_modules/ts-node/src/esm.ts:255:45
    at addShortCircuitFlag (/Users/hrawlinson/code/docs-mdx-serializer/node_modules/ts-node/src/esm.ts:409:21)
    at load (/Users/hrawlinson/code/docs-mdx-serializer/node_modules/ts-node/src/esm.ts:239:12)
    at load (/Users/hrawlinson/code/docs-mdx-serializer/node_modules/ts-node/src/child/child-loader.ts:18:36)
    at nextLoad (node:internal/modules/esm/loader:173:28)
    at /Users/hrawlinson/code/docs-mdx-serializer/node_modules/ts-node/src/esm.ts:255:45
    at addShortCircuitFlag (/Users/hrawlinson/code/docs-mdx-serializer/node_modules/ts-node/src/esm.ts:409:21)
    at load (/Users/hrawlinson/code/docs-mdx-serializer/node_modules/ts-node/src/esm.ts:239:12)
    at load (/Users/hrawlinson/code/docs-mdx-serializer/node_modules/ts-node/src/child/child-loader.ts:18:36)
 ```
 
So I tried to create a repro by creating a new empty repository, creating the same blank file, and copying the same tsconfig over, and specifying `"type": "module"` in `package.json`.  But in this scenario the code behaves as I expect - it runs and exits 0.

I would love to help by creating a minimal repro, but unfortunately I can't figure out what's causing this behavior. If you can think of any further configuration locations I ought to check, I would be happy to try them. I'm using Node 18.6.0 too.

**Comment by davidsansay** [comment]
Same issue here with node18.

With node16 ts-node & ts-node-esm work fine.

With node18 ts-node & ts-node-esm fail.

```
Exception in PromiseRejectCallback:
.../node_modules/ts-node/dist/esm.js:133
            return { format, source };

RangeError: Maximum call stack size exceeded
Exception in PromiseRejectCallback:
.../node_modules/ts-node/dist/esm.js:219
    const ret = await fn();
                      ^

RangeError: Maximum call stack size exceeded
.../node_modules/ts-node/src/esm.ts:409
  const ret = await fn();
                    ^
RangeError: Maximum call stack size exceeded
...
```

## Solution 1:

`node --no-warnings --experimental-specifier-resolution=node --loader ts-node/esm`

## Solution 2: 

"ts-node": "^10.9.1",
"typescript": "^4.9.5"

**Comment by jfstephe** [comment]
Having similar issues with tsx with v18.7.0. v18.14.2 seems ok though.
