### ISSUE TITLE
TSError:Unable to compile TypeScript: error TS5083: Cannot read file '/app/tsconfig.json'.

### ISSUE THREAD

**Issue by Edijae** [TypeStrong/ts-node#1850]
### Search Terms

TS5083 , Unable to compile TypeScript, Cannot read file tsconfig.json
### Expected Behavior

Compile typescript project 
### Actual Behavior

Compilation failing in docker using docker compose

```
TSError: ⨯ Unable to compile TypeScript:
error TS5083: Cannot read file '/app/tsconfig.json'.
at createTSError (/app/node_modules/ts-node/src/index.ts:859:12)
at reportTSError (/app/node_modules/ts-node/src/index.ts:863:19)
at createFromPreloadedConfig (/app/node_modules/ts-node/src/index.ts:874:36)
at phase4 (/app/node_modules/ts-node/src/bin.ts:543:44)
at bootstrap (/app/node_modules/ts-node/src/bin.ts:95:10)
at main (/app/node_modules/ts-node/src/bin.ts:55:10)
at Object.<anonymous> (/app/node_modules/ts-node/src/bin.ts:800:3)
at Module._compile (node:internal/modules/cjs/loader:1105:14)
at Object.Module._extensions..js (node:internal/modules/cjs/loader:1159:10)
at Module.load (node:internal/modules/cjs/loader:981:32) {
diagnosticCodes: [ 5083 ]
}
```

### Minimal reproduction

Project folder set up - (project root folder)/app/tsconfig.json
                                      (project root folder)/app/package.json
                                      (project root folder)/docker-compose.yml
**/app/tsconfig.json**
```
{
    "compilerOptions": {
        "rootDir": "./src",
        "outDir": "./bin",
        "allowJs": true,
        "checkJs": true,
        "moduleResolution": "node",
        "target": "ES2020",
        "module": "esnext",
        "strict": true,
        "noImplicitAny": false,
        "strictNullChecks": true,
        "types": ["node"],
        "lib": ["es6"],
        "esModuleInterop": true,
        "skipLibCheck": true,
        "forceConsistentCasingInFileNames": true,
        "allowUnreachableCode": true,
        "experimentalDecorators": true
    },
    "ts-node": {
        "esm": true
    },
    "include": ["./src/*",],
    "exclude": ["./node_modules/*","<node_internals>/**"],
}
```
**app/package.json**
```
{
  "version": "1.0.0",
  "description": "backend",
  "main": "src/index.ts",
  "scripts": {
    "test": "echo \"Error: no test specified\" && exit 1",
    "start": "ts-node src/index.ts"
  },
  "type": "module",
  "dependencies": {
```

**(project root folder)/docker-compose.yml**

```
version: '3'

services:
  
  portal:
    image: "node:16"
    user: "node"
    working_dir: /app
    restart: unless-stopped

    command: "npm start"


```

### Specifications

* ts-node version: ^10.9.1
* node version: ^4.7.4
* TypeScript version: ^4.7.4
* tsconfig.json, if you're using one:
```
{}
```
* package.json:
```
"devDependencies": {
    "@types/body-parser": "^1.19.2",
    "@types/express": "^4.17.13",
    "@types/image-thumbnail": "^1.0.1",
    "@types/multer": "^1.4.7",
    "@types/multiparty": "^0.0.33",
    "@types/node": "^18.6.1",
    "@types/sharp": "^0.29.5",
    "ts-node": "^10.9.1",
    "tslib": "^2.4.0",
    "typescript": "^4.7.4"
  }
```
* Operating system and version: digital ocean ubuntu 20.04.4 LTS droplet
* If Windows, are you using WSL or WSL2?:

**Comment by cspotcode** [comment]
Do you think that ts-node is doing anything wrong here?  The evidence suggests that your docker configuration is somehow making that file either nonexistent or inaccessible.  I'm not sure how ts-node would behave any differently in this situation.

**Comment by p3t3r67x0** [comment]
Hi @Edijae have you been able to understand what was going on?
