### ISSUE TITLE
Installed typescript-node and try to run the example in the Readme get the following error

### ISSUE THREAD

**Issue by aprinaresh97** [TypeStrong/ts-node#186]
It looks like the code in the github is newer than the package in the npm.

ts-node -e "console.log(\"Hello\")"

return ts.parseConfigFile(config, ts.sys, fileName);
              ^
TypeError: ts.parseConfigFile is not a function
    at readConfig (D:\udu\Test\node\tsnode\node_modules\typescript-node\dist\typescript-node.js:31:15)
    at Object.register (D:\udu\Test\node\tsnode\node_modules\typescript-node\dist\typescript-node.js:43:18)
    at Object.<anonymous> (D:\udu\Test\node\tsnode\node_modules\typescript-node\dist\bin\ts-node.js:34:33)
    at Module._compile (module.js:541:32)
    at Object.Module._extensions..js (module.js:550:10)
    at Module.load (module.js:458:32)
    at tryModuleLoad (module.js:417:12)
    at Function.Module._load (module.js:409:3)
    at Module.require (module.js:468:17)
    at require (internal/module.js:20:19)

**Comment by blakeembrey** [comment]
If you look at the README or read the warning when you installed, you would see `typescript-node` is deprecated.
