### ISSUE TITLE
Import of a typescript file fails if a folder named node_modules is anywhere within the path

### ISSUE THREAD

**Issue by erichosick** [TypeStrong/ts-node#1910]
### Expected Behavior

The [module resolution](https://www.typescriptlang.org/docs/handbook/module-resolution.html) of a typescript file using the [import declaration](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Statements/import) should successfully import the typescript file even when part of the path contains a directory named `node_modules`.

```typescript
// this works
import { something } from './source/node_modules2/index';
```

### Actual Behavior

Placing a typescript file anywhere in a project where part of the path contains a directory named `node_modules` results in failure to load the typescript file with the error `SyntaxError: Unexpected token ...`. Renaming the directory to anything else, even `node_modules2`, results in the successful import of the file.

```typescript
// this does not work
import { something } from './source/node_modules/index';
```

### Steps to reproduce the problem

Given a typescript file:

```typescript
// File: add.ts located in sub-folder2/node_modules2 and sub-folder/node_modules
const add = (left: number, right: number): number => {
  return left + right;
};

export default add;
```

```bash
// outputs 2
$ yarn ts-node works
$ /.../typescript-node-module-issue/node_modules/.bin/ts-node works
2
```

An import as follows works because the path **does not** contain a folder named `node_modules`.

```typescript
// File: works.ts
import add from './sub-folder2/node_modules2/add';
console.log(add(1, 1));
```

However, when the path **does** contain a folder named `node_modules` then the import fails with the error `SyntaxError: Unexpected token ...`:

```typescript
// File: fails.ts
import add from './sub-folder/node_modules/add';
console.log(add(1, 1));
```

```bash
// does not work
$ yarn ts-node fails
$ /.../typescript-node-module-issue/node_modules/.bin/ts-node fails
/.../typescript-node-module-issue/sub-folder/node_modules/add.ts:1
const add = (left: number, right: number): number => {
                 ^

SyntaxError: Unexpected token ':'
    at Object.compileFunction (node:vm:360:18)
    at wrapSafe (node:internal/modules/cjs/loader:1084:15)
    at Module._compile (node:internal/modules/cjs/loader:1119:27)
    at Module._extensions..js (node:internal/modules/cjs/loader:1209:10)
    at Object.require.extensions.<computed> [as .ts] (/.../typescript-node-module-issue/node_modules/ts-node/src/index.ts:1608:43)
    at Module.load (node:internal/modules/cjs/loader:1033:32)
    at Function.Module._load (node:internal/modules/cjs/loader:868:12)
    at Module.require (node:internal/modules/cjs/loader:1057:19)
    at require (node:internal/modules/cjs/helpers:103:18)
    at Object.<anonymous> (/.../typescript-node-module-issue/fails.ts:1:1)
```

### Minimal reproduction

See [typescript-node-module-issue](https://github.com/erichosick/typescript-node-module-issue) which contains the minimal code to reproduce the issue.

### Specifications

* ts-node v10.9.1
* node v16.18.0
* compiler v4.8.4

* tsconfig.json, if you're using one:
There is no tsconfig.json file

* package.json:
```
{
  "name": "typescript-node-module-issue",
  "version": "1.0.0",
  "license": "MIT",
  "devDependencies": {
    "@types/node": "^18.11.9",
    "ts-node": "^10.9.1",
    "typescript": "^4.8.4"
  }
}
```
* Operating system and version:
* macOS Monterey

**Comment by erichosick** [comment]
I'm not sure if the behavior should be for the import to work or fail. However, I feel it should be consistent: it should always work or fail for both cases (path contains a `node_modules` directory and path does not contain a `node_modules` directory.

**Comment by erichosick** [comment]
It may be that this issue is within the core code of node: [node:internal/modules/cjs/loader](https://github.com/nodejs/node/blob/97355c74e819cf5f429efef71654697870a6416c/lib/internal/modules/cjs/loader.js#L846) and not an issue with ts-node itself.

**Comment by erichosick** [comment]
Turns out this is expected behavior of node. See answer here: https://github.com/nodejs/node/issues/45453#issuecomment-1313121137 and doc here https://github.com/TypeStrong/ts-node/blob/ba950599c6bfcba32b514b33d254094b278b744e/website/docs/scope.md#skipping-node_modules .
