### ISSUE TITLE
Support for the experimental syntax 'decorators' isn't currently enabled

### ISSUE THREAD

**Issue by justinmchase** [TypeStrong/ts-node#1930]
### Search Terms

Support for the experimental syntax 'decorators' isn't currently enabled

### Expected Behavior

I expect it to not be using babel at all, I expect this to be using typescript compiler and using my tsconfig file configuration, which does have decorator support enabled.

### Actual Behavior

```
SyntaxError[ @/Users/jchase24/code/recovery/apps/recovery-auth-api/src/controllers/auth.controller.test.ts ]: /Users/jchase24/code/recovery/apps/recovery-auth-api/src/controllers/auth.controller.ts: Support for the experimental syntax 'decorators' isn't currently enabled (45:1):

  43 | import { ConfigService } from '../services/config/config.service.js'
  44 |
> 45 | @ApiPath({
     | ^
  46 |   path: '/',
  47 |   name: 'Authentication'
  48 | })

Add @babel/plugin-proposal-decorators (https://github.com/babel/babel/tree/main/packages/babel-plugin-proposal-decorators) to the 'plugins' section of your Babel config to enable transformation.
If you want to leave it as-is, add @babel/plugin-syntax-decorators (https://github.com/babel/babel/tree/main/packages/babel-plugin-syntax-decorators) to the 'plugins' section to enable parsing.
    at instantiate (/Users/jchase24/code/recovery/apps/recovery-auth-api/node_modules/@babel/parser/src/parse-error/credentials.ts:62:21)
    at toParseError (/Users/jchase24/code/recovery/apps/recovery-auth-api/node_modules/@babel/parser/src/parse-error.ts:60:12)
    at Parser.raise (/Users/jchase24/code/recovery/apps/recovery-auth-api/node_modules/@babel/parser/src/tokenizer/index.ts:1474:19)
    at Parser.expectOnePlugin (/Users/jchase24/code/recovery/apps/recovery-auth-api/node_modules/@babel/parser/src/tokenizer/index.ts:1539:18)
    at Parser.parseDecorator (/Users/jchase24/code/recovery/apps/recovery-auth-api/node_modules/@babel/parser/src/parser/statement.ts:713:10)
    at Parser.parseDecorators (/Users/jchase24/code/recovery/apps/recovery-auth-api/node_modules/@babel/parser/src/parser/statement.ts:692:28)
    at Parser.parseStatementLike (/Users/jchase24/code/recovery/apps/recovery-auth-api/node_modules/@babel/parser/src/parser/statement.ts:418:25)
    at Parser.parseModuleItem (/Users/jchase24/code/recovery/apps/recovery-auth-api/node_modules/@babel/parser/src/parser/statement.ts:365:17)
    at Parser.parseBlockOrModuleBlockBody (/Users/jchase24/code/recovery/apps/recovery-auth-api/node_modules/@babel/parser/src/parser/statement.ts:1345:16)
    at Parser.parseBlockBody (/Users/jchase24/code/recovery/apps/recovery-auth-api/node_modules/@babel/parser/src/parser/statement.ts:1319:10)
    at Parser.parseProgram (/Users/jchase24/code/recovery/apps/recovery-auth-api/node_modules/@babel/parser/src/parser/statement.ts:226:10)
    at Parser.parseTopLevel (/Users/jchase24/code/recovery/apps/recovery-auth-api/node_modules/@babel/parser/src/parser/statement.ts:208:25)
    at Parser.parse (/Users/jchase24/code/recovery/apps/recovery-auth-api/node_modules/@babel/parser/src/parser/index.ts:45:10)
    at parse (/Users/jchase24/code/recovery/apps/recovery-auth-api/node_modules/@babel/parser/src/index.ts:67:38)
    at parser (/Users/jchase24/code/recovery/apps/recovery-auth-api/node_modules/@babel/core/src/parser/index.ts:28:19)
    at parser.next (<anonymous>)
    at normalizeFile (/Users/jchase24/code/recovery/apps/recovery-auth-api/node_modules/@babel/core/src/transformation/normalize-file.ts:52:24)
    at normalizeFile.next (<anonymous>)
    at run (/Users/jchase24/code/recovery/apps/recovery-auth-api/node_modules/@babel/core/src/transformation/index.ts:38:36)
    at run.next (<anonymous>)
    at transform (/Users/jchase24/code/recovery/apps/recovery-auth-api/node_modules/@babel/core/src/transform.ts:29:20)
    at transform.next (<anonymous>)
    at step (/Users/jchase24/code/recovery/apps/recovery-auth-api/node_modules/gensync/index.js:261:32)
    at /Users/jchase24/code/recovery/apps/recovery-auth-api/node_modules/gensync/index.js:273:13
    at async.call.result.err.err (/Users/jchase24/code/recovery/apps/recovery-auth-api/node_modules/gensync/index.js:223:11)
    at cb (/Users/jchase24/code/recovery/apps/recovery-auth-api/node_modules/gensync/index.js:189:28)
    at /Users/jchase24/code/recovery/apps/recovery-auth-api/node_modules/@babel/core/src/gensync-utils/async.ts:90:7
    at /Users/jchase24/code/recovery/apps/recovery-auth-api/node_modules/gensync/index.js:113:33
    at step (/Users/jchase24/code/recovery/apps/recovery-auth-api/node_modules/gensync/index.js:287:14)
    at /Users/jchase24/code/recovery/apps/recovery-auth-api/node_modules/gensync/index.js:273:13
    at async.call.result.err.err (/Users/jchase24/code/recovery/apps/recovery-auth-api/node_modules/gensync/index.js:223:11)
```

### Steps to reproduce the problem

Here is my mocha config:
```
  "mocha": {
    "parallel": false,
    "loader": [
      "@istanbuljs/esm-loader-hook",
      "ts-node/esm"
    ],
    "spec": [
      "src/**/*.test.ts"
    ],
    "extension": [
      "ts"
    ]
  },
```
Then I'm just running `mocha`

Make a ts file with a decorator on a class.

### Minimal reproduction

If you actually want this I'll make it but I'm not gonna go through this effort until its warranted.

### Specifications

ts-node v10.9.1
node v16.17.0
compiler v4.6.4
* tsconfig.json, if you're using one:
```
{
  "compilerOptions": {
    "module": "esnext",
    "target": "esnext",
    "moduleResolution": "node",
    "lib": ["ES2019", "ESNext.AsyncIterable"],
    "outDir": "dest",
    "rootDir": "src",
    "sourceMap": true,
    "experimentalDecorators": true,
    "emitDecoratorMetadata": true,
    "allowSyntheticDefaultImports": true,
    "skipLibCheck": true,
    "strictNullChecks": true
  },
  "include": ["src"],
  "exclude": ["node_modules"]
}

```
* package.json:
```
{}
```
* Operating system and version: osx
* If Windows, are you using WSL or WSL2?:

**Comment by justinmchase** [comment]
Ok good news for you all here, I actually realized it was my other loader `@istanbuljs/esm-loader-hook` that is causing the issue.
