### ISSUE TITLE
Cannot find dependent packages while using `ts-node-esm` with `yarn berry` under `pnp mode`.

### ISSUE THREAD

**Issue by LvChengbin** [TypeStrong/ts-node#1941]
### Actual Behavior

Cannot find dependent packages while using `ts-node-esm` with `yarn berry` under `pnp mode`.
I'm not sure if it should be an issue of `ts-node` project, but it's working well while using `yarn node` command and `yarn ts-node` command.

I know the issue of chaining loaders of nodejs, so I upgraded my nodejs to the latest version (19.4.0) which seems has already supported chaining loaders.

### Steps to reproduce the problem

Sample code:

```ts
import escapeStringRegexp from 'escape-string-regexp';
console.log( escapeStringRegexp );
```

```sh
% yarn node src/index.js
[Function: escapeStringRegexp]
```

```sh
% yarn ts-node --transpile-only src/index.js
[Function: escapeStringRegexp]
```

```sh
% yarn ts-node-esm --transpile-only src/index.js
/Users/Workspace/test/esmodule/.yarn/__virtual__/ts-node-virtual-920353443a/0/cache/ts-node-npm-10.9.1-6c268be7f4-090adff130.zip/node_modules/ts-node/dist-raw/node-internal-modules-esm-resolve.js:757
  throw new ERR_MODULE_NOT_FOUND(packageName, fileURLToPath(base));
        ^
CustomError: Cannot find package 'escape-string-regexp' imported from /Users/Workspace/test/esmodule/src/index.js
    at packageResolve (/Users/Workspace/test/esmodule/.yarn/__virtual__/ts-node-virtual-920353443a/0/cache/ts-node-npm-10.9.1-6c268be7f4-090adff130.zip/node_modules/ts-node/dist-raw/node-internal-modules-esm-resolve.js:757:9)
    at moduleResolve (/Users/Workspace/test/esmodule/.yarn/__virtual__/ts-node-virtual-920353443a/0/cache/ts-node-npm-10.9.1-6c268be7f4-090adff130.zip/node_modules/ts-node/dist-raw/node-internal-modules-esm-resolve.js:798:18)
    at Object.defaultResolve (/Users/Workspace/test/esmodule/.yarn/__virtual__/ts-node-virtual-920353443a/0/cache/ts-node-npm-10.9.1-6c268be7f4-090adff130.zip/node_modules/ts-node/dist-raw/node-internal-modules-esm-resolve.js:912:11)
    at /Users/Workspace/test/esmodule/.yarn/__virtual__/ts-node-virtual-920353443a/0/cache/ts-node-npm-10.9.1-6c268be7f4-090adff130.zip/node_modules/ts-node/src/esm.ts:218:35
    at entrypointFallback (/Users/Workspace/test/esmodule/.yarn/__virtual__/ts-node-virtual-920353443a/0/cache/ts-node-npm-10.9.1-6c268be7f4-090adff130.zip/node_modules/ts-node/src/esm.ts:168:34)
    at /Users/Workspace/test/esmodule/.yarn/__virtual__/ts-node-virtual-920353443a/0/cache/ts-node-npm-10.9.1-6c268be7f4-090adff130.zip/node_modules/ts-node/src/esm.ts:217:14
    at addShortCircuitFlag (/Users/Workspace/test/esmodule/.yarn/__virtual__/ts-node-virtual-920353443a/0/cache/ts-node-npm-10.9.1-6c268be7f4-090adff130.zip/node_modules/ts-node/src/esm.ts:409:21)
    at resolve (/Users/Workspace/test/esmodule/.yarn/__virtual__/ts-node-virtual-920353443a/0/cache/ts-node-npm-10.9.1-6c268be7f4-090adff130.zip/node_modules/ts-node/src/esm.ts:197:12)
    at resolve (/Users/Workspace/test/esmodule/.yarn/__virtual__/ts-node-virtual-920353443a/0/cache/ts-node-npm-10.9.1-6c268be7f4-090adff130.zip/node_modules/ts-node/src/child/child-loader.ts:15:39)
    at nextResolve (node:internal/modules/esm/loader:164:28)
```

### Specifications

* ts-node version: 10.9.1
* node version: v19.4.0
* TypeScript version: 4.9.4
* tsconfig.json, if you're using one:
```
{
    "compilerOptions": {
        "outDir" : "./lib/",
        "rootDir" : "./src/",
        /* Visit https://aka.ms/tsconfig to read more about this file */

        /* Projects */
        // "incremental": true,                              /* Save .tsbuildinfo files to allow for incremental compilation of projects. */
        "composite": true,                                /* Enable constraints that allow a TypeScript project to be used with project references. */
        // "tsBuildInfoFile": "./.tsbuildinfo",              /* Specify the path to .tsbuildinfo incremental compilation file. */
        // "disableSourceOfProjectReferenceRedirect": true,  /* Disable preferring source files instead of declaration files when referencing composite projects. */
        // "disableSolutionSearching": true,                 /* Opt a project out of multi-project reference checking when editing. */
        // "disableReferencedProjectLoad": true,             /* Reduce the number of projects loaded automatically by TypeScript. */

        /* Language and Environment */
        "target": "ESNext",                                  /* Set the JavaScript language version for emitted JavaScript and include compatible library declarations. */
        // "lib": [],                                        /* Specify a set of bundled library declaration files that describe the target runtime environment. */
        // "jsx": "preserve",                                /* Specify what JSX code is generated. */
        "experimentalDecorators": true,                   /* Enable experimental support for TC39 stage 2 draft decorators. */
        "emitDecoratorMetadata": true,                    /* Emit design-type metadata for decorated declarations in source files. */
        // "jsxFactory": "",                                 /* Specify the JSX factory function used when targeting React JSX emit, e.g. 'React.createElement' or 'h'. */
        // "jsxFragmentFactory": "",                         /* Specify the JSX Fragment reference used for fragments when targeting React JSX emit e.g. 'React.Fragment' or 'Fragment'. */
        // "jsxImportSource": "",                            /* Specify module specifier used to import the JSX factory functions when using 'jsx: react-jsx*'. */
        // "reactNamespace": "",                             /* Specify the object invoked for 'createElement'. This only applies when targeting 'react' JSX emit. */
        // "noLib": true,                                    /* Disable including any library files, including the default lib.d.ts. */
        // "useDefineForClassFields": true,                  /* Emit ECMAScript-standard-compliant class fields. */
        // "moduleDetection": "auto",                        /* Control what method is used to detect module-format JS files. */

        /* Modules */
        "module": "ESNext",                                /* Specify what module code is generated. */
        // "rootDir": "./",                                  /* Specify the root folder within your source files. */
        "moduleResolution": "node",                       /* Specify how TypeScript looks up a file from a given module specifier. */
        "baseUrl": "./",                                  /* Specify the base directory to resolve non-relative module names. */
        // "paths": {},                                      /* Specify a set of entries that re-map imports to additional lookup locations. */
        // "rootDirs": [],                                   /* Allow multiple folders to be treated as one when resolving modules. */
        // "typeRoots": [],                                  /* Specify multiple folders that act like './node_modules/@types'. */
        // "types": [],                                      /* Specify type package names to be included without being referenced in a source file. */
        // "allowUmdGlobalAccess": true,                     /* Allow accessing UMD globals from modules. */
        // "moduleSuffixes": [],                             /* List of file name suffixes to search when resolving a module. */
        "resolveJsonModule": false,                        /* Enable importing .json files. */
        // "noResolve": true,                                /* Disallow 'import's, 'require's or '<reference>'s from expanding the number of files TypeScript should add to a project. */

        /* JavaScript Support */
        // "allowJs": true,                                  /* Allow JavaScript files to be a part of your program. Use the 'checkJS' option to get errors from these files. */
        // "checkJs": true,                                  /* Enable error reporting in type-checked JavaScript files. */
        // "maxNodeModuleJsDepth": 1,                        /* Specify the maximum folder depth used for checking JavaScript files from 'node_modules'. Only applicable with 'allowJs'. */

        /* Emit */
        // "declaration": true,                              /* Generate .d.ts files from TypeScript and JavaScript files in your project. */
        // "declarationMap": true,                           /* Create sourcemaps for d.ts files. */
        // "emitDeclarationOnly": true,                      /* Only output d.ts files and not JavaScript files. */
        // "sourceMap": true,                                /* Create source map files for emitted JavaScript files. */
        // "outFile": "./",                                  /* Specify a file that bundles all outputs into one JavaScript file. If 'declaration' is true, also designates a file that bundles all .d.ts output. */
        // "outDir": "./",                                   /* Specify an output folder for all emitted files. */
        // "removeComments": true,                           /* Disable emitting comments. */
        // "noEmit": true,                                   /* Disable emitting files from a compilation. */
        // "importHelpers": true,                            /* Allow importing helper functions from tslib once per project, instead of including them per-file. */
        // "importsNotUsedAsValues": "remove",               /* Specify emit/checking behavior for imports that are only used for types. */
        // "downlevelIteration": true,                       /* Emit more compliant, but verbose and less performant JavaScript for iteration. */
        // "sourceRoot": "",                                 /* Specify the root path for debuggers to find the reference source code. */
        // "mapRoot": "",                                    /* Specify the location where debugger should locate map files instead of generated locations. */
        // "inlineSourceMap": true,                          /* Include sourcemap files inside the emitted JavaScript. */
        // "inlineSources": true,                            /* Include source code in the sourcemaps inside the emitted JavaScript. */
        // "emitBOM": true,                                  /* Emit a UTF-8 Byte Order Mark (BOM) in the beginning of output files. */
        // "newLine": "crlf",                                /* Set the newline character for emitting files. */
        // "stripInternal": true,                            /* Disable emitting declarations that have '@internal' in their JSDoc comments. */
        // "noEmitHelpers": true,                            /* Disable generating custom helper functions like '__extends' in compiled output. */
        // "noEmitOnError": true,                            /* Disable emitting files if any type checking errors are reported. */
        // "preserveConstEnums": true,                       /* Disable erasing 'const enum' declarations in generated code. */
        // "declarationDir": "./",                           /* Specify the output directory for generated declaration files. */
        // "preserveValueImports": true,                     /* Preserve unused imported values in the JavaScript output that would otherwise be removed. */

        /* Interop Constraints */
        // "isolatedModules": true,                          /* Ensure that each file can be safely transpiled without relying on other imports. */
        // "allowSyntheticDefaultImports": true,             /* Allow 'import x from y' when a module doesn't have a default export. */
        "esModuleInterop": true,                             /* Emit additional JavaScript to ease support for importing CommonJS modules. This enables 'allowSyntheticDefaultImports' for type compatibility. */
        // "preserveSymlinks": true,                         /* Disable resolving symlinks to their realpath. This correlates to the same flag in node. */
        "forceConsistentCasingInFileNames": true,            /* Ensure that casing is correct in imports. */

        /* Type Checking */
        "strict": true,                                      /* Enable all strict type-checking options. */
        // "noImplicitAny": true,                            /* Enable error reporting for expressions and declarations with an implied 'any' type. */
        // "strictNullChecks": true,                         /* When type checking, take into account 'null' and 'undefined'. */
        // "strictFunctionTypes": true,                      /* When assigning functions, check to ensure parameters and the return values are subtype-compatible. */
        // "strictBindCallApply": true,                      /* Check that the arguments for 'bind', 'call', and 'apply' methods match the original function. */
        // "strictPropertyInitialization": true,             /* Check for class properties that are declared but not set in the constructor. */
        // "noImplicitThis": true,                           /* Enable error reporting when 'this' is given the type 'any'. */
        // "useUnknownInCatchVariables": true,               /* Default catch clause variables as 'unknown' instead of 'any'. */
        // "alwaysStrict": true,                             /* Ensure 'use strict' is always emitted. */
        // "noUnusedLocals": true,                           /* Enable error reporting when local variables aren't read. */
        // "noUnusedParameters": true,                       /* Raise an error when a function parameter isn't read. */
        // "exactOptionalPropertyTypes": true,               /* Interpret optional property types as written, rather than adding 'undefined'. */
        // "noImplicitReturns": true,                        /* Enable error reporting for codepaths that do not explicitly return in a function. */
        // "noFallthroughCasesInSwitch": true,               /* Enable error reporting for fallthrough cases in switch statements. */
        // "noUncheckedIndexedAccess": true,                 /* Add 'undefined' to a type when accessed using an index. */
        // "noImplicitOverride": true,                       /* Ensure overriding members in derived classes are marked with an override modifier. */
        // "noPropertyAccessFromIndexSignature": true,       /* Enforces using indexed accessors for keys declared using an indexed type. */
        // "allowUnusedLabels": true,                        /* Disable error reporting for unused labels. */
        // "allowUnreachableCode": true,                     /* Disable error reporting for unreachable code. */

        /* Completeness */
        // "skipDefaultLibCheck": true,                      /* Skip type checking .d.ts files that are included with TypeScript. */
        "skipLibCheck": true                                 /* Skip type checking all .d.ts files. */
    }
}
```
* package.json:
```
{
    "name": "esmodule",
    "version": "1.0.0",
    "main": "index.js",
    "license": "MIT",
    "type": "module",
    "devDependencies": {
        "@types/node": "^18.11.18",
        "ts-node": "^10.9.1",
        "typescript": "^4.9.4"
    },
    "dependencies": {
        "escape-string-regexp": "^5.0.0"
    }
}
```
* Operating system and version: MacOS 13.1
* If Windows, are you using WSL or WSL2?:

**Comment by ruckonic** [comment]
Update the `tsconfig.json`
```json
{
  "compilerOptions": {
       ...,
       "module": "NodeNext",
        "moduleResolution": "NodeNext",
        "esModuleInterop": true
  }
}
```

**Comment by sdvina** [comment]
I have the same issue

**Comment by ruckonic** [comment]
Try `node --loader=ts-node/esm`

**Comment by sdvina** [comment]
> 

I use   `ts-node-esm file.ts  `     CustomError: Cannot find package that import in file.ts

**Comment by sdvina** [comment]
> Try `node --loader=ts-node/esm file.js`

I use `ts-node-esm file.ts`  CustomError: Cannot find package XXX imported from file.ts

**Comment by ezracelli** [comment]
Same issue here, even with `--loader ts-node/esm`.

Tried:

```console
$ yarn exec ts-node-esm "$script"
Error [ERR_MODULE_NOT_FOUND]: Cannot find package '/xxx/.yarn/__virtual__/ts-node-virtual-xxx/0/cache/xxx/ts-node-npm-10.9.1-xxx.zip/node_modules/ts-node/child-loader.mjs' imported from $script

$ yarn exec ts-node --esm "$script"
Error [ERR_MODULE_NOT_FOUND]: Cannot find package '/xxx/.yarn/__virtual__/ts-node-virtual-xxx/0/cache/xxx/ts-node-npm-10.9.1-xxx.zip/node_modules/ts-node/child-loader.mjs' imported from $script

$ yarn node --loader ts-node/esm "$script"
Error [ERR_MODULE_NOT_FOUND]: Cannot find package 'ts-node' imported from $script

$ yarn node --loader "$(yarn node -p 'require.resolve("ts-node/esm")')" "$script"
Error [ERR_MODULE_NOT_FOUND]: Cannot find package '/xxx/.yarn/__virtual__/ts-node-virtual-xxx/0/cache/xxx/ts-node-npm-10.9.1-xxx.zip/node_modules/ts-node/esm.mjs' imported from $script
```

Figured maybe it's just a compatibilit issue with Yarn's `.zip` file storage, but still no luck after [unplugging](https://yarnpkg.com/cli/unplug) `ts-node` &mdash; though did get different errors:

```console
$ yarn exec ts-node-esm "$script"
/xxx/.yarn/unplugged/ts-node-virtual-xxx/node_modules/ts-node/dist-raw/node-internal-modules-esm-resolve.js:757
  throw new ERR_MODULE_NOT_FOUND(packageName, fileURLToPath(base));
        ^
CustomError: Cannot find package '$dependency' imported from $script

$ yarn exec ts-node --esm "$script"
/xxx/.yarn/unplugged/ts-node-virtual-xxx/node_modules/ts-node/dist-raw/node-internal-modules-esm-resolve.js:757
  throw new ERR_MODULE_NOT_FOUND(packageName, fileURLToPath(base));
        ^
CustomError: Cannot find package '$dependency' imported from $script

$ yarn node --loader ts-node/esm "$script"
Error [ERR_MODULE_NOT_FOUND]: Cannot find package 'ts-node' imported from $script

$ yarn node --loader "$(yarn node -p 'require.resolve("ts-node/esm")')" "$script"
/xxx/.yarn/unplugged/ts-node-virtual-xxx/node_modules/ts-node/dist-raw/node-internal-modules-esm-resolve.js:757
  throw new ERR_MODULE_NOT_FOUND(packageName, fileURLToPath(base));
        ^
CustomError: Cannot find package '$dependency' imported from $script
```

**Comment by sdvina** [comment]
> Same issue here, even with `--loader ts-node/esm`.
> 
> Tried:
> 
> ```
> $ yarn exec ts-node-esm "$script"
> Error [ERR_MODULE_NOT_FOUND]: Cannot find package '/xxx/.yarn/__virtual__/ts-node-virtual-xxx/0/cache/xxx/ts-node-npm-10.9.1-xxx.zip/node_modules/ts-node/child-loader.mjs' imported from $script
> 
> $ yarn exec ts-node --esm "$script"
> Error [ERR_MODULE_NOT_FOUND]: Cannot find package '/xxx/.yarn/__virtual__/ts-node-virtual-xxx/0/cache/xxx/ts-node-npm-10.9.1-xxx.zip/node_modules/ts-node/child-loader.mjs' imported from $script
> 
> $ yarn node --loader ts-node/esm "$script"
> Error [ERR_MODULE_NOT_FOUND]: Cannot find package 'ts-node' imported from $script
> 
> $ yarn node --loader "$(yarn node -p 'require.resolve("ts-node/esm")')" "$script"
> Error [ERR_MODULE_NOT_FOUND]: Cannot find package '/xxx/.yarn/__virtual__/ts-node-virtual-xxx/0/cache/xxx/ts-node-npm-10.9.1-xxx.zip/node_modules/ts-node/esm.mjs' imported from $script
> ```
> 
> Figured maybe it's just a compatibilit issue with Yarn's `.zip` file storage, but still no luck after [unplugging](https://yarnpkg.com/cli/unplug) `ts-node` — though did get different errors:
> 
> ```
> $ yarn exec ts-node-esm "$script"
> /xxx/.yarn/unplugged/ts-node-virtual-xxx/node_modules/ts-node/dist-raw/node-internal-modules-esm-resolve.js:757
>   throw new ERR_MODULE_NOT_FOUND(packageName, fileURLToPath(base));
>         ^
> CustomError: Cannot find package '$dependency' imported from $script
> 
> $ yarn exec ts-node --esm "$script"
> /xxx/.yarn/unplugged/ts-node-virtual-xxx/node_modules/ts-node/dist-raw/node-internal-modules-esm-resolve.js:757
>   throw new ERR_MODULE_NOT_FOUND(packageName, fileURLToPath(base));
>         ^
> CustomError: Cannot find package '$dependency' imported from $script
> 
> $ yarn node --loader ts-node/esm "$script"
> Error [ERR_MODULE_NOT_FOUND]: Cannot find package 'ts-node' imported from $script
> 
> $ yarn node --loader "$(yarn node -p 'require.resolve("ts-node/esm")')" "$script"
> /xxx/.yarn/unplugged/ts-node-virtual-xxx/node_modules/ts-node/dist-raw/node-internal-modules-esm-resolve.js:757
>   throw new ERR_MODULE_NOT_FOUND(packageName, fileURLToPath(base));
>         ^
> CustomError: Cannot find package '$dependency' imported from $script
> ```

SEE
[https://github.com/TypeStrong/ts-node/issues/1514](url)
[https://github.com/TypeStrong/ts-node/issues/1381](url)
ts-node does not recognize node third-party depencent packages

**Comment by sdvina** [comment]
> Same issue here, even with `--loader ts-node/esm`.
> 
> Tried:
> 
> ```
> $ yarn exec ts-node-esm "$script"
> Error [ERR_MODULE_NOT_FOUND]: Cannot find package '/xxx/.yarn/__virtual__/ts-node-virtual-xxx/0/cache/xxx/ts-node-npm-10.9.1-xxx.zip/node_modules/ts-node/child-loader.mjs' imported from $script
> 
> $ yarn exec ts-node --esm "$script"
> Error [ERR_MODULE_NOT_FOUND]: Cannot find package '/xxx/.yarn/__virtual__/ts-node-virtual-xxx/0/cache/xxx/ts-node-npm-10.9.1-xxx.zip/node_modules/ts-node/child-loader.mjs' imported from $script
> 
> $ yarn node --loader ts-node/esm "$script"
> Error [ERR_MODULE_NOT_FOUND]: Cannot find package 'ts-node' imported from $script
> 
> $ yarn node --loader "$(yarn node -p 'require.resolve("ts-node/esm")')" "$script"
> Error [ERR_MODULE_NOT_FOUND]: Cannot find package '/xxx/.yarn/__virtual__/ts-node-virtual-xxx/0/cache/xxx/ts-node-npm-10.9.1-xxx.zip/node_modules/ts-node/esm.mjs' imported from $script
> ```
> 
> Figured maybe it's just a compatibilit issue with Yarn's `.zip` file storage, but still no luck after [unplugging](https://yarnpkg.com/cli/unplug) `ts-node` — though did get different errors:
> 
> ```
> $ yarn exec ts-node-esm "$script"
> /xxx/.yarn/unplugged/ts-node-virtual-xxx/node_modules/ts-node/dist-raw/node-internal-modules-esm-resolve.js:757
>   throw new ERR_MODULE_NOT_FOUND(packageName, fileURLToPath(base));
>         ^
> CustomError: Cannot find package '$dependency' imported from $script
> 
> $ yarn exec ts-node --esm "$script"
> /xxx/.yarn/unplugged/ts-node-virtual-xxx/node_modules/ts-node/dist-raw/node-internal-modules-esm-resolve.js:757
>   throw new ERR_MODULE_NOT_FOUND(packageName, fileURLToPath(base));
>         ^
> CustomError: Cannot find package '$dependency' imported from $script
> 
> $ yarn node --loader ts-node/esm "$script"
> Error [ERR_MODULE_NOT_FOUND]: Cannot find package 'ts-node' imported from $script
> 
> $ yarn node --loader "$(yarn node -p 'require.resolve("ts-node/esm")')" "$script"
> /xxx/.yarn/unplugged/ts-node-virtual-xxx/node_modules/ts-node/dist-raw/node-internal-modules-esm-resolve.js:757
>   throw new ERR_MODULE_NOT_FOUND(packageName, fileURLToPath(base));
>         ^
> CustomError: Cannot find package '$dependency' imported from $script
> ```

SEE
https://github.com/TypeStrong/ts-node/issues/1514
https://github.com/TypeStrong/ts-node/issues/1381

ts-node really can not resolve Node third-part dependencies

**Comment by psychobolt** [comment]
Working example for `ts-node` (and additional loaders):



```sh
yarn -v
3.5.0
yarn add -DE ts-node
# any loaders must be unplugged or you'll get ERR_MODULE_NOT_FOUND
yarn unplug ts-node
# chain loaders
yarn node --loader file://$(yarn node -p \"require.resolve('ts-node')\")/../../esm.mjs --loader ./.pnp.loader.mjs scripts/bootstrap.ts # reference: https://github.com/psychobolt/vite-storybook-boilerplate/blob/cf1a70553fde830d4d2c4b2ab18003095ce34c7e/package.json#L7
```

**Comment by get6** [comment]
Thanks! @psychobolt 
You fixed my error!  😄

I want to add comments solving a problem. 
Add these lines to `tsconfig.json`

```json
"ts-node": {
    "transpileOnly": true,
    "esm": true,
}
```

**Comment by meotimdihia** [comment]
use `tsx`, the package supported `esm `better

**Comment by MyNameIsNeXTSTEP** [comment]
@psychobolt 
The suggested approach does not work well on the current Node LTS (v22), which gives the following error:
```Bash
(node:15764) [DEP0180] DeprecationWarning: fs.Stats constructor is deprecated.
(Use `node --trace-deprecation ...` to show where the warning was created)

node:internal/modules/run_main:122
    triggerUncaughtException(
    ^
[Object: null prototype] {
  [Symbol(nodejs.util.inspect.custom)]: [Function: [nodejs.util.inspect.custom]]
}

Node.js v22.10.0
```

Referring to the known issue:
- https://github.com/TypeStrong/ts-node/issues/2116
- https://stackoverflow.com/questions/78591135/nodejs-warning-deprecationwarning-fs-stats-constructor-is-deprecated

---

And the question still remains:
How to resolve the prolem of this issue with `ts-node` and `esm` for Node v22 under the yarn PnP system for typescript project ?

**Comment by MyNameIsNeXTSTEP** [comment]
@LvChengbin
Hi, have you managed to resolve the issue ?

**Comment by LvChengbin** [comment]
@MyNameIsNeXTSTEP I apologize for not resolving this issue. I attempted to migrate my projects to use esmodule, but ran into several roadblocks that proved challenging to overcome. I'll try again in the future.
