### ISSUE TITLE
ERR_UNKNOWN_FILE_EXTENSION for binaries without extension

### ISSUE THREAD

**Issue by emoriarty** [TypeStrong/ts-node#1943]
### Search Terms
ERR_UNKNOWN_FILE_EXTENSION, entrypoint, runmain

### Expected Behavior

Running `ts-node-esm` for binaries with no extension work without error in node 18.6 and greater.

### Actual Behavior

Executing `ts-node-esm` for binaries without extension (sequelize, uuid, tserver) throws the following error:

```bash
CustomError: ERR_UNKNOWN_FILE_EXTENSION  /Users/enriquearias/Workspace/swile/notifications-hub/node_modules/uuid/dist/bin/uuid
    at defaultGetFormat (/Users/enriquearias/Workspace/swile/notifications-hub/node_modules/ts-node/dist-raw/node-internal-modules-esm-get_format.js:93:15)
    at defer (/Users/enriquearias/Workspace/swile/notifications-hub/node_modules/ts-node/src/esm.ts:307:38)
    at entrypointFallback (/Users/enriquearias/Workspace/swile/notifications-hub/node_modules/ts-node/src/esm.ts:314:14)
    at getFormat (/Users/enriquearias/Workspace/swile/notifications-hub/node_modules/ts-node/src/esm.ts:352:17)
    at /Users/enriquearias/Workspace/swile/notifications-hub/node_modules/ts-node/src/esm.ts:268:10
    at addShortCircuitFlag (/Users/enriquearias/Workspace/swile/notifications-hub/node_modules/ts-node/dist/esm.js:233:23)
    at load (/Users/enriquearias/Workspace/swile/notifications-hub/node_modules/ts-node/dist/esm.js:122:16)
    at load (/Users/enriquearias/Workspace/swile/notifications-hub/node_modules/ts-node/src/child/child-loader.ts:18:36)
    at nextLoad (node:internal/modules/esm/loader:163:28)
    at ESMLoader.load (node:internal/modules/esm/loader:605:26)
```
This error happens only in node v18.6 and higher.

### Minimal reproduction

Create a project and install ts-node and [uuid](https://www.npmjs.com/package/uuid).
Make sure to use node 18.6 or greater.

Run the following command:
```bash
$(npm bin)/ts-node-esm $(npm bin)/uuid
```

The output should look as follows:
```bash
CustomError: ERR_UNKNOWN_FILE_EXTENSION  /Users/enriquearias/Workspace/swile/notifications-hub/node_modules/uuid/dist/bin/uuid
    at defaultGetFormat (/Users/enriquearias/Workspace/swile/notifications-hub/node_modules/ts-node/dist-raw/node-internal-modules-esm-get_format.js:93:15)
    at defer (/Users/enriquearias/Workspace/swile/notifications-hub/node_modules/ts-node/src/esm.ts:307:38)
    at entrypointFallback (/Users/enriquearias/Workspace/swile/notifications-hub/node_modules/ts-node/src/esm.ts:314:14)
    at getFormat (/Users/enriquearias/Workspace/swile/notifications-hub/node_modules/ts-node/src/esm.ts:352:17)
    at /Users/enriquearias/Workspace/swile/notifications-hub/node_modules/ts-node/src/esm.ts:268:10
    at addShortCircuitFlag (/Users/enriquearias/Workspace/swile/notifications-hub/node_modules/ts-node/dist/esm.js:233:23)
    at load (/Users/enriquearias/Workspace/swile/notifications-hub/node_modules/ts-node/dist/esm.js:122:16)
    at load (/Users/enriquearias/Workspace/swile/notifications-hub/node_modules/ts-node/src/child/child-loader.ts:18:36)
    at nextLoad (node:internal/modules/esm/loader:163:28)
    at ESMLoader.load (node:internal/modules/esm/loader:605:26)
```

On node v16 it works OK.
```bash
0be0cf0b-b216-4891-b6a2-db4bca3bd4a8
```

### Specifications

* ts-node version: 10.9.1
* node version: >= 18.6.0
* TypeScript version: 4.9.4
* Operating system and version: Mac OSX | Ubuntu

### Debug

After debugging the source code, I've noticed that the last version ([10.9.1](https://github.com/TypeStrong/ts-node/releases/tag/v10.9.1)) includes this [patch](https://github.com/TypeStrong/ts-node/pull/1838) which causes the issue here.

Concretely, the file [runmain-hack.js](https://github.com/TypeStrong/ts-node/blob/v10.9.1/dist-raw/runmain-hack.js) is importing the entrypoint file (uuid in the example above) which adds itself as `parentURL` in the current import context.

When the [`entrypointFallback`](https://github.com/TypeStrong/ts-node/blob/0e0da590b3c104ee515ae7b603c29d3d87620ce5/src/esm.ts#L164) function is executed, it is asked if the current file (specifier) is an entrypoint by calling the function [`isProbablyEntrypoint`](https://github.com/TypeStrong/ts-node/blob/0e0da590b3c104ee515ae7b603c29d3d87620ce5/src/esm.ts#L146).

One of the conditions to be a entrypoint in `isProbablyEntrypoint` is that there's no parent in the context. Because runmain-hack adds the parent in the context, the `rememberIsProbablyEntrypoint` object won't be updated.

This is important for files without extension, because when the function [`getFormat`](https://github.com/TypeStrong/ts-node/blob/0e0da590b3c104ee515ae7b603c29d3d87620ce5/src/esm.ts#L290) executes the [`defaultGetFormat`](https://github.com/TypeStrong/ts-node/blob/0e0da590b3c104ee515ae7b603c29d3d87620ce5/dist-raw/node-internal-modules-esm-get_format.js#L61) which [throws an error](https://github.com/TypeStrong/ts-node/blob/0e0da590b3c104ee515ae7b603c29d3d87620ce5/dist-raw/node-internal-modules-esm-get_format.js#L93) because there's no matching format, the catch body [checks if the file is an entrypoint](https://github.com/TypeStrong/ts-node/blob/0e0da590b3c104ee515ae7b603c29d3d87620ce5/src/esm.ts#L306). But, because the `rememberIsProbablyEntrypoint` was not set, instead of [returning the commonjs format](https://github.com/TypeStrong/ts-node/blob/0e0da590b3c104ee515ae7b603c29d3d87620ce5/src/esm.ts#L307), the error is re-thrown.

**Comment by cspotcode** [comment]
Thanks for reporting this and for the detailed investigation of the issue.  I've made a fix in #1952.
