### ISSUE TITLE
[Typescript 5.0] TypeError: value.replace is not a function

### ISSUE THREAD

**Issue by loynoir** [TypeStrong/ts-node#2000]
### Search Terms

- Typescript 5.0
- tsconfig extends array

### Expected Behavior
No error.

### Actual Behavior
```
$ npm exec -- ts-node --esm --swc ./path/to/reproduce.mts
/path/to/node_modules/ts-node/dist/util.js:62
    return value.replace(backslashRegExp, directorySeparator);
                 ^

TypeError: value.replace is not a function
    at normalizeSlashes (/path/to/node_modules/ts-node/dist/util.js:62:18)
    at Object.getExtendsConfigPath (/path/to/node_modules/ts-node/dist/ts-internals.js:24:54)
    at readConfig (/path/to/node_modules/ts-node/dist/configuration.js:127:64)
    at findAndReadConfig (/path/to/node_modules/ts-node/dist/configuration.js:50:84)
    at phase3 (/path/to/node_modules/ts-node/dist/bin.js:254:67)
    at bootstrap (/path/to/node_modules/ts-node/dist/bin.js:47:30)
    at Object.<anonymous> (/path/to/node_modules/ts-node/dist/child/child-entrypoint.js:23:21)
    at Module._compile (node:internal/modules/cjs/loader:1254:14)
    at Module._extensions..js (node:internal/modules/cjs/loader:1308:10)
    at Module.load (node:internal/modules/cjs/loader:1117:32)

Node.js v18.15.0
```

### Debug
```js
function normalizeSlashes(value) {console.warn({value})
    return value.replace(backslashRegExp, directorySeparator);
}
```

errrlog
```js
{
  value: [ '@tsconfig/strictest/tsconfig', '@tsconfig/node18/tsconfig' ]
}
```

### Specifications

* ts-node version: latest
* node version: v18.15.0
* TypeScript version: latest
* tsconfig.json, if you're using one:
```
  "extends": [
    "@tsconfig/strictest/tsconfig",
    "@tsconfig/node18/tsconfig"
  ],
```
* package.json:
```
{}
```
* Operating system and version:
* If Windows, are you using WSL or WSL2?:

### Additional

https://www.npmjs.com/package/@tsconfig/node18-strictest-esm

> This package has been deprecated
> Author message:
> TypeScript 5.0 supports combining TSConfigs using array syntax in extends

https://github.com/tsconfig/bases#what-about-combined-configs

> Because of previous limitations in the config extension system of TypeScript, this repo used to provide combined configs from a few common bases (like Node + ESM, Node + Strictest and so on).

> This issue is now moot since TypeScript v5.0.0, which provides the [ability to extend from multiple configs at once](https://devblogs.microsoft.com/typescript/announcing-typescript-5-0-rc/#supporting-multiple-configuration-files-in-extends). For instance, if you want to start from a Node 18 + Strictest base config, you can install both @tsconfig/node18 and @tsconfig/strictest packages and extend those configs like so:

```jsonc
// tsconfig.json
{
  "extends": ["@tsconfig/strictest/tsconfig", "@tsconfig/node18/tsconfig"]
}
```

https://devblogs.microsoft.com/typescript/announcing-typescript-5-0-rc/#supporting-multiple-configuration-files-in-extends

**Comment by loynoir** [comment]
Workaround

```sh
$ npm exec -- tsc --showConfig > tsconfig.tsnode.json
$ npm exec -- ts-node --project tsconfig.tsnode.json --esm --swc ./reproduce.mts
```

**Comment by basicdays** [comment]
Note that if you have a `ts-node` config section in your `tsconfig` file, that it won't be ported into your `tsc --showConfig` output. You'll need to manually copy that over after the hacked `tsconfig` file is created.

**Comment by mrkjdy** [comment]
It would be awesome if ts-node could release a fix for this! A package that I use (Cypress) uses ts-node internally, and the old @tsconfigs in the projects that I work on are incompatible with TypeScript 5 because they have some options that are no longer supported. So until ts-node is fixed and Cypress uses that new version, the projects that I work on will have to stick with TypeScript 4 and the old @tsconfigs.

**Comment by muratgozel** [comment]
Yep, this is kind of urgent for me too 😞

**Comment by sebaplaza** [comment]
Any news on this ?

**Comment by duckboy81** [comment]
May have to install direct from git until the next release, see https://github.com/TypeStrong/ts-node/pull/1958

**Comment by gspetrou** [comment]
Can we please get a 10.9.2 with just this fix? Is there any ETA? What is the benefit of waiting?

**Comment by liambutler-lawrence** [comment]
Agreed. It seems absurd that a primary package in the TS ecosystem hasn't release an update (that's already merged) to support the current version of the TS language.

**Comment by StevenDouillet** [comment]
Does someone have a workaround about this issue ?
It still blocking me while running end to end and unit tests 😞 

And i've got the same issue when i try to get the next dev release

**Comment by andykenward** [comment]
> Does someone have a workaround about this issue ? It still blocking me while running end to end and unit tests 😞
> 
> And i've got the same issue when i try to get the next dev release
> 
> **My workarround** : leave only one element on the extends (`"extends": "./node_modules/gts/tsconfig-google.json"`) and move others in the main tsconfig file

@StevenDouillet did you try the workaround by @loynoir https://github.com/TypeStrong/ts-node/issues/2000#issuecomment-1519339593

It outputs a `tsconfig.tsnode.json` from your `tsconfig.json` that `ts-node` can understands.

If it helps I've used it in this repo
- [`tsconfig.json`](https://github.com/unlike-ltd/cloudflare-pages-action/blob/20712cae04cac7d63534f7b5ae27c0552526450e/tsconfig.json)
- [`tsconfig.tsnode.json`](https://github.com/unlike-ltd/cloudflare-pages-action/blob/20712cae04cac7d63534f7b5ae27c0552526450e/tsconfig.tsnode.json)

I have [2 cli scripts](https://github.com/unlike-ltd/cloudflare-pages-action/blob/20712cae04cac7d63534f7b5ae27c0552526450e/package.json#L16-L17) that use it.
```json
    "tsc:ts-node-config": "tsc --showConfig > tsconfig.tsnode.json",
    "ts-node": "ts-node-esm --project tsconfig.tsnode.json",
```

Then for any other script I do
```json
    "dev": "pnpm run ts-node --require dotenv/config src/index.ts",
    "codegen": "pnpm run ts-node -T bin/codegen/index.ts",
    "download": "pnpm run ts-node -T bin/download/index.ts"
```

**Comment by guoyunhe** [comment]
Same here. It is breaking everything.

**Comment by gspetrou** [comment]
> As a definitive solution, you can migrate to [@swc/register](https://github.com/swc-project/register).
> 
> 
> 
> Also, It can be easily used by jest, mocha, etc...

In what way is this a solution? It looks like this just binds SWC to be used when importing files with `require`. This is unrelated to the owner of ts-node refusing to release bug fixes for no reason

**Comment by sebaplaza** [comment]
@gspetrou the solution is to migrate to another library (like @swc/register).

This is a critical issue, in a critical library (in ts ecosystem) and there is still no solution (the issue was created on April 24)

There is nothing we can do to fix this issue, other than wait for the maintainers.

**Comment by chenxxzhe** [comment]
In my project , change `tsconfig.json` `extends: ['...']` to `extends: '...'` can fix it.

**Comment by TheCleric** [comment]
> In my project , change `tsconfig.json` `extends: ['...']` to `extends: '...'` can fix it.

This worked for me as well. Thanks!

**Comment by Kurt-von-Laven** [comment]
@chenxxzhe, the reason for the thumbs down is that the whole point of this issue is that folks are hoping for support for `extends: ['...']`.

**Comment by binarykitchen** [comment]
@ahollenbach What's the reason why the maintainers haven't issued a new release for more than one year?

**Comment by Kurt-von-Laven** [comment]
I would consider porting to an alternative like SWC if you require TypeScript v5 support. Maintainers of open-source repositories don't owe their users answers to questions like this.

**Comment by gspetrou** [comment]
Or just fork it and publish it yourself since it's open source and contains changes other people than just the maintainers committed to benefit everyone

**Comment by JoseCabo-comscore** [comment]
> @ahollenbach What's the reason why the maintainers haven't issued a new release for more than one year?

There have been releases during the last year. What are you talking about? You don't need to increase the major version for no reason. This is a regresson introduced by TS 5.3.2, the very latest version. And ts-node v11 will contain the bugfix for it.

I think you need to calm down? You can always fork, fix and maintain ts-node. Or not use it at all.

Temporary workaround until ts-node 11: downgrade your typescript to 5.2.2.

**Comment by ahollenbach** [comment]
FYI - the beta version of ts-node 11 is published: https://www.npmjs.com/package/ts-node/v/11.0.0-beta.1 so installing via git is no longer necessary.

It can be installed using `npm install ts-node@11.0.0-beta.1` if using npm.

**Comment by therockstorm** [comment]
> With ts-node@11.0.0-beta.1 and TS >5 I'm still getting the same errors with extends. My only way to fix it is to downgrade to TS 4.9.

@Bloodsucker I was too, with Jest, until I added overrides:

```json
  "devDependencies": {
    "ts-node": "11.0.0-beta.1",
    "tsconfig-paths": "4.2.0",
    "typescript": "5.2.2"
  },
  "overrides": {
    "tsconfig-paths": "4.2.0",
    "ts-node": "11.0.0-beta.1"
  }
```

**Comment by jensbodal** [comment]
> > With ts-node@11.0.0-beta.1 and TS >5 I'm still getting the same errors with extends. My only way to fix it is to downgrade to TS 4.9.
> 
> @Bloodsucker I was too, with Jest, until I added overrides:
> 
> ```json
>   "devDependencies": {
>     "ts-node": "11.0.0-beta.1",
>     "tsconfig-paths": "4.2.0",
>     "typescript": "5.2.2"
>   },
>   "overrides": {
>     "ts-node": "11.0.0-beta.1",
>     "tsconfig-paths": "4.2.0"
>   }
> ```

Just an FYI so you don't need to duplicate the version, you can just do

```
  "devDependencies": {
    "ts-node": "11.0.0-beta.1",
    "tsconfig-paths": "4.2.0",
    "typescript": "5.2.2"
  },
  "overrides": {
    "ts-node": "$ts-node",
    "tsconfig-paths": "$tsconfig-paths"
  }
```

**Comment by adrian-gierakowski** [comment]
the 11.0.0-beta.1 release is affected by [this bug](https://github.com/TypeStrong/ts-node/issues/2076) when used with TypeScript 5.3.3

**Comment by muratgozel** [comment]
I switched to [swc](https://github.com/swc-project/swc-node) guys, its pretty simple:
```sh
node --loader @swc-node/register/esm src/index.ts
```

Besides, wanted to share, just saw `node` has a `--watch` flag now. so with one less dependency, my npm dev command is even more beautiful:
```sh
node -r dotenv/config --watch --watch-path src --loader @swc-node/register/esm src/index.ts
```

**Comment by adrian-gierakowski** [comment]
@muratgozel does `swc` type check the code before running it?

**Comment by muratgozel** [comment]
> @muratgozel does `swc` type check the code before running it?

no

**Comment by adrian-gierakowski** [comment]
> > @muratgozel does `swc` type check the code before running it?
> 
> no

Then it’s not a like for like replacement for ts-node.

**Comment by gspetrou** [comment]
@muratgozel here's something that does type check and has been updated to support language features released in the last year

https://www.npmjs.com/package/tsx

**Comment by adrian-gierakowski** [comment]
@gspetrou does it support composite TS projects with [project references](https://www.typescriptlang.org/docs/handbook/project-references.html)? Thanks!

**Comment by giseburt** [comment]
> @muratgozel here's something that does type check and has been updated to support language features released in the last year
> 
> https://www.npmjs.com/package/tsx

I don’t know why you’d say that. `tsx` does **not** type check. Says so right on the page linked to. 🤦‍♂️

**Comment by topkat** [comment]
[https://www.npmjs.com/package/tsx](url) was the best choices for me! I had a lot of pain with ts-node, and either `vite-node` which was better BTW

**Comment by JeffJacobson** [comment]
> [https://www.npmjs.com/package/tsx](url) was the best choices for me! I had a lot of pain with ts-node, and either `vite-node` which was better BTW

Thanks. This worked for me. They really need to fix this issue in this package, though.

**Comment by rockey2020** [comment]
> In my project , change `tsconfig.json` `extends: ['...']` to `extends: '...'` can fix it.
you save my code thank you

**Comment by adi-works** [comment]
> In my project , change `tsconfig.json` `extends: ['...']` to `extends: '...'` can fix it.

But the whole point is to be able to extend from multiple configs. That workaround is only good for those inheriting from just one config.

**Comment by gspetrou** [comment]
> ```shell
> But the whole point is to be able to extend from multiple configs. That workaround is only good for those inheriting from just one config.
> ```

Are you saying `swc-node` errors when the `extends` field of `tsconfig.json` is an array? I don't think that is true.


----


By the way, congrats on having this issue [fixed for over a year now in main](https://github.com/TypeStrong/ts-node/commit/ece352f79195ef47c38e24938989f4ca29ea334a) without releasing it in npm 👏🏼👏🏼👏🏼

**Comment by adi-works** [comment]
No, I misquoted, see edit.

**Comment by adamspotlite** [comment]
heyo, any update for the best way to handle this? using in an `expo` project in an `app.config.ts` - [docs](https://docs.expo.dev/guides/typescript/#appconfigjs) say to use this technique but getting this error :/

**Comment by ghost** [comment]
To anyone running into this issue on Expo from trying to import a TS file in `app.config.ts`: if you could afford an alternative, a solution that worked for me was to replace `ts-node` with [`@swc-node/register`](https://github.com/swc-project/swc-node/tree/master/packages/register) and register that instead at the top of my `app.config.ts`.

```typescript
// app.config.ts

import "@swc-node/register";  // <-- insert this line

import { SomeValue } from "./your-ts-module";

export default ({ config }: ConfigContext): ExpoConfig => ({
  ...
});
```

**Comment by david1542** [comment]
> In my project , change `tsconfig.json` `extends: ['...']` to `extends: '...'` can fix it.

OMG it worked

**Comment by mp3por** [comment]
WHY IS THIS NOT AVAILABLE THROUGH NPM ?

**Comment by topkat** [comment]
@mp3por  Please don't use ts-node, it's not maintained and actually there is much better solutions right now.
Too bad that there is not a message about that in the readme. It's really not correct to let so much peoples in troubles I really agree.
Actually I use bun, tsx is also a good alternative.

**Comment by mp3por** [comment]
@top-kat thank you - however nodemon uses ts-node. I don't know how to configure it otherwise. All I want is to auto compile and restart my TS app on file change

**Comment by jensbodal** [comment]
> @top-kat thank you - however nodemon uses ts-node. I don't know how to configure it otherwise. All I want is to auto compile and restart my TS app on file change

I use nodemon with bun and tsx all the time

```
nodemon -w file.ts -x "bun file.ts" 
```

For example. Of course can use `bun` or `tsx` directly for this exact use case, but there's times I want to use nodemon for the sake of monitoring other files to initiate the rebuild. 

If you're watching multiple typescript files or different types of files you have to use the `-e` flag (e.g. `-e ts,js,json`)

**Comment by huyunan** [comment]
ts-node is no longer maintained. tsx works better
"runtimeArgs": ["-r", "tsx"]

**Comment by andre-brdoch** [comment]
since node 22.18.0, TS is supported natively by node!
`node path-to-file.ts`

It is however not possible to configure it with a tsconfig.

https://nodejs.org/en/learn/typescript/run-natively

**Comment by loynoir** [comment]
I don't know if this issue still exist or not.

Close as now I don't use `ts-node`.
