### ISSUE TITLE
ts-node should take into account tsconfig paths in esm mode and keep but transpile imports

### ISSUE THREAD

**Issue by a-x-** [TypeStrong/ts-node#2023]
### Search Terms
node-ts and tsconfig paths
what I found:
- https://github.com/TypeStrong/ts-node/issues/1948
- https://stackoverflow.com/questions/72549407/how-to-use-tsconfig-paths-with-ts-node
- https://typestrong.org/ts-node/docs/imports

### Expected Behavior
Take tsconfig.json paths into account even in esm mode. Keep imports, but transpile paths.

### Actual Behavior
imports keeping as is in esm mode

### Steps to reproduce the problem
1. create tsconfig.json with at least `{ "compilerOptions": { "paths": { "foo": "src/bar.ts" } } }`
2. run `ts-node-esm --project tsconfig.json src/index.ts`
3. write src/index.ts like `import foo from 'foo'` and create some src/bar.ts file with default export

### Minimal reproduction

will be later

### Specifications

- ts-node v10.9.1
- node v16.16.0
- compiler v5.0.4

I have complex monorepo setup with 3 tsconfigs and many other things, I'll show later minimal repo if it really needed in this case...

* Operating system and version: macOS

**Comment by a-x-** [comment]
<details><summary>my error: ERR_INVALID_MODULE_SPECIFIER</summary>

```
cd server && yarn run start
$ NODE_OPTIONS='--loader=ts-node/esm --experimental-specifier-resolution=node' ts-node -r tsconfig-paths/register --project tsconfig.json ./index.ts
(node:88652) ExperimentalWarning: --experimental-loader is an experimental feature. This feature could change at any time
(Use `node --trace-warnings ...` to show where the warning was created)
(node:88652) ExperimentalWarning: The Node.js specifier resolution flag is experimental. It could change or be removed at any time.
(node:88671) ExperimentalWarning: The Node.js specifier resolution flag is experimental. It could change or be removed at any time.
(Use `node --trace-warnings ...` to show where the warning was created)
/Users/wzhalmq/raif/ips-cortex-collateral-ui-application/node_modules/ts-node/dist-raw/node-internal-modules-esm-resolve.js:695
    throw new ERR_INVALID_MODULE_SPECIFIER(
          ^
cd server && yarn run start
$ NODE_OPTIONS='--loader=ts-node/esm --experimental-specifier-resolution=node' ts-node -r tsconfig-paths/register --project tsconfig.json ./index.ts
(node:88652) ExperimentalWarning: --experimental-loader is an experimental feature. This feature could change at any time
(Use `node --trace-warnings ...` to show where the warning was created)
(node:88652) ExperimentalWarning: The Node.js specifier resolution flag is experimental. It could change or be removed at any time.
(node:88671) ExperimentalWarning: The Node.js specifier resolution flag is experimental. It could change or be removed at any time.
(Use `node --trace-warnings ...` to show where the warning was created)
/Users/wzhalmq/raif/ips-cortex-collateral-ui-application/node_modules/ts-node/dist-raw/node-internal-modules-esm-resolve.js:695
    throw new ERR_INVALID_MODULE_SPECIFIER(
          ^
CustomError: ERR_INVALID_MODULE_SPECIFIER @date-fns is not a valid package name /Users/wzhalmq/raif/ips-cortex-collateral-ui-application/shared/utils/date.ts
```

</details>

**Comment by a-x-** [comment]
Can I implement it myself?
Could you help me is a little advice?
Where, and how to fix it in the TS node source code?

**Comment by a-x-** [comment]
I found answer, but it is not help me to solve a problem and I disagree with this decision:

https://github.com/TypeStrong/ts-node#why-is-this-not-built-in-to-ts-node

### Why is this not built-in to ts-node?

The official TypeScript Handbook explains the intended purpose for "paths" in "Additional module resolution flags".

The TypeScript compiler has a set of additional flags to inform the compiler of transformations that are expected to happen to the sources to generate the final output.

It is important to note that the compiler will not perform any of these transformations; it just uses these pieces of information to guide the process of resolving a module import to its definition file.
This means "paths" are intended to describe mappings that the build tool or runtime already performs, not to tell the build tool or runtime how to resolve modules. In other words, they intend us to write our imports in a way node already understands. For this reason, ts-node does not modify node's module resolution behavior to implement "paths" mappings.

**Comment by a-x-** [comment]
I dig into ts-node and tsconfig-paths and realised:
function register(params) {} in tsconfig-paths had not even called before error:
`CustomError: ERR_INVALID_MODULE_SPECIFIER @date-fns is not a valid package name`

there is on good thing, registering is works:
tsconfig-paths/register.js
typescript-transform-paths/register.js

also, I tried remove typescript-transform-paths or swap requirement order

**Comment by aaggarwal-sumo** [comment]
@a-x- I am facing similar issue when I am using paths in tsconfig.json with V8 WDIO.

```
{
  "ts-node": {
    // Do not forget to `npm i -D tsconfig-paths`
    "require": ["tsconfig-paths/register"]
  },
  "compilerOptions": {
    "allowJs": true,
    "allowSyntheticDefaultImports": true,
    "baseUrl": ".",
    "esModuleInterop": true,
    "moduleResolution": "node",
    "outDir": "dist",
    "paths": {
      "@Constants/*": [
        "test/constants/*"
      ],
      "@DialogBoxes/*": [
        "test/pageobjects/dialogboxes/*"
      ],
      "@EncryptedData/*": [
        "test/encryptedData/*"
      ],
      "@Locators/*": [
        "test/locators/*"
      ],
      "@Component/*": [
        "test/pageobjects/components/*"
      ],
      "@PageObject/*": [
        "test/pageobjects/*"
      ],
      "@Reporter/*": [
        "customReporters/*"
      ],
      "@TestData/*": [
        "test/testdata/*"
      ],
      "@Util/*": [
        "test/util/*"
      ]
    },
    "resolveJsonModule": true,
    "target": "es2022",
    "module": "esnext",
    "types": [
      "node",
      "@wdio/globals/types",
      "webdriverio/async",
      "@wdio/jasmine-framework",
      "expect-webdriverio"
    ],
    // "strict": true,
  },
  "exclude": [
    "node_modules"
  ],
  "include": [
    "customReporters/",
    "test/",
    "wdio.conf.ts"
  ]
}
```

Getting Error: 

`[2023-08-08T12:15:07.941Z] 2023-08-08T12:15:07.941Z ERROR @wdio/runner: Error: Cannot find package '@Util/GetCustomerLoginData' imported from /Users/aaggarwal/Documents/Sumo-Repo/sumo-ui-test/UIE2ETests/test/util/LoginUtil.ts
[0-0]     at packageResolve (/Users/aaggarwal/Documents/Sumo-Repo/sumo-ui-test/UIE2ETests/node_modules/ts-node/dist-raw/node-internal-modules-esm-resolve.js:757:9)
[0-0]     at moduleResolve (/Users/aaggarwal/Documents/Sumo-Repo/sumo-ui-test/UIE2ETests/node_modules/ts-node/dist-raw/node-internal-modules-esm-resolve.js:798:18)
[0-0]     at Object.defaultResolve (/Users/aaggarwal/Documents/Sumo-Repo/sumo-ui-test/UIE2ETests/node_modules/ts-node/dist-raw/node-internal-modules-esm-resolve.js:912:11)
[0-0]     at /Users/aaggarwal/Documents/Sumo-Repo/sumo-ui-test/UIE2ETests/node_modules/ts-node/src/esm.ts:218:35
[0-0]     at entrypointFallback (/Users/aaggarwal/Documents/Sumo-Repo/sumo-ui-test/UIE2ETests/node_modules/ts-node/src/esm.ts:168:34)
[0-0]     at /Users/aaggarwal/Documents/Sumo-Repo/sumo-ui-test/UIE2ETests/node_modules/ts-node/src/esm.ts:217:14
[0-0]     at addShortCircuitFlag (/Users/aaggarwal/Documents/Sumo-Repo/sumo-ui-test/UIE2ETests/node_modules/ts-node/src/esm.ts:409:21)
[0-0]     at resolve (/Users/aaggarwal/Documents/Sumo-Repo/sumo-ui-test/UIE2ETests/node_modules/ts-node/src/esm.ts:197:12)
[0-0]     at nextResolve (node:internal/modules/esm/hooks:733:28)
[0-0]     at Hooks.resolve (node:internal/modules/esm/hooks:242:30)
[2023-08-08T12:15:07.941Z] [0-0]  Error:  Cannot find package '@Util/GetCustomerLoginData' imported from /Users/aaggarwal/Documents/Sumo-Repo/sumo-ui-test/UIE2ETests/test/util/LoginUtil.ts`

How did you resolve it?

**Comment by mettini** [comment]
This has done the trick for me: https://github.com/TypeStrong/ts-node/discussions/1450#discussioncomment-1806115

**Comment by immotus** [comment]
This helped me and appears to be the recommended solution:
https://typestrong.org/ts-node/docs/paths/
