### ISSUE TITLE
Use ts-node command to compile .ts file is unsuccessful ,throwing an error as is below 

### ISSUE THREAD

**Issue by birdflesh** [TypeStrong/ts-node#2066]
### Search Terms
ts-node
E:XXXXX\nodejs\node_modules\typescript\lib\typescript.js:139
    for (let i = startIndex ?? 0; i < array.length; i++) {
                             ^

SyntaxError: Unexpected token ?
    at new Script (vm.js:79:7)
    at createScript (vm.js:251:10)
    at Object.runInThisContext (vm.js:303:10)
    at Module._compile (internal/modules/cjs/loader.js:656:28)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:699:10)
    at Module.load (internal/modules/cjs/loader.js:598:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:537:12)
    at Function.Module._load (internal/modules/cjs/loader.js:529:3)
    at Module.require (internal/modules/cjs/loader.js:636:17)
    at require (internal/modules/cjs/helpers.js:20:18)

### Specifications

* ts-node version:
* node version:
* TypeScript version:
* tsconfig.json, if you're using one:
```
{}
```
* package.json:
```
{}
```
* Operating system and version:
* If Windows, are you using WSL or WSL2?:

**Comment by MateuszKikmunter** [comment]
I'm having exactly the same issue as above, node 18.18.0 with ts-node: ^10.9.1 and typescript: ^5.3.2.

**Comment by Erhannis** [comment]
I was getting that error when I ran `ts-node`, but I upgraded my nodejs (via https://github.com/nodesource/distributions ) and the problem seems to have gone away.  I'm on Ubuntu 20.04.6.  My new versions are:
nodejs: v20.11.0
npm: 10.2.4
ts-node: v10.9.2

**Comment by KostrebaDV** [comment]
I have the same error
```
/api/node_modules/typescript/lib/typescript.js:139
    for (let i = startIndex ?? 0; i < array.length; i++) {
```
Node.js v18.17.1
"typescript": "^5.3.3"
"ts-node": "^10.9.2"
macOs Ventura 13.6

**Comment by wirwolf** [comment]
I have the same problem
Node.js v22.14.0
"ts-node": "^10.9.2",
"typescript": "^5.7.3"
