### ISSUE TITLE
[DEP0180] DeprecationWarning: fs.Stats constructor is deprecated when using node 22

### ISSUE THREAD

**Issue by darcyrush** [TypeStrong/ts-node#2116]
### Search Terms

DeprecationWarning: fs.Stats 

### Steps to reproduce the problem

Warning only appears in node 22, node 21 is fine.

```
(node:4075381) [DEP0180] DeprecationWarning: fs.Stats constructor is deprecated.
    at Object.createResolve (/.../node_modules/ts-node/dist-raw/node-internal-modules-esm-resolve.js:146:25)
    at /.../node_modules/ts-node/src/index.ts:1494:7
    at Object.onceFn [as getNodeEsmResolver] (/.../node_modules/ts-node/src/util.ts:166:13)
    at createEsmHooks (/.../node_modules/ts-node/src/esm.ts:125:51)
    at Object.registerAndCreateEsmHooks (/.../node_modules/ts-node/src/esm.ts:118:10)
    at file:///.../node_modules/ts-node/esm.mjs:8:7
    at ModuleJob.run (node:internal/modules/esm/module_job:235:25)
    at async ModuleLoader.import (node:internal/modules/esm/loader:461:24)
    at async Hooks.register (node:internal/modules/esm/hooks:150:26)
    at async MessagePort.handleMessage (node:internal/modules/esm/worker:199:18)
```
The line of code in question;
```
const statsIfNotFound = new Stats();
```

### Minimal reproduction
```
node --trace-deprecation --import ./ts-node.register.mjs path/to/any/file.ts
```
With `ts-node.register.mjs` containing the lines of code suggested [here](https://github.com/TypeStrong/ts-node/issues/2100#issuecomment-2039564225).

### Specifications
* ts-node version: 10.9.1
* node version: v22.0.0
* TypeScript version: 5.4.5
* Operating system and version: Ubuntu 22.04 LTS, 5.15.0-105-generic x86_64

**Comment by Byron2016** [comment]
maybe some update on this warning?

**Comment by RomainLanz** [comment]
We made [ts-node-maintained](https://github.com/thetutlage/ts-node-maintained) in the meanwhile

**Comment by druewilding** [comment]
thank you @RomainLanz for `ts-node-maintained` 🥰 

are there any plans to update `ts-node` again at some point?

**Comment by tianyingchun** [comment]
it seems that `ts-node` have no activity over 1 year. maybe we need to switch it to `swc`

i have create new repo and replace `ts-node` with `swc` see here. https://github.com/hyperse-io/ts-node

**Comment by vasilvestre** [comment]
I have this log now when I launch gitkraken and the UI is not shown. Maybe it's not related but I can't have more logs.

**Comment by oldium** [comment]
> I have this log now when I launch gitkraken and the UI is not shown. Maybe it's not related but I can't have more logs.

And you decided to report it to a completely random project on the internet, right? 🤔 If you have issue with Gitkraken, I would say the best you could do is to report it to Gitkraken project. 😉

**Comment by vasilvestre** [comment]
> > I have this log now when I launch gitkraken and the UI is not shown. Maybe it's not related but I can't have more logs.
> 
> And you decided to report it to a completely random project on the internet, right? 🤔 If you have issue with Gitkraken, I would say the best you could do is to report it to Gitkraken project. 😉

oopsie, I was tired 😓 My bad !

**Comment by tianyingchun** [comment]
Maybe you can try @hyperse/ts- node.
