### ISSUE TITLE
error ts-node@0.4.1 postinstall: `typings install`

### ISSUE THREAD

**Issue by arolson101** [TypeStrong/ts-node#22]
It looks like we have to install typings now, so I did ("npm install -g typings"), but when I try to install ts-node I get the following:

```
2813 verbose stack Error: ts-node@0.4.1 postinstall: `typings install`
2813 verbose stack Exit status 1
2813 verbose stack     at EventEmitter.<anonymous> (C:\Program Files (x86)\nodejs\node_modules\npm\lib\utils\lifecycle.js:214:16)
2813 verbose stack     at emitTwo (events.js:87:13)
2813 verbose stack     at EventEmitter.emit (events.js:172:7)
2813 verbose stack     at ChildProcess.<anonymous> (C:\Program Files (x86)\nodejs\node_modules\npm\lib\utils\spawn.js:24:14)
2813 verbose stack     at emitTwo (events.js:87:13)
2813 verbose stack     at ChildProcess.emit (events.js:172:7)
2813 verbose stack     at maybeClose (internal/child_process.js:818:16)
2813 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:211:5)
2814 verbose pkgid ts-node@0.4.1
2815 verbose cwd C:\updraft
2816 error Windows_NT 6.1.7601
2817 error argv "C:\\Program Files (x86)\\nodejs\\node.exe" "C:\\Program Files (x86)\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "install" "--save-dev" "ts-node"
2818 error node v4.1.2
2819 error npm  v2.14.4
2820 error code ELIFECYCLE
2821 error ts-node@0.4.1 postinstall: `typings install`
2821 error Exit status 1
2822 error Failed at the ts-node@0.4.1 postinstall script 'typings install'.
2822 error This is most likely a problem with the ts-node package,
2822 error not with npm itself.
2822 error Tell the author that this fails on your system:
2822 error     typings install
2822 error You can get their info via:
2822 error     npm owner ls ts-node
2822 error There is likely additional logging output above.
2823 verbose exit [ 1, true ]
2824 verbose unbuild node_modules\ts-node
2825 info preuninstall ts-node@0.4.1
2826 info uninstall ts-node@0.4.1
2827 verbose unbuild rmStuff ts-node@0.4.1 from C:\updraft\node_modules
2828 silly gentlyRm C:\updraft\node_modules\.bin\ts-node.cmd is being gently removed
2829 silly gentlyRm verifying C:\updraft is an npm working directory
2830 silly gentlyRm containing path C:\updraft is under npm's control, in C:\updraft
2831 silly gentlyRm deletion target C:\updraft\node_modules\.bin\ts-node.cmd is under C:\updraft
2832 verbose gentlyRm vacuuming from C:\updraft\node_modules\.bin\ts-node.cmd up to C:\updraft
2833 silly vacuum-fs removing C:\updraft\node_modules\.bin\ts-node.cmd
2834 silly vacuum-fs quitting because other entries in C:\updraft\node_modules\.bin
2835 silly gentlyRm C:\updraft\node_modules\.bin\ts-node is being gently removed
2836 silly gentlyRm verifying C:\updraft is an npm working directory
2837 silly gentlyRm containing path C:\updraft is under npm's control, in C:\updraft
2838 silly gentlyRm deletion target C:\updraft\node_modules\.bin\ts-node is under C:\updraft
2839 verbose gentlyRm vacuuming from C:\updraft\node_modules\.bin\ts-node up to C:\updraft
2840 silly vacuum-fs removing C:\updraft\node_modules\.bin\ts-node
2841 silly vacuum-fs quitting because other entries in C:\updraft\node_modules\.bin
2842 info postuninstall ts-node@0.4.1
2843 silly gentlyRm C:\updraft\node_modules\ts-node is being purged from base C:\updraft
2844 verbose gentlyRm don't care about contents; nuking C:\updraft\node_modules\ts-node
2845 silly vacuum-fs purging C:\updraft\node_modules\ts-node
2846 silly vacuum-fs quitting because other entries in C:\updraft\node_modules
```

**Comment by blakeembrey** [comment]
Sorry! :frowning: I'll look into it, this is a pain in the ass because NPM runs `prepublish` on installation too, which breaks CI without `postinstall`. I'll move this to "preprepublish".

**Comment by blakeembrey** [comment]
Should be working with `v0.4.2` on NPM :+1:
