### ISSUE TITLE
TypeError: Cannot read property 'parent' of undefined

### ISSUE THREAD

**Issue by zubuzon** [TypeStrong/ts-node#224]
I reported it on the TypeScript repo as well. Seen here: https://github.com/Microsoft/TypeScript/issues/11703

Various different setup configuration and still same issue.

```js
  at getOutput (node_modules\ts-node\src\index.ts:299:32)
    at node_modules\ts-node\src\index.ts:340:18
    at Object.compile (node_modules\ts-node\src\index.ts:473:19)
    at Module.m._compile (node_modules\ts-node\src\index.ts:403:44)
    at Module._extensions..js (module.js:579:10)
    at Object.require.extensions.(anonymous function) [as .ts] (node_modules\ts-node\src\index.ts:406:12)
    at Module.load (module.js:487:32)
```

**Comment by blakeembrey** [comment]
Can you place share your configuration? Are you using `allowJs` in `tsconfig.json`? What version of `ts-node` and `node` are you running? Anything else I could use to reproduce?

**Comment by zubuzon** [comment]
@blakeembrey Click on the link above to the issue reported on the TypeScript repo. Latest post there you see my configuration.

Regarding your questions. Here is my tsconfig.js

```js
{
    "compilerOptions": {
        "allowJs": false,
        "allowUnreachableCode": false,
        "forceConsistentCasingInFileNames": true,
        "declaration": false,
        "experimentalDecorators": true,
        "moduleResolution": "node",
        "target": "es6",
        "lib": ["es7"],
        "noEmitHelpers": true,
        "newLine": "LF",
        "noImplicitAny": true,
        "project": "src",
        "noLib": false,
        "removeComments": false,
        "pretty": true,
        "strictNullChecks": true,
        "stripInternal": true,
        "sourceMap": false,
        "inlineSourceMap": false,
        "suppressImplicitAnyIndexErrors": false,
        "outDir": "lib/",
        "types": ["mocha", "chai", "node"]
}}
```

**Comment by zubuzon** [comment]
I also tried running this on NodeJS v. 4 - 6. All versions. Same thing

**Comment by blakeembrey** [comment]
@zubuzon Are you sure that you haven't got `allowJs` enabled? From the stack trace it looks like you're falling through from TypeScript -> JavaScript so that's either from a file in `node_modules` or `allowJs`. However, if it's from `node_modules` that isn't in line with the title - can you share the full stack-trace you're seeing?

**Comment by blakeembrey** [comment]
Perhaps I can enable a `--debug-require` flag so we can at least figure out when it's crashing?

**Comment by zubuzon** [comment]
@blakeembrey Different stack trace now. Here is the complete one:

```js
TypeError: Cannot read property 'parent' of undefined
    at visitNode (node_modules\typescript\lib\typescript.js:13558:22)
    at visitEachNode (node_modules\typescript\lib\typescript.js:12943:30)
    at forEachChild (node_modules\typescript\lib\typescript.js:13315:24)
    at visitNode (node_modules\typescript\lib\typescript.js:13562:21)
    at visitNode (node_modules\typescript\lib\typescript.js:12931:20)
    at forEachChild (node_modules\typescript\lib\typescript.js:13313:21)
    at visitNode (node_modules\typescript\lib\typescript.js:13562:21)
    at visitEachNode (node_modules\typescript\lib\typescript.js:12943:30)
    at forEachChild (node_modules\typescript\lib\typescript.js:13299:24)
    at visitNode (node_modules\typescript\lib\typescript.js:13568:29)
    at visitEachNode (node_modules\typescript\lib\typescript.js:12943:30)
    at forEachChild (node_modules\typescript\lib\typescript.js:13103:24)
    at fixupParentReferences (node_modules\typescript\lib\typescript.js:13552:13)
    at parseSourceFileWorker (node_modules\typescript\lib\typescript.js:13525:17)
    at Object.parseSourceFile (node_modules\typescript\lib\typescript.js:13470:26)
    at Object.createSourceFile (node_modules\typescript\lib\typescript.js:13329:29)
    at createLanguageServiceSourceFile (node_modules\typescript\lib\typescript.js:74491:29)
    at Object.updateLanguageServiceSourceFile (node_modules\typescript\lib\typescript.js:74544:16)
    at acquireOrUpdateDocument (node_modules\typescript\lib\typescript.js:65898:43)
    at Object.updateDocumentWithKey (node_modules\typescript\lib\typescript.js:65877:20)
    at getOrCreateSourceFileByPath (node_modules\typescript\lib\typescript.js:74740:49)
    at Object.getOrCreateSourceFile [as getSourceFile] (node_modules\typescript\lib\typescript.js:74697:24)
    at findSourceFile (node_modules\typescript\lib\typescript.js:59696:29)
    at processImportedModules (node_modules\typescript\lib\typescript.js:59829:25)
    at findSourceFile (node_modules\typescript\lib\typescript.js:59724:17)
    at processImportedModules (node_modules\typescript\lib\typescript.js:59829:25)
    at findSourceFile (node_modules\typescript\lib\typescript.js:59724:17)
    at processSourceFile (node_modules\typescript\lib\typescript.js:59627:27)
    at processRootFile (node_modules\typescript\lib\typescript.js:59521:13)
    at node_modules\typescript\lib\typescript.js:58982:60
    at Object.forEach (node_modules\typescript\lib\typescript.js:1238:30)
    at Object.createProgram (node_modules\typescript\lib\typescript.js:58982:16)
    at synchronizeHostData (node_modules\typescript\lib\typescript.js:74675:33)
    at Object.getEmitOutput (node_modules\typescript\lib\typescript.js:74948:13)
    at getOutput (node_modules\ts-node\src\index.ts:299:32)
    at node_modules\ts-node\src\index.ts:340:18
    at Object.compile (node_modules\ts-node\src\index.ts:473:19)
    at Module.m._compile (node_modules\ts-node\src\index.ts:403:44)
    at Module._extensions..js (module.js:579:10)
    at Object.require.extensions.(anonymous function) [as .ts] (node_modules\ts-node\src\index.ts:406:12)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
    at Module.require (module.js:497:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (src\utils\xxx.ts:2:1)
    at Module._compile (module.js:570:32)
    at Module.m._compile (node_modules\ts-node\src\index.ts:403:23)
    at Module._extensions..js (module.js:579:10)
    at Object.require.extensions.(anonymous function) [as .ts] (node_modules\ts-node\src\index.ts:406:12)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
    at Module.require (module.js:497:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (test\specs\xxx.ts:1:1)
    at Module._compile (module.js:570:32)
    at Module.m._compile (node_modules\ts-node\src\index.ts:403:23)
    at Module._extensions..js (module.js:579:10)
    at Object.require.extensions.(anonymous function) [as .ts] (node_modules\ts-node\src\index.ts:406:12)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
    at Module.require (module.js:497:17)
    at require (internal/module.js:20:19)
    at node_modules\mocha\lib\mocha.js:222:27
    at Array.forEach (native)
    at Mocha.loadFiles (node_modules\mocha\lib\mocha.js:219:14)
    at Mocha.run (node_modules\mocha\lib\mocha.js:487:10)
    at loadAndRun (node_modules\mocha\bin\_mocha:415:22)
    at Object.<anonymous> (node_modules\mocha\bin\_mocha:432:3)
    at Module._compile (module.js:570:32)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
    at Module.runMain (module.js:604:10)
    at run (bootstrap_node.js:394:7)
    at startup (bootstrap_node.js:149:9)
    at bootstrap_node.js:509:3
```

**Comment by blakeembrey** [comment]
Have you tried running any of this without `ts-node`? Does `tsc` succeed?

I just pushed up a branch, https://github.com/TypeStrong/ts-node/tree/debug-log, if you want to test that locally and see where it's failing it may help. No guarantees though, but at least it'll give a sense of how many requires are happening and which one it fails on.

**Comment by blakeembrey** [comment]
Can you also share your `mocha.opts`? Is there anything else you can share that might help me debug? Looking over the stack-trace again, it looks like `ts-node` never even starts - have you checked with `tsc`? How many files are we looking at in the project? Do you have `node_modules` linked within the project somewhere? Is there any symlinks I should know about?

**Comment by zubuzon** [comment]
@blakeembrey Sorry late reply. If I downgrade TS version to 2.0.3 everything works as expected. And if I still are using latest TS nigthly build everything works as expected. If that helps.
The issue occur only when I run tests with latest TS v. *next*.

My mocha.opts is this:

```js
--require ts-node/register
--ui bdd
--reporter spec
--bail
--full-trace
--check-leaks
--watch-extensions tsx,ts
--colors
--recursive
--timeout 5000
```

**Comment by zubuzon** [comment]
I ran the ts-node you linked too. All tests pass there except one for the CLI:

` 1) should pipe into `ts-node` and evaluate`

But couldn't find a way to activate the logging

**Comment by blakeembrey** [comment]
Ignore the tests. The logging was in the README, use `TS_NODE_LOG_DEBUG=true` as an environment variable. I'll try to replicate it soon, but it's definitely a lot easier when it's something like this to narrow down the issue and replicate it. If it's only one test, it should be easy enough to create a stand-alone repo that someone could checkout and debug. It certainly makes like for us maintainers 100x easier than going back on forth on project details 😄

**Comment by blakeembrey** [comment]
Did you try running `tsc` on it yet by the way? Maybe you've found an issue with the TypeScript compiler? Hard to tell without seeing the file that's erroring. If it helps, you can always get in touch by email as well.

**Comment by zubuzon** [comment]
@blakeembrey if we could communicate outside GH it could make it easier. I can then grant access to the project itself (*not for GH*) so you could use that to debug with.

The TypeScript compiler isn't the issue here. The project compiles just fine.

**Comment by zubuzon** [comment]
@blakeembrey Okay. Follow this step-by-step

1. Create a file named `defineProperty.ts`, and paste in this code:

```js
function defineProperty(obj: any, prop: any, val: any): any {

    return Object.defineProperty(obj, prop, {
        configurable: true,
        enumerable: false,
        writable: true,
        value: val
    });
}
export default defineProperty;
```

2. Create a new file that you namme `dummy.ts`, and paste in this code:

```js
import defineProperty from './defineProperty';

let cache: any = {};

function cacheRegex(regex: any, key: string, pattern: string, options: any): void {
    defineProperty(regex, 'hello', key);
    cache[key] = regex;
}

export function dummy (pattern: any, options: any): any {

}

export default dummy;
```

3. Create a test file and use this test code:

```js
import foo from '../../src/utils/createRegex';

const expect = chai.expect;

describe('foo', function() {

 it('should export a function', function() {
     expect(typeof foo).to.eql('function');
 });

});
```

Run the test, and you will see what I see :)

*Note!* TS latest nightly build is the TS version you need to use. If you use TS 2.0.3 it works without errors.

**Comment by zubuzon** [comment]
@blakeembrey I know what's causing this, and I didn't expect THAT 👎 

This will fail:

```js
/**
 * Define property
 *
 * @typedef {Object} defineProperty
 * @property {[any]} [obj]
 * @property {[string]} [prop]
 * @property {[val]} [val]
 */
function defineProperty(obj: any, prop: string, val: any): any {

    return Object.defineProperty(obj, prop, {
        configurable: true,
        enumerable: false,
        writable: true,
        value: val
    });
}
export default defineProperty;
```
THIS is not failing
```js
/**
 * Define property
 */
function defineProperty(obj: any, prop: string, val: any): any {

    return Object.defineProperty(obj, prop, {
        configurable: true,
        enumerable: false,
        writable: true,
        value: val
    });
}
export default defineProperty;
```

Do you see it? Look at the differences between the comments!! Yep. That cause the whole thing to explode

**Comment by zubuzon** [comment]
@blakeembrey I video recorded this. Should I send it on an email?

**Comment by blakeembrey** [comment]
Thanks for the debugging. I'll try running it now and seeing what happens. I'll get back to you, but you're always free to email me (the email is on my GitHub profile).

**Comment by zubuzon** [comment]
@blakeembrey Check you email. I sent the video there. To be honest I have never experienced this things before!

**Comment by blakeembrey** [comment]
I just tried replicating it according to the comments, but it still isn't failing. I'm using:

```
→ ts-node --version
ts-node v1.6.0
node v6.8.0
→ tsc --version
Version 2.1.0-dev.20161022
```

Are those the same versions you can reproduce on?

![image](https://cloud.githubusercontent.com/assets/1088987/19623072/56e8147a-9870-11e6-9edc-23f3792b606d.png)

I can create a test repo and add you to it if that'll help you create a reproduction?

**Comment by zubuzon** [comment]
Yes. It's the same. Did you see the video in the email I sent you ?

**Comment by blakeembrey** [comment]
Actually, I got it working once I replicated the rest of the project in the TypeScript issue. Narrowing it down now.

**Comment by zubuzon** [comment]
So you see the bug?

**Comment by blakeembrey** [comment]
That is literally insane. I'll create a repro repo that @mhegazy can review.

**Comment by blakeembrey** [comment]
Here's the repro I was using to verify - https://github.com/blakeembrey/ts-and-ts-node-compile-bug-224. If you `npm install` and then run `npm test`, it should repro.

**Comment by zubuzon** [comment]
I looked at it, but with all this comments in the code I'm sure it will break!

**Comment by isiahmeadows** [comment]
Much smaller repro [explained here](https://github.com/Microsoft/TypeScript/issues/11703#issuecomment-255563467).

**Comment by zubuzon** [comment]
@blakeembrey I'm closing this. The issue have been fixed by the TypeScript team.
