### ISSUE TITLE
Error "declarationDir" cannot be specified without "declaration" - when "declarationDir" is set within extended config

### ISSUE THREAD

**Issue by danthegoodman** [TypeStrong/ts-node#320]
I have a project that has the following configurations:

tsconfig.json:
```
{ extends: "./node_modules/@our-company/build-toolchain/tsconfig.json" }
```

@our-company/build-toolchain/tsconfig.json:
```
{
  "compileOnSave": true,
  "compilerOptions": {
    "strict": true,
    "forceConsistentCasingInFileNames": true,
    "declaration": true,
    "lib": [ "es6" ],
    "moduleResolution": "node",
    "module": "commonjs",
    "noEmitOnError": true,
    "noFallthroughCasesInSwitch": true,
    "noImplicitReturns": true,
    "preserveConstEnums": true,
    "target": "es5",
    "pretty": true,
    "sourceMap": true,
    "rootDir": "../../../lib",
    "outDir": "../../../dist",
    "declarationDir": "../../../dist"
  },
  "include": [
    "../../../lib/**/*"
  ]
}
```

These configurations result in the following error:
```
Option 'declarationDir' cannot be specified without specifying option 'declaration'. (5052)
    at getOutput (/.../node_modules/ts-node/src/index.ts:312:15)
    at /.../node_modules/ts-node/src/index.ts:343:16
    at Object.compile (/.../node_modules/ts-node/src/index.ts:487:17)
    at Module.m._compile (/.../node_modules/ts-node/src/index.ts:395:43)
    at Module._extensions..js (module.js:579:10)
    at Object.require.extensions.(anonymous function) [as .ts] (/.../ts-node/src/index.ts:398:12)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
    at Function.Module.runMain (module.js:604:10)
```

After digging around in the code, it appears that the `declaration` property is getting overridden to false, but the declarationDir property is just getting deleted from the config (which ends up not impacting the extended configuration. [Relevant Lines: index.ts:419](https://github.com/TypeStrong/ts-node/blob/54128f26bd6d99770a6c2d0fb9f0848d7bf8ae2b/src/index.ts#L419-L421)

**Comment by blakeembrey** [comment]
I'm not sure what the best fix is, probably need to refactor it to support extends better. I think there's a related issue for this. Welcome to a PR.
