### ISSUE TITLE
ts-node 3.0.5 attempts to compile package.json

### ISSUE THREAD

**Issue by sjbarag** [TypeStrong/ts-node#346]
Just updated to `ts-node@3.0.5` and received a compilation error for every place my compiled TypeScript files use a `require` statement.  While this seems to happen for any external dependency, compiling with `importHelpers: true` causes `require("tslib")` to appear in compiled JavaScript, thus reproducing the error just as well.

Minimum working example provided below, but I can't find a workaround other than downgrading to 3.0.4.  Any idea what's going on?

## Code Snippets

```javascript
// index.js

require("ts-node/register");
const { B } = require("./tsFile");
new B();
```

```typescript
// tsFile.ts

class A {
    constructor() {
        console.log("A");
    }
}

// extend A to force use of `tslib`
class B extends A {
    constructor() {
        super();
        console.log("B");
    }
}

export { B };
```

```javascript
// tsconfig.json

{
    "compilerOptions": {
        "importHelpers": true
    }
}
```

## Expected Behavior
Running `node index.js` should result in 

```
$ node index.js
A
B
```

## Observed Behavior
```
$ node index.js

/Users/sean.barag/src/public/ts-node-broken/node_modules/ts-node/src/index.ts:300
        throw new TSError(formatDiagnostics(diagnosticList, cwd, ts, lineOffset))
              ^
TSError: ⨯ Unable to compile TypeScript
File '/Users/sean.barag/src/public/ts-node-broken/node_modules/tslib/package.json' has unsupported extension. The only supported extensions are '.ts', '.tsx', '.d.ts'. (6054)
    at getOutput (/Users/sean.barag/src/public/ts-node-broken/node_modules/ts-node/src/index.ts:300:15)
    at /Users/sean.barag/src/public/ts-node-broken/node_modules/ts-node/src/index.ts:330:16
    at Object.compile (/Users/sean.barag/src/public/ts-node-broken/node_modules/ts-node/src/index.ts:489:17)
    at Module.m._compile (/Users/sean.barag/src/public/ts-node-broken/node_modules/ts-node/src/index.ts:382:43)
    at Module._extensions..js (module.js:579:10)
    at Object.require.extensions.(anonymous function) [as .ts] (/Users/sean.barag/src/public/ts-node-broken/node_modules/ts-node/src/index.ts:385:12)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
    at Module.require (module.js:497:17)
```

## Environment
Mac OS X Sierra
```
$ npm version
{ 'ts-node-broken': '1.0.0',
  npm: '3.10.10',
  ares: '1.10.1-DEV',
  http_parser: '2.7.0',
  icu: '58.2',
  modules: '48',
  node: '6.10.3',
  openssl: '1.0.2k',
  uv: '1.9.1',
  v8: '5.1.281.101',
  zlib: '1.2.11' }
```

**Comment by sjbarag** [comment]
Seems like `ts-node` now tries to compile `package.json` and -- in some other cases -- the file indicated by the `main` property in package.json.

**Comment by hutchwhite** [comment]
Yep, causing breaking builds for me.

**Comment by blakeembrey** [comment]
Please look at existing issues before opening a new one: https://github.com/TypeStrong/ts-node/issues/344.
