### ISSUE TITLE
does not ignore /node_modules/

### ISSUE THREAD

**Issue by tomdavidson** [TypeStrong/ts-node#348]
ts-node v3.0.3 - v3.0.6
node v6.9.1 and v8.0.0

```sh
$ node_modules/.bin/ts-node --ignore '/node_modules/' src/cli.ts 
and 
$ node_modules/.bin/ts-node src/cli.ts 
```
Errors on js and json files in node_modules:

```sh
/home/tom/Projects/tomdavidson/s6/node_modules/ts-node/src/index.ts:300
        throw new TSError(formatDiagnostics(diagnosticList, cwd, ts, lineOffset))
              ^
TSError: ⨯ Unable to compile TypeScript
File '/home/tom/Projects/tomdavidson/s6/node_modules/@types/load-json-file/package.json' has unsupported extension. The only supported extensions are '.ts', '.tsx', '.d.ts'. (6054)
File '/home/tom/Projects/tomdavidson/s6/node_modules/@types/node/package.json' has unsupported extension. The only supported extensions are '.ts', '.tsx', '.d.ts'. (6054)
File '/home/tom/Projects/tomdavidson/s6/node_modules/home-court/package.json' has unsupported extension. The only supported extensions are '.ts', '.tsx', '.d.ts'. (6054)
File '/home/tom/Projects/tomdavidson/s6/node_modules/load-json-file/package.json' has unsupported extension. The only supported extensions are '.ts', '.tsx', '.d.ts'. (6054)
File '/home/tom/Projects/tomdavidson/s6/node_modules/tslib/package.json' has unsupported extension. The only supported extensions are '.ts', '.tsx', '.d.ts'. (6054)
File '/home/tom/Projects/tomdavidson/s6/node_modules/url/package.json' has unsupported extension. The only supported extensions are '.ts', '.tsx', '.d.ts'. (6054)
File '/home/tom/Projects/tomdavidson/s6/node_modules/url/url.js' has unsupported extension. The only supported extensions are '.ts', '.tsx', '.d.ts'. (6054)
    at getOutput (/home/tom/Projects/tomdavidson/s6/node_modules/ts-node/src/index.ts:300:15)
    at /home/tom/Projects/tomdavidson/s6/node_modules/ts-node/src/index.ts:330:16
    at Object.compile (/home/tom/Projects/tomdavidson/s6/node_modules/ts-node/src/index.ts:489:17)
    at Object.m._compile (/home/tom/Projects/tomdavidson/s6/node_modules/ts-node/src/index.ts:382:43)
    at Module._extensions..js (module.js:579:10)
    at Object.require.extensions.(anonymous function) [as .ts] (/home/tom/Projects/tomdavidson/s6/node_modules/ts-node/src/index.ts:385:12)
    at NYC._readTranspiledSource (/home/tom/Projects/tomdavidson/s6/node_modules/nyc/index.js:160:26)
    at NYC.addFile (/home/tom/Projects/tomdavidson/s6/node_modules/nyc/index.js:144:21)
    at /home/tom/Projects/tomdavidson/s6/node_modules/nyc/index.js:176:11
    at /home/tom/Projects/tomdavidson/s6/node_modules/nyc/index.js:244:5
```
`tsc` handles the project fine and if I suppress `ts-node` warnings with `-D` then the script executes without issue.

**Comment by eventualbuddha** [comment]
I'm seeing similar issues: https://github.com/decaffeinate/decaffeinate/issues/1065 https://github.com/decaffeinate/decaffeinate-parser/issues/219 https://github.com/decaffeinate/coffee-lex/issues/108.

**Comment by blakeembrey** [comment]
This was fixed in https://github.com/TypeStrong/ts-node/issues/344 already. Please search before opening a duplicate issue.

**Comment by blakeembrey** [comment]
Similarly, @eventualbuddha, if you read the Greenkeeper you would see it was also fixed before you even commented here: https://github.com/decaffeinate/decaffeinate/issues/1065#issuecomment-306578744.

**Comment by eventualbuddha** [comment]
Whoops, you're right! I've only had 10 minute spans of time today between meetings so I didn't realize the situation was resolved. Thanks for the fix!
