### ISSUE TITLE
ts-node is breaking bunch of projects

### ISSUE THREAD

**Issue by unional** [TypeStrong/ts-node#349]
e.g. https://github.com/types/npm-no-op/issues/2

It is trying to run against some .js files:

```sh
/home/travis/build/types/npm-no-op/node_modules/ts-node/src/index.ts:300
        throw new TSError(formatDiagnostics(diagnosticList, cwd, ts, lineOffset))
              ^
TSError: ⨯ Unable to compile TypeScript
File '/home/travis/build/types/npm-no-op/node_modules/blue-tape/blue-tape.js' has unsupported extension. The only supported extensions are '.ts', '.tsx', '.d.ts'. (6054)
File '/home/travis/build/types/npm-no-op/node_modules/blue-tape/package.json' has unsupported extension. The only supported extensions are '.ts', '.tsx', '.d.ts'. (6054)
File '/home/travis/build/types/npm-no-op/node_modules/no-op/index.js' has unsupported extension. The only supported extensions are '.ts', '.tsx', '.d.ts'. (6054)
File '/home/travis/build/types/npm-no-op/node_modules/no-op/package.json' has unsupported extension. The only supported extensions are '.ts', '.tsx', '.d.ts'. (6054)
    at getOutput (/home/travis/build/types/npm-no-op/node_modules/ts-node/src/index.ts:300:15)
    at /home/travis/build/types/npm-no-op/node_modules/ts-node/src/index.ts:330:16
    at Object.compile (/home/travis/build/types/npm-no-op/node_modules/ts-node/src/index.ts:489:17)
    at Module.m._compile (/home/travis/build/types/npm-no-op/node_modules/ts-node/src/index.ts:382:43)
    at Module._extensions..js (module.js:580:10)
    at Object.require.extensions.(anonymous function) [as .ts] (/home/travis/build/types/npm-no-op/node_modules/ts-node/src/index.ts:385:12)
    at Module.load (module.js:503:32)
    at tryModuleLoad (module.js:466:12)
    at Function.Module._load (module.js:458:3)
    at Module.require (module.js:513:17)
```

**Comment by blakeembrey** [comment]
See https://github.com/TypeStrong/ts-node/issues/344 and the previous four closed issues 😄

**Comment by blakeembrey** [comment]
You should be able to just close those issues if you see https://github.com/types/npm-no-op/issues/2#issuecomment-306581197.
