### ISSUE TITLE
Could not find file in NPM link package with file ending svg

### ISSUE THREAD

**Issue by nihiluis** [TypeStrong/ts-node#371]
I'm using a local dependency package via npm link. If I use `import * as logoIcon from './logo.svg'` it throws an error. Same goes for file ending css (probably all that aren't ts or tsx). File is properly loaded by the corresponding loader.

Only crashes on nodemon (for server side rendering), but not on webpack-dev-server.

Is this related to ts-node or possibly to some other package? (tsconfig-paths is not the culprit)

```
Error: Could not find file: 'projects/work/nx-ui/src/components/misc/Logo/logo.svg'.
    at getValidSourceFile (projects/work/land/node_modules/typescript/lib/typescript.js:86054:23)
    at Object.getEmitOutput (projects/work/land/node_modules/typescript/lib/typescript.js:86415:30)
    at getOutput (projects/work/land/node_modules/ts-node/src/index.ts:286:30)
    at projects/work/land/node_modules/ts-node/src/index.ts:325:16
    at Object.compile (projects/work/land/node_modules/ts-node/src/index.ts:479:11)
    at Module.m._compile (projects/work/land/node_modules/ts-node/src/index.ts:379:43)
    at Module._extensions..js (module.js:579:10)
    at Object.require.extensions.(anonymous function) [as .js] (projects/work/land/node_modules/ts-node/src/index.ts:382:12)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
    at Function.Module._load (projects/work/land/node_modules/tsconfig-paths/lib/register.js:26:31)
    at Module.require (module.js:497:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (projects/work/nx-ui/src/components/misc/Logo/index.tsx:14:16)
    at Module._compile (module.js:570:32)

[nodemon] app crashed - waiting for file changes before starting...
```
tsconfig.json
```json
{
  "compilerOptions": {
    "allowJs": true,
    "sourceMap": true,
    "target": "es5",
    "jsx": "react",
    "module": "commonjs",
    "moduleResolution": "node",
    "emitDecoratorMetadata": true,
    "experimentalDecorators": true,
    "forceConsistentCasingInFileNames": true,
    "noFallthroughCasesInSwitch": false,
    "noImplicitReturns": true,
    "noUnusedLocals": true,
    "noUnusedParameters": true,
    "noImplicitUseStrict": true,
    "allowUnreachableCode": true,
    "pretty": true,
    "strictNullChecks": true,
    "lib": [
      "es2015",
      "dom"
    ],
    "baseUrl": ".",
    "paths": {
      "*": [
        "*",
        "src/*",
        "src/client/*",
        "src/shared/*"
      ],
      "nx-land/typings": [
        "./typings/models.d.ts"
      ]
    }
  },
  "include": [
    "bin/*",
    "src/**/*",
    "webpack/**/*",
    "typings/*",
    "webpack.config.ts",
    "node_modules/nx-ui/*",
    "node_modules/nx-ui/**/*"
  ],
  "exclude": [
    "dist",
    "build",
    "node_modules"
  ]
}
```

tsconfig.json of dependency (almost the samse)
```json
{
  "compilerOptions": {
    "allowJs": true,
    "sourceMap": false,
    "target": "es5",
    "jsx": "react",
    "module": "commonjs",
    "moduleResolution": "node",
    "emitDecoratorMetadata": true,
    "experimentalDecorators": true,
    "forceConsistentCasingInFileNames": true,
    "noFallthroughCasesInSwitch": false,
    "noImplicitReturns": true,
    //"noImplicitThis": true,
    "noUnusedLocals": true,
    "noUnusedParameters": true,
    "noImplicitUseStrict": true,
    "allowUnreachableCode": true,
    "pretty": true,
    "strictNullChecks": true,
    //"outDir": "build",
    "lib": [
      "es2015",
      "dom"
    ],
    "baseUrl": ".",
    "paths": {
      "nx-ui/typings": [
        "./typings"
      ]
    }
    //"types": ["node"],
  },
  "include": [
    "src/*",
    "src/**/*",
    "typings/*",
    "webpack/**/*",
    "webpack.config.ts"
  ],
  "exclude": [
    "dist",
    "build",
    "node_modules"
  ]
}
```
webpack config
```ts
import * as path from 'path'
import * as webpack from 'webpack'

const baseConfig: webpack.Configuration = {
  module: {
    rules: [
      //{
      //  enforce: 'pre',
      //  test: /\.tsx?$/,
      //  loader: 'tslint-loader'
      //},
      {
        test: /\.jsx$/,
        loader: 'babel-loader'
      },
      {
        test: /\.json$/,
        loader: 'json-loader'
      },
      {
        test: /\.p?css$/,
        use: [
          { loader: 'style-loader' },
          {
            loader: 'css-loader',
            query: {
              localIdentName: '[path][name]---[local]---[hash:base64:5]',
              modules: true,
              sourceMap: true,
            },
          },
          { loader: 'postcss-loader' }
        ],
      },
      {
        test: /\.(png|jpe?g|gif)(\?.*)?$/,
        use: [
          {
            loader: 'url-loader',
            query: {
              limit: 10000,
            }
          },
        ]
      },
      {
        test: /\.svg$/,
        use: [
          {
            loader: 'svg-inline-loader'
          }
        ]
      }
    ]
  },
  plugins: [
    new webpack.optimize.CommonsChunkPlugin({
      filename: '[name].js',
      minChunks: 3,
      name: 'main',
    }),
    new webpack.optimize.AggressiveMergingPlugin(),
  ],
  output: {
    path: path.join(__dirname, '..', 'dist/static'),
  },
  resolve: {
    alias: {
      shared: path.resolve(__dirname, '../src/shared'),
      components: path.resolve(__dirname, '../src/shared/components'),
      containers: path.resolve(__dirname, '../src/shared/containers'),
      config: path.resolve(__dirname, '../../src/config.ts'),
      server: path.resolve(__dirname, '../src/server'),
    },
    extensions: [
      '.js',
      '.jsx',
      '.ts',
      '.tsx',
      '.css',
      '.svg',
      '.png',
      '.pcss'
    ],
  },

}

export default baseConfig
```

**Comment by blakeembrey** [comment]
Please make a demo if you'd like help on something as complex as this. As it is, I don't believe this is related to `ts-node`. In node.js, you can't magically make `.svg` or `.css` files work. They end up being treated as `.js`, which would break. You might want to either run the Webpack bundle in JavaScript so it's compiled to something node.js can run or find the appropriate loaders for node.js to use (as you have `ts-node` for `.ts`).

**Comment by nihiluis** [comment]
It's using webpack on the server and `.svg` or `.css` work fine, as long as they are in a normal directory and not in `node_modules/...` Trying hard on this, will see if I need a demo
