### ISSUE TITLE
Intersection types not working

### ISSUE THREAD

**Issue by david-reir** [TypeStrong/ts-node#407]
I'm testing the example of typescript handbook about intersection types and it's not working. It works well with tsc but it doesn't with ts-node.

```
function extend<T, U>(first: T, second: U): T & U {
    let result = <T & U>{};
    for (let id in first) {
        (<any>result)[id] = (<any>first)[id];
    }
    for (let id in second) {
        if (!result.hasOwnProperty(id)) {
            (<any>result)[id] = (<any>second)[id];
        }
    }
    return result;
}

class Person {
    constructor(public name: string) { }
}
interface Loggable {
    log(): void;
}
class ConsoleLogger implements Loggable {
    log() {
        // ...
    }
}
var jim = extend(new Person("Jim"), new ConsoleLogger());
var n = jim.name;
jim.log();
```

The error says:
```
TypeError: jim.log is not a function
    at Object.<anonymous> (E:\david\projects\typescript\advTypes.ts:27:5)
    at Module._compile (module.js:570:32)
    at Module.m._compile (E:\david\projects\typescript\node_modules\ts-node\src\
index.ts:392:23)
    at Module._extensions..js (module.js:579:10)
    at Object.require.extensions.(anonymous function) [as .ts] (E:\david\project
s\typescript\node_modules\ts-node\src\index.ts:395:12)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
    at Function.Module.runMain (module.js:604:10)
    at Object.<anonymous> (E:\david\projects\typescript\node_modules\ts-node\src
\_bin.ts:182:12)
```

**Comment by blakeembrey** [comment]
Works for me. You will need to provide more information if you expect help.

![image](https://user-images.githubusercontent.com/1088987/29439693-28fd83ca-8374-11e7-9ba7-641f6bd8e5d3.png)

**Comment by blakeembrey** [comment]
Closing this now. Feel free to continue the discussion and I'll re-open.

**Comment by dominion-ubah** [comment]
this is okay if you want to extend but what about when you want to intesect
