### ISSUE TITLE
Cannot redeclare block-scoped variable 'React'

### ISSUE THREAD

**Issue by jmjpro** [TypeStrong/ts-node#430]
I receive this and several other similar messages for other libraries whenever I compile my code with ts-node. I don't receive similar errors when running the same code through tsc.

I have tried to change the target and the lib and several other settings but nothing seems to help.

I'm running the following versions:
ts-node v3.3.0
node v8.5.0
typescript v2.5.2

Here's my config:
```
{
  "compilerOptions": {
    /* Basic Options */
    "target": "esnext",                          /* Specify ECMAScript target version: 'ES3' (default), 'ES5', 'ES2015', 'ES2016', 'ES2017', or 'ESNEXT'. */
    "module": "commonjs",                     /* Specify module code generation: 'commonjs', 'amd', 'system', 'umd', 'es2015', or 'ESNext'. */
    // "lib": ["es2015", "dom"],                             /* Specify library files to be included in the compilation:  */
    "allowJs": true,                       /* Allow javascript files to be compiled. */
    "checkJs": false,                       /* Report errors in .js files. */
    "jsx": "react",                     /* Specify JSX code generation: 'preserve', 'react-native', or 'react'. */
    // "declaration": true,                   /* Generates corresponding '.d.ts' file. */
    // "sourceMap": true,                     /* Generates corresponding '.map' file. */
    // "outFile": "./",                       /* Concatenate and emit output to single file. */
    "outDir": "build",                        /* Redirect output structure to the directory. */
    // "rootDir": "./",                       /* Specify the root directory of input files. Use to control the output directory structure with --outDir. */
    // "removeComments": true,                /* Do not emit comments to output. */
    // "noEmit": true,                        /* Do not emit outputs. */
    // "importHelpers": true,                 /* Import emit helpers from 'tslib'. */
    // "downlevelIteration": true,            /* Provide full support for iterables in 'for-of', spread, and destructuring when targeting 'ES5' or 'ES3'. */
    // "isolatedModules": true,               /* Transpile each file as a separate module (similar to 'ts.transpileModule'). */

    /* Strict Type-Checking Options */
    "strict": true,                            /* Enable all strict type-checking options. */
    "noImplicitAny": false,                 /* Raise error on expressions and declarations with an implied 'any' type. */
    // "strictNullChecks": true,              /* Enable strict null checks. */
    // "noImplicitThis": true,                /* Raise error on 'this' expressions with an implied 'any' type. */
    // "alwaysStrict": true,                  /* Parse in strict mode and emit "use strict" for each source file. */

    /* Additional Checks */
    // "noUnusedLocals": true,                /* Report errors on unused locals. */
    // "noUnusedParameters": true,            /* Report errors on unused parameters. */
    // "noImplicitReturns": true,             /* Report error when not all code paths in function return a value. */
    // "noFallthroughCasesInSwitch": true,    /* Report errors for fallthrough cases in switch statement. */

    /* Module Resolution Options */
    "moduleResolution": "node",            /* Specify module resolution strategy: 'node' (Node.js) or 'classic' (TypeScript pre-1.6). */
    "baseUrl": "./src",                       /* Base directory to resolve non-absolute module names. */
    "paths": {
      "~/*" : ["*"]   // resolve any `~/foo/bar` to `<baseUrl>/foo/bar`
    }                          /* A series of entries which re-map imports to lookup locations relative to the 'baseUrl'. */
    // "rootDirs": [],                        /* List of root folders whose combined content represents the structure of the project at runtime. */
    // "typeRoots": [],                       /* List of folders to include type definitions from. */
    //"types": ["./vendor.d.ts"]                           /* Type declaration files to be included in compilation. */
    // "allowSyntheticDefaultImports": true  /* Allow default imports from modules with no default export. This does not affect code emit, just typechecking. */

    /* Source Map Options */
    // "sourceRoot": "./",                    /* Specify the location where debugger should locate TypeScript files instead of source locations. */
    // "mapRoot": "./",                       /* Specify the location where debugger should locate map files instead of generated locations. */
    // "inlineSourceMap": true,               /* Emit a single file with source maps instead of having a separate file. */
    // "inlineSources": true,                 /* Emit the source alongside the sourcemaps within a single file; requires '--inlineSourceMap' or '--sourceMap' to be set. */

    /* Experimental Options */
    // "experimentalDecorators": true,        /* Enables experimental support for ES7 decorators. */
    // "emitDecoratorMetadata": true,         /* Enables experimental support for emitting type metadata for decorators. */
  },
  "include": [
    "vendor.d.ts",
    "src/**/*.ts",
    "src/**/*.tsx",
    "src/**/*.js",
    //"install/**/*.ts",
    "config/**/*.ts"
  ],
  "exclude": [
    "node_modules"
  ]
}
```

**Comment by blakeembrey** [comment]
I can't do much with this, sorry. Can you share a reproducible demo or narrow it down so I can see the error myself?

**Comment by jmjpro** [comment]
I'm trying to narrow it down. It's not so simple because the error is intermittent and inconsistent, i.e. sometimes it just seems to go away on its own. When the error does occur it seems to rotate between different files upon different runs of ts-node:

run 1:
```
/Users/joshua/Projects/elminda/bna-report-gen/node_modules/ts-node/src/index.ts:307
        throw new TSError(formatDiagnostics(diagnosticList, cwd, ts, lineOffset))
              ^
TSError: ⨯ Unable to compile TypeScript
src/fip/report_components/styles.ts (3,7): Cannot redeclare block-scoped variable 'styled_components_1'. (2451)
src/fip/report_components/styles.ts (4,7): Cannot redeclare block-scoped variable 'common_1'. (2451)
src/fip/report_components/styles.ts (5,28): Cannot redeclare block-scoped variable 'PageConstants'. (2451)
    at getOutput (/Users/joshua/Projects/elminda/bna-report-gen/node_modules/ts-node/src/index.ts:307:15)
    at /Users/joshua/Projects/elminda/bna-report-gen/node_modules/ts-node/src/index.ts:336:16
    at Object.compile (/Users/joshua/Projects/elminda/bna-report-gen/node_modules/ts-node/src/index.ts:498:11)
    at Module.m._compile (/Users/joshua/Projects/elminda/bna-report-gen/node_modules/ts-node/src/index.ts:392:43)
    at Module.m._compile (/Users/joshua/Projects/elminda/bna-report-gen/node_modules/ts-node/src/index.ts:392:23)
    at Module._extensions..js (module.js:635:10)
    at require.extensions.(anonymous function) (/Users/joshua/Projects/elminda/bna-report-gen/node_modules/ts-node/src/index.ts:395:12)
    at Object.require.extensions.(anonymous function) [as .ts] (/Users/joshua/Projects/elminda/bna-report-gen/node_modules/ts-node/src/index.ts:395:12)
    at Module.load (module.js:545:32)
    at tryModuleLoad (module.js:508:12)
```

run 2:
```
/Users/joshua/Projects/elminda/bna-report-gen/node_modules/ts-node/src/index.ts:307
        throw new TSError(formatDiagnostics(diagnosticList, cwd, ts, lineOffset))
              ^
TSError: ⨯ Unable to compile TypeScript
src/common/subject_information.tsx (3,7): Cannot redeclare block-scoped variable 'React'. (2451)
src/common/subject_information.tsx (4,7): Cannot redeclare block-scoped variable 'styled_components_1'. (2451)
src/common/subject_information.tsx (5,7): Cannot redeclare block-scoped variable 'constants_1'. (2451)
    at getOutput (/Users/joshua/Projects/elminda/bna-report-gen/node_modules/ts-node/src/index.ts:307:15)
    at /Users/joshua/Projects/elminda/bna-report-gen/node_modules/ts-node/src/index.ts:336:16
    at Object.compile (/Users/joshua/Projects/elminda/bna-report-gen/node_modules/ts-node/src/index.ts:498:11)
    at Module.m._compile (/Users/joshua/Projects/elminda/bna-report-gen/node_modules/ts-node/src/index.ts:392:43)
    at Module.m._compile (/Users/joshua/Projects/elminda/bna-report-gen/node_modules/ts-node/src/index.ts:392:23)
    at Module._extensions..js (module.js:635:10)
    at require.extensions.(anonymous function) (/Users/joshua/Projects/elminda/bna-report-gen/node_modules/ts-node/src/index.ts:395:12)
    at Object.require.extensions.(anonymous function) [as .tsx] (/Users/joshua/Projects/elminda/bna-report-gen/node_modules/ts-node/src/index.ts:395:12)
    at Module.load (module.js:545:32)
    at tryModuleLoad (module.js:508:12)
```

**Comment by jmjpro** [comment]
My imports look like this:
```
import * as React from 'react'
import styled from 'styled-components'
```

**Comment by blakeembrey** [comment]
From the looks of things like `styled_components_1`, it's going through transpilation multiple times. Have you registered `ts-node` twice, or another transpiler before `ts-node`?

**Comment by sagnol** [comment]
I have same error.
using nodemon (nodemon.json)
```
"exec": "ts-node index.js",
```

**Comment by blakeembrey** [comment]
Closing without extra info.

**Comment by mcavaliere** [comment]
For anyone interested, I've run into this as well. The resolution was removing a `require` call to `ts-node` or `@babel/register` from the codebase.
