### ISSUE TITLE
SyntaxError: Unexpected token } in JSON at position 4707

### ISSUE THREAD

**Issue by leebenson** [TypeStrong/ts-node#449]
Node v8.7.0, Typescript 2.5.3 -- 

After installing globally...

> ➜  api git:(master) ✗ npm install -g ts-node
/usr/local/bin/_ts-node -> /usr/local/lib/node_modules/ts-node/dist/_bin.js
/usr/local/bin/ts-node -> /usr/local/lib/node_modules/ts-node/dist/bin.js
> + ts-node@3.3.0
updated 1 package in 0.725s

... neither the REPL or script loading works - I get the following JSON error:

> ➜  api git:(master) ✗ ts-node               
SyntaxError: Unexpected token } in JSON at position 4707
    at JSON.parse (<anonymous>)
    at parse (/usr/local/lib/node_modules/ts-node/node_modules/tsconfig/src/tsconfig.ts:195:15)
    at readFileSync (/usr/local/lib/node_modules/ts-node/node_modules/tsconfig/src/tsconfig.ts:181:10)
    at Object.loadSync (/usr/local/lib/node_modules/ts-node/node_modules/tsconfig/src/tsconfig.ts:151:18)
    at readConfig (/usr/local/lib/node_modules/ts-node/src/index.ts:425:18)
    at Object.register (/usr/local/lib/node_modules/ts-node/src/index.ts:189:18)
    at Object.<anonymous> (/usr/local/lib/node_modules/ts-node/src/_bin.ts:140:17)
    at Module._compile (module.js:624:30)
    at Object.Module._extensions..js (module.js:635:10)
    at Module.load (module.js:545:32)

**Comment by blakeembrey** [comment]
Can you share your `tsconfig.json` file? Are you sure it doesn’t have a syntax error?

**Comment by leebenson** [comment]
Oops - my bad. Extraneous comma. Weirdly, `tsc` forgave it. Closing.

**Comment by blakeembrey** [comment]
Interesting. It’s likely an update needed in our config loader then. Right now it’s only stripping comments, I didn’t realise TypeScript also relaxed other parts of the config also.

**Comment by soerenBoisen** [comment]
Could this be reopened, since this is a bug in the loader per above comment?

**Comment by blakeembrey** [comment]
@soerenBoisen Feel free to open an issue or PR to https://github.com/TypeStrong/tsconfig, it's not handled here. You can also open an issue with TypeScript since the reason it had to be handled outside `ts-node` is that the TypeScript method wasn't exposed (this has probably changed since then, but I don't have time to fix it).

**Comment by tbsvttr** [comment]
@leebenson Had the same problem and I wonder why neither tsc nor tslint or prettier said something about. In my case it was at the end of a list. What was it in your case? Maybe one of us should create an issue about that at some of the relevant places.

**Comment by leebenson** [comment]
@tbsvttr I imagine it's because JSON is being parsed different in `tsc` and `tslint`, rather than using the built-in `JSON.parse()`. Not 100%, though - I haven't dived into the code. But that'd make sense, since they're doing some pretty heavy AST parsing anyway.

**Comment by blakeembrey** [comment]
FWIW, this has been fixed since [5.0](https://github.com/TypeStrong/ts-node/releases/tag/v5.0.0) (February).

**Comment by shreya121212** [comment]
SyntaxError: Unexpected token p in JSON at position 2
at JSON.parse ()
at Object.Utils.JSON.parse (/Users/Admin/Desktop/bitshare/node_modules/jayson/lib/utils.js:274:26)
at IncomingMessage. (/Users/Admin/Desktop/bitshare/node_modules/jayson/lib/client/http.js:75:22)
at IncomingMessage.emit (events.js:187:15)
at endReadableNT (_stream_readable.js:1081:12)
at process._tickCallback (internal/process/next_tick.js:63:19)

this is the errror which comes from bitshare-rpc, how can i resolve this??

**Comment by kevindashgit** [comment]
This was driving me nuts!!! An extra comma was the issue - but I wasn't sure which JSON file was causing the problem!

**Comment by hydraslay** [comment]
Don't know exactly why but a similar issue solved when I updated ts-node -> 12.12, @types/node -> 8.5, typescript -> 3.7 (maybe one of them was not relevant) to latest version.
