### ISSUE TITLE
Sometimes I get 'unknown error, open' errors

### ISSUE THREAD

**Issue by spacem** [TypeStrong/ts-node#467]
Hi, sorry I am not 100% sure this is ts-node that causes this but I have been seeing these errors from time to time. Whenever this happens I just end my build task and build again and it works fine. If it makes any difference this happened in the middle of gulp-mocha task (I run gulp with a gulpfile.ts).

I have ts-node@3.3.0 installed, node 8.9.1 and windows 7.

   UNKNOWN: unknown error, open 'C:\Users\PLAY~1.BBB\AppData\Local\Temp\ts-node-021db2043d0283c486561fbbe8522b9d7a853983d485a88d2f086152cf5a2ee9\4ec2c5a2b91b6324a8f03e5607d83fd125248aee32e1c22fdd1ed403b9b4847d\5af6465cad9306da275ec46778251b6d250b4ed3870e5315fc202fd4e0a50127.js'
Details:
    errno: -4094
    code: UNKNOWN
    syscall: open
    path: C:\Users\PLAY~1.BBB\AppData\Local\Temp\ts-node-021db2043d0283c486561fbbe8522b9d7a853983d485a88d2f086152cf5a2ee9\4ec2c5a2b91b6324a8f03e5607d83fd125248aee32e1c22fdd1ed403b9b4847d\5af6465cad9306da275ec46778251b6d250b4ed3870e5315fc202fd4e0a50127.js
Stack:
Error: UNKNOWN: unknown error, open 'C:\Users\PLAY~1.BBB\AppData\Local\Temp\ts-node-021db2043d0283c486561fbbe8522b9d7a853983d485a88d2f086152cf5a2ee9\4ec2c5a2b91b6324a8f03e5607d83fd125248aee32e1c22fdd1ed403b9b4847d\5af6465cad9306da275ec46778251b6d250b4ed3870e5315fc202fd4e0a50127.js'
    at Object.fs.openSync (fs.js:646:18)
    at Object.fs.writeFileSync (fs.js:1291:33)
    at Object.compile (c:\work\project1\node_modules\ts-node\src\index.ts:502:5)
    at Module.m._compile (c:\work\project1\node_modules\ts-node\src\index.ts:392:43)
    at Module._extensions..js (module.js:646:10)
    at Object.require.extensions.(anonymous function) [as .js] (c:\work\project1\node_modules\ts-node\src\index.ts:395:12)
    at Module.load (module.js:554:32)
    at tryModuleLoad (module.js:497:12)
    at Function.Module._load (module.js:489:3)
    at Module.require (module.js:579:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (c:\work\project1\core\lib\ibm-maximo-api\resources\resourceset.js:13:22)
    at Module._compile (module.js:635:30)
    at Module.m._compile (c:\work\project1\node_modules\ts-node\src\index.ts:392:23)
    at Module._extensions..js (module.js:646:10)
    at Object.require.extensions.(anonymous function) [as .js] (c:\work\project1\node_modules\ts-node\src\index.ts:395:12)
    at Module.load (module.js:554:32)
    at tryModuleLoad (module.js:497:12)
    at Function.Module._load (module.js:489:3)
    at Module.require (module.js:579:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (c:\work\project1\core\lib\ibm-maximo-api\resources\resourceobject.js:4:19)

**Comment by galilg** [comment]
Hi! Did you find a solution to this issue? I'm facing the same one.

**Comment by spacem** [comment]
Sorry.. actually I don't remember now the last time this happened but since reporting this I got a new laptop now with windows 10 and updated node (now 8.9.3) and typescript (now 2.6.2) also I reset my tsconfig to be the angular-cli generated one so you could try one of those things.

**Comment by mtuzinskiy** [comment]
@galilg  Hi! Did you find a solution to this issue back then?
