### ISSUE TITLE
When will be the next release?

### ISSUE THREAD

**Issue by cevek** [TypeStrong/ts-node#468]
I really need custom transformers

**Comment by netpoetica** [comment]
We are having trouble with Chalk version ts-node is using, I noticed you guys updated it in package.json but have not cut a release yet. Hoping this version update will help... I was trying to install directly from master, but this doesn't do all of the magical npm publish, dist stuff.

```
npm i git://github.com/TypeStrong/ts-node.git#master

npm ERR! path /Users/rosenbek/Desktop/git/adp-e-websocket-backend/node_modules/ts-node/dist/bin.js
npm ERR! code ENOENT
npm ERR! errno -2
npm ERR! syscall chmod
npm ERR! enoent ENOENT: no such file or directory, chmod '/my-project/node_modules/ts-node/dist/bin.js'
npm ERR! enoent This is related to npm not being able to find a file.
npm ERR! enoent 
```

See: https://github.com/chalk/chalk/issues/31

Based on our testing, it seems to be an issue with the Chalk version ts-node is using vs. the Chalk version the `elasticsearch` module is using, and only when we run ts-node+mocha for testing. It's a narsty one

```
/my-project/node_modules/escape-string-regexp/index.js:7
		throw new TypeError('Expected a string');
        ^
TypeError: Expected a string
    at module.exports (/my-project/node_modules/escape-string-regexp/index.js:7:9)
    at /my-project/node_modules/chalk/index.js:24:40
    at Array.forEach (<anonymous>)
    at /my-project/node_modules/chalk/index.js:23:26
    at Object.<anonymous> (/my-project/node_modules/chalk/index.js:34:3)
    at Module._compile (module.js:624:30)
    at Module._extensions..js (module.js:635:10)
    at Object.require.extensions.(anonymous function) [as .js] (/my-project/node_modules/ts-node/src/index.ts:384:14)
    at Module.load (module.js:545:32)
    at tryModuleLoad (module.js:508:12)
    at Function.Module._load (module.js:500:3)
    at Module.require (module.js:568:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (/my-project/node_modules/elasticsearch/src/lib/loggers/stdio.js:15:13)
    at Module._compile (module.js:624:30)
    at Module._extensions..js (module.js:635:10)
    at Object.require.extensions.(anonymous function) [as .js] (/my-project/node_modules/ts-node/src/index.ts:384:14)
    at Module.load (module.js:545:32)
    at tryModuleLoad (module.js:508:12)
    at Function.Module._load (module.js:500:3)
    at Module.require (module.js:568:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (/my-project/node_modules/elasticsearch/src/lib/loggers/index.js:5:10)
    at Module._compile (module.js:624:30)
    at Module._extensions..js (module.js:635:10)
    at Object.require.extensions.(anonymous function) [as .js] (/my-project/node_modules/ts-node/src/index.ts:384:14)
    at Module.load (module.js:545:32)
    at tryModuleLoad (module.js:508:12)
    at Function.Module._load (module.js:500:3)
    at Module.require (module.js:568:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (/my-project/node_modules/elasticsearch/src/lib/log.js:55:15)
    at Module._compile (module.js:624:30)
    at Module._extensions..js (module.js:635:10)
    at Object.require.extensions.(anonymous function) [as .js] (/my-project/node_modules/ts-node/src/index.ts:384:14)
    at Module.load (module.js:545:32)
    at tryModuleLoad (module.js:508:12)
    at Function.Module._load (module.js:500:3)
    at Module.require (module.js:568:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (/my-project/node_modules/elasticsearch/src/lib/connection_pool.js:13:11)
    at Module._compile (module.js:624:30)
    at Module._extensions..js (module.js:635:10)
    at Object.require.extensions.(anonymous function) [as .js] (/my-project/node_modules/ts-node/src/index.ts:384:14)
    at Module.load (module.js:545:32)
    at tryModuleLoad (module.js:508:12)
    at Function.Module._load (module.js:500:3)
    at Module.require (module.js:568:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (/my-project/node_modules/elasticsearch/src/lib/transport.js:105:9)
    at Module._compile (module.js:624:30)
    at Module._extensions..js (module.js:635:10)
    at Object.require.extensions.(anonymous function) [as .js] (/my-project/node_modules/ts-node/src/index.ts:384:14)
    at Module.load (module.js:545:32)
    at tryModuleLoad (module.js:508:12)
    at Function.Module._load (module.js:500:3)
    at Module.require (module.js:568:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (/my-project/node_modules/elasticsearch/src/lib/client.js:29:17)
    at Module._compile (module.js:624:30)
    at Module._extensions..js (module.js:635:10)
    at Object.require.extensions.(anonymous function) [as .js] (/my-project/node_modules/ts-node/src/index.ts:384:14)
    at Module.load (module.js:545:32)
    at tryModuleLoad (module.js:508:12)
    at Function.Module._load (module.js:500:3)
    at Module.require (module.js:568:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (/my-project/node_modules/elasticsearch/src/elasticsearch.js:10:13)
    at Module._compile (module.js:624:30)
    at Module._extensions..js (module.js:635:10)
    at Object.require.extensions.(anonymous function) [as .js] (/my-project/node_modules/ts-node/src/index.ts:384:14)
    at Module.load (module.js:545:32)
    at tryModuleLoad (module.js:508:12)
    at Function.Module._load (module.js:500:3)
    at Module.require (module.js:568:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (/my-project/src/lib/comm-adapter/ElasticsearchClient.ts:2:1)
    at Module._compile (module.js:624:30)
    at Module.m._compile (/my-project/node_modules/ts-node/src/index.ts:392:23)
    at Module._extensions..js (module.js:635:10)
    at Object.require.extensions.(anonymous function) [as .ts] (/my-project/node_modules/ts-node/src/index.ts:395:12)
    at Module.load (module.js:545:32)
    at tryModuleLoad (module.js:508:12)
    at Function.Module._load (module.js:500:3)
    at Module.require (module.js:568:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (/my-project/src/api/queries/FullTextSearch/fullTextSearchTimeline.ts:3:1)
    at Module._compile (module.js:624:30)
    at Module.m._compile (/my-project/node_modules/ts-node/src/index.ts:392:23)
    at Module._extensions..js (module.js:635:10)
    at Object.require.extensions.(anonymous function) [as .ts] (/my-project/node_modules/ts-node/src/index.ts:395:12)
    at Module.load (module.js:545:32)
    at tryModuleLoad (module.js:508:12)
    at Function.Module._load (module.js:500:3)
    at Module.require (module.js:568:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (/my-project/src/api/queries/index.ts:47:1)
    at Module._compile (module.js:624:30)
    at Module.m._compile (/my-project/node_modules/ts-node/src/index.ts:392:23)
    at Module._extensions..js (module.js:635:10)
    at Object.require.extensions.(anonymous function) [as .ts] (/my-project/node_modules/ts-node/src/index.ts:395:12)
    at Module.load (module.js:545:32)
    at tryModuleLoad (module.js:508:12)
    at Function.Module._load (module.js:500:3)
    at Module.require (module.js:568:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (/my-project/src/api/Root.ts:1:1)
    at Module._compile (module.js:624:30)
    at Module.m._compile (/my-project/node_modules/ts-node/src/index.ts:392:23)
    at Module._extensions..js (module.js:635:10)
    at Object.require.extensions.(anonymous function) [as .ts] (/my-project/node_modules/ts-node/src/index.ts:395:12)
    at Module.load (module.js:545:32)
    at tryModuleLoad (module.js:508:12)
    at Function.Module._load (module.js:500:3)
    at Module.require (module.js:568:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (/my-project/src/api/API.ts:3:1)
    at Module._compile (module.js:624:30)
    at Module.m._compile (/my-project/node_modules/ts-node/src/index.ts:392:23)
    at Module._extensions..js (module.js:635:10)
    at Object.require.extensions.(anonymous function) [as .ts] (/my-project/node_modules/ts-node/src/index.ts:395:12)
    at Module.load (module.js:545:32)
    at tryModuleLoad (module.js:508:12)
    at Function.Module._load (module.js:500:3)
    at Module.require (module.js:568:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (/my-project/src/api/index.ts:2:1)
    at Module._compile (module.js:624:30)
    at Module.m._compile (/my-project/node_modules/ts-node/src/index.ts:392:23)
    at Module._extensions..js (module.js:635:10)
    at Object.require.extensions.(anonymous function) [as .ts] (/my-project/node_modules/ts-node/src/index.ts:395:12)
    at Module.load (module.js:545:32)
    at tryModuleLoad (module.js:508:12)
    at Function.Module._load (module.js:500:3)
    at Module.require (module.js:568:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (/my-project/src/Session.ts:1:1)
    at Module._compile (module.js:624:30)
    at Module.m._compile (/my-project/node_modules/ts-node/src/index.ts:392:23)
    at Module._extensions..js (module.js:635:10)
    at Object.require.extensions.(anonymous function) [as .ts] (/my-project/node_modules/ts-node/src/index.ts:395:12)
    at Module.load (module.js:545:32)
    at tryModuleLoad (module.js:508:12)
    at Function.Module._load (module.js:500:3)
    at Module.require (module.js:568:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (/my-project/test/api/API.spec.ts:5:1)
    at Module._compile (module.js:624:30)
    at Module.m._compile (/my-project/node_modules/ts-node/src/index.ts:392:23)
    at Module._extensions..js (module.js:635:10)
    at Object.require.extensions.(anonymous function) [as .ts] (/my-project/node_modules/ts-node/src/index.ts:395:12)
    at Module.load (module.js:545:32)
    at tryModuleLoad (module.js:508:12)
    at Function.Module._load (module.js:500:3)
    at Module.require (module.js:568:17)
    at require (internal/module.js:11:18)
    at /my-project/node_modules/mocha/lib/mocha.js:230:27
    at Array.forEach (<anonymous>)
    at Mocha.loadFiles (/my-project/node_modules/mocha/lib/mocha.js:227:14)
    at Mocha.run (/my-project/node_modules/mocha/lib/mocha.js:495:10)
    at Object.<anonymous> (/my-project/node_modules/mocha/bin/_mocha:460:18)
    at Module._compile (module.js:624:30)
    at Object.Module._extensions..js (module.js:635:10)
    at Module.load (module.js:545:32)
    at tryModuleLoad (module.js:508:12)
    at Function.Module._load (module.js:500:3)
    at Function.Module.runMain (module.js:665:10)
    at startup (bootstrap_node.js:187:16)
    at bootstrap_node.js:607:3
```

Internally, it's looking for this `modifier.close` character in chalk and ansi-styles, which ends up being undefined, only when running ts-node and mocha.

**Comment by blakeembrey** [comment]
If you’d like to help close the last few issues I’ll be able to release ASAP. The last blocker is the breaking change ensuring you can’t double register. There’s also a task to move away from the current approach to node spawned children, but I can probably cut a v4 now and put both of these into a v5 instead.

**Comment by stelcheck** [comment]
FWIW, I'd really love to see #458 or #419 be part of that release. The related issue has been outstanding for months now, and I think it would be nice to finally be done with it.

**Comment by blakeembrey** [comment]
@stelcheck Thanks for your PRs. I'm looking into it now.
