### ISSUE TITLE
Throwing error makes all future code unreachable

### ISSUE THREAD

**Issue by crutchcorn** [TypeStrong/ts-node#469]
```
> throw new Error('Hi GH')
[eval].ts:2
throw new Error('Hi GH');
^

Error: Hi GH
    at [eval].ts:2:7
    at ContextifyScript.Script.runInContext (vm.js:59:29)
    at ContextifyScript.Script.runInNewContext (vm.js:65:15)
    at _eval (C:\Users\CorbinCrutchley\AppData\Roaming\npm\node_modules\ts-node\dist\_bin.js:181:29)
    at REPLServer.replEval (C:\Users\CorbinCrutchley\AppData\Roaming\npm\node_modules\ts-node\dist\_bin.js:220:18)
    at bound (domain.js:301:14)
    at REPLServer.runBound [as eval] (domain.js:314:12)
    at REPLServer.onLine (repl.js:441:10)
    at emitOne (events.js:116:13)
    at REPLServer.emit (events.js:211:7)
> let a = 5
Thrown: ⨯ Unable to compile TypeScript
[eval].ts (1,1): Unreachable code detected. (7027)
```

This behavior is not present in the `node` REPL.

**Comment by blakeembrey** [comment]
This is an unfortunate issue and I can’t see any way to fix it unless we can disable the unreachable code error. I’ll have to look into that but feel free to submit a PR.
