### ISSUE TITLE
ts-node isn't checking dependencies when cache is enabled

### ISSUE THREAD

**Issue by nicolaspeixoto** [TypeStrong/ts-node#546]
I have two files: 
a.ts:
```typescript
export const foo = {};
export const bar = {};
```

b.ts:
```typescript
import * as a from './a';

export function foobar() {
    Object.assign(a.foo, a.bar);
}
```

I'm running b.ts with ts-node. It's compiling and running.

if I comment line 1 on file a.ts:
```typescript
//export const foo = {};
export const bar = {};
```

I'm **not** getting the expected compilation error when I run ```ts-node``` again, but if I try to compile using ```tsc``` or run ```ts-node --no-cache``` I'm getting an error, what is **expected**.

**Comment by blakeembrey** [comment]
Enable type checking?

**Comment by nicolaspeixoto** [comment]
Yes, same result.
```bash
⋊> ~/w/a/issue on master ⨯ export TS_NODE_TYPE_CHECK=true                                                                                                                                           14:00:15
⋊> ~/w/a/issue on master ⨯ ts-node b.ts                                                                                                                                                             14:00:17
⋊> ~/w/a/issue on master ⨯ ts-node --no-cache b.ts                                                                                                                                                  14:00:21

/usr/local/lib/node_modules/ts-node/src/index.ts:300
        throw new TSError(formatDiagnostics(diagnosticList, cwd, ts, lineOffset))
              ^
TSError: ⨯ Unable to compile TypeScript
b.ts (4,21): Property 'foo' does not exist on type 'typeof "/Users/nsanto1/workspace/adp-e-meta/issue/a"'. (2339)
    at getOutput (/usr/local/lib/node_modules/ts-node/src/index.ts:300:15)
    at /usr/local/lib/node_modules/ts-node/src/index.ts:330:16
    at Object.compile (/usr/local/lib/node_modules/ts-node/src/index.ts:463:19)
    at Module.m._compile (/usr/local/lib/node_modules/ts-node/src/index.ts:382:43)
    at Module._extensions..js (module.js:646:10)
    at Object.require.extensions.(anonymous function) [as .ts] (/usr/local/lib/node_modules/ts-node/src/index.ts:385:12)
    at Module.load (module.js:554:32)
    at tryModuleLoad (module.js:497:12)
    at Function.Module._load (module.js:489:3)
    at Function.Module.runMain (module.js:676:10)
⋊> ~/w/a/issue on master ⨯
```

**Comment by blakeembrey** [comment]
@nicolaspeixoto What `ts-node` version are you using?

**Comment by blakeembrey** [comment]
I haven't been able to replicate the issue testing it locally. Might need something more reproducible. Can you output `ts-node -v` with and without type checking enabled? The only way this can happen is if the file somehow ended up in the cache so it's skipping compilation, but the `typeCheck` flag should be giving two separate cache paths.

![image](https://user-images.githubusercontent.com/1088987/36930889-d0535b1e-1e5f-11e8-9af1-e2f8143ceb49.png)
