### ISSUE TITLE
Readme out of date

### ISSUE THREAD

**Issue by SalchiPapa** [TypeStrong/ts-node#548]
![image](https://user-images.githubusercontent.com/4594825/36929812-b944775e-1e5b-11e8-93d3-d598dc1641b8.png)

```typescript
$ ts-node             
> const x = 10
undefined
> const y = 'foo'
undefined
> function add(x: number, y: number) {return x + y}
undefined
> add(x, y)
'10foo'
> .type x

/usr/local/google/home/vismael/.config/yarn/global/node_modules/ts-node/src/index.ts:264
    throw new TypeError(`Type information is unavailable without "--type-check"`)
          ^
TypeError: Type information is unavailable without "--type-check"
    at Object.getTypeInfo (/usr/local/google/home/vismael/.config/yarn/global/node_modules/ts-node/src/index.ts:264:11)
    at REPLServer.action (/usr/local/google/home/vismael/.config/yarn/global/node_modules/ts-node/src/bin.ts:259:13)
    at REPLServer.parseREPLKeyword (repl.js:1087:16)
    at REPLServer.onLine (repl.js:454:18)
    at emitOne (events.js:116:13)
    at REPLServer.emit (events.js:211:7)
    at REPLServer.Interface._onLine (readline.js:282:10)
    at REPLServer.Interface._line (readline.js:631:8)
    at REPLServer.Interface._ttyWrite (readline.js:911:14)
    at REPLServer.self._ttyWrite (repl.js:537:7)
```

I have to use `--type-check`, which is not the default as it would seem in the readme example, also `.type` return the value **not** the type! :warning: 

 ```typescript
$ ts-node --type-check
> const x = 10
undefined
> const y = 'foo'
undefined
> function add(x: number, y: number) {return x + y}
undefined
> add(x, y)
Thrown: ⨯ Unable to compile TypeScript
[eval].ts (1,8): Argument of type '"foo"' is not assignable to parameter of type 'number'. (2345)
> .type x
const x: 10
> .type y
const y: "foo"
> typeof x
'number'
> typeof y
'string'
```

**Comment by blakeembrey** [comment]
Actually, `'foo'` is a type. That screenshot is just from a long time ago before literal types even existed. I'll update it now.

**Comment by blakeembrey** [comment]
Closed with https://github.com/TypeStrong/ts-node/commit/a95357976c7e30b5d3305b12c0cecec817eddc75.
