### ISSUE TITLE
Strange issue on deployment

### ISSUE THREAD

**Issue by richtera** [TypeStrong/ts-node#572]
When running ts-node locally on my Mac it doesn't do quite as much type checking than it does when running the same version and the same code in production on my ubuntu docker. So far I have added --transpileOnly to allow the code to run, but it seems kind of "unexpected" to me.
Is there something that triggers full validation when it runs in production? (I am not passing NODE_ENV=production and it still behaves this way.)
So on the Mac it runs and inside of my ubuntu docker I get all kinds of type validation errors that even my local tslint doesn't pick up. 
Example:
```
Argument of type '(item: {}, key: {}) => {}' is not assignable to parameter of type '(value?: {}, key?: {}, iter?: Iterable<{}, {}>) => boolean'.
```
Even intelliJ with typescript errors shown is happy with the code:
![image](https://user-images.githubusercontent.com/708186/39066966-01673cb4-44a5-11e8-80ad-1a0e2b89d748.png)
That being said I know I have some typescript errors in my project, but if these are only showing up in production I really wouldn't know how to fix them 😀

**Comment by richtera** [comment]
I will double check but I am using the same yarn.lock file to install the two and I run it from node_modules/.bin/ts-node

**Comment by richtera** [comment]
Run locally from node_modules folder:
```sh
$ ./node_modules/.bin/ts-node -v
ts-node v6.0.0
node v9.11.1
typescript v2.8.3
cache "/var/folders/vp/5m13m6sx52g2y7zn2f006jdh0000gn/T/ts-node-983b73be61f86388086f613b41ddc072bf2bd77c6f8946071fc7a34836339289/2e5928f9135883c2c14f21697bb283e98ea573a4f4e605e8aadb6bdff0783695"
```
Running in docker from node_modules folder:
```sh
$ ./run.sh docker-bash
root@1f1e108a4bba:/run# node_modules/.bin/ts-node -v
ts-node v6.0.0
node v8.10.0
typescript v2.8.3
cache "/tmp/ts-node-94a6b447580330f9f2b609422537b04239ff3a39df9137e32efd559f1a2935cb/42fe92278947b83fc20f7a1dce1b84a902b10b390865f0e982ca91de690d2caf"
```
Running from within "npm run"
```sh
$ npm run ts-node-version
> ts-node -v

ts-node v6.0.0
node v9.11.1
typescript v2.8.3
cache "/var/folders/vp/5m13m6sx52g2y7zn2f006jdh0000gn/T/ts-node-983b73be61f86388086f613b41ddc072bf2bd77c6f8946071fc7a34836339289/2e5928f9135883c2c14f21697bb283e98ea573a4f4e605e8aadb6bdff0783695"
```

So I am seeing that there is a different version of node in the docker and outside but ts-node and typescript are the same version. Is it possible that the version of node can affect this?

**Comment by richtera** [comment]
oops clicked the wrong button.

**Comment by richtera** [comment]
I rebuilt the docker with v9.11 and still it has the same problem:
```sh
root@5ac0b140af27:/run# ./node_modules/.bin/ts-node -v
ts-node v6.0.0
node v9.11.1
typescript v2.8.3
cache "/tmp/ts-node-94a6b447580330f9f2b609422537b04239ff3a39df9137e32efd559f1a2935cb/42fe92278947b83fc20f7a1dce1b84a902b10b390865f0e982ca91de690d2caf"
```
Executing my node on the docker...
```javascript
./node_modules/.bin/ts-node www.tsx 
info: Connecting to ES at undefined using user undefined
info: Initializing firebase...

/run/node_modules/ts-node/src/index.ts:329
        throw new TSError(formatDiagnostics(diagnosticList, cwd, ts, lineOffset))
              ^
TSError: ⨯ Unable to compile TypeScript
src/shared/api/history.tsx (6088,110): Argument of type '(item: {}, key: {}) => {}' is not assignable to parameter of type '(value?: {}, key?: {}, iter?: Iterable<{}, {}>) => boolean'.
  Type '{}' is not assignable to type 'boolean'. (2345)
src/shared/api/history.tsx (6089,120): Argument of type '(item: {}, key: {}) => {}' is not assignable to parameter of type '(value?: {}, key?: {}, iter?: Iterable<{}, {}>) => boolean'.
  Type '{}' is not assignable to type 'boolean'. (2345)
    at getOutput (/run/node_modules/ts-node/src/index.ts:329:15)
    at Object.compile (/run/node_modules/ts-node/src/index.ts:515:11)
    at Module.m._compile (/run/node_modules/ts-node/src/index.ts:402:43)
    at Module._extensions..js (internal/modules/cjs/loader.js:665:10)
    at Object.require.extensions.(anonymous function) [as .tsx] (/run/node_modules/ts-node/src/index.ts:405:12)
    at Module.load (internal/modules/cjs/loader.js:566:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:506:12)
    at Function.Module._load (internal/modules/cjs/loader.js:498:3)
    at Module.require (internal/modules/cjs/loader.js:598:17)
    at require (internal/modules/cjs/helpers.js:11:18)
```
Executing it locally the same way locally:
```sh
$ ./node_modules/.bin/ts-node www.tsx
info: Connecting to ES at https://7aab2e38150624f479534383ce7dd507.us-central1.gcp.cloud.es.io:9243 using user elastic
info: Initializing firebase...
info: mounting /teach and /teach/index.html as teach/index.html
info: mounting / and /index.html as login_app/index.html
info: mounting /create and /create/index.html as create/index.html
info: mounting /pimsleur and /pimsleur/index.html as pimsleur/index.html
info: mounting /learn and /learn/index.html as learn/index.html
info: mounting /organize and /organize/index.html as organize/index.html
info: mounting /manage and /manage/index.html as manage/index.html
info: mounting /teach* as teach/index.html
info: mounting /create* as create/index.html
info: mounting /pimsleur* as pimsleur/index.html
info: mounting /learn* as learn/index.html
info: mounting /organize* as organize/index.html
info: mounting /manage* as manage/index.html
info: mounting * as login_app/index.html
info: app listening on 3003
```
I am not quite sure what to look at but I will look at src/index.ts:329 to see if anything makes sense.

**Comment by richtera** [comment]
I don't have any TS_NODE_* env variables on either platform. I was hoping I did; this is perplexing me.

**Comment by richtera** [comment]
My docker env contains these env variables:
```
GOOGLE_CLIENT_CERT_URL
NODE_VERSION
EMAIL_BCC
GOOGLE_PROJECT_ID
SENDGRID_API_KEY
WINSTON_LEVEL
HOSTNAME
TERM
KEYMETRICS_PUBLIC
GOOGLE_PRIVATE_KEY
GOOGLE_PRIVATE_KEY_ID
GOOGLE_TOKEN_URI
RIEVENT_PRIVATE_KEY
FIREBASE_DATABASE_URL
STRIPE_SECRET
FIREBASE_MESSAGING_SENDER_ID
STRIPE_SK
GOOGLE_AUTH_URI
FIREBASE_STORAGE_BUCKET
EMAIL_TO
GOOGLE_AUTH_PROVIDER_CERT_URL
PATH
FIREBASE_API_KEY
VERSION_STAMP
REPLY_TO
PWD
SUBDOMAIN
TLS_KEY
FIREBASE_AUTH_DOMAIN
RIEVENT_PUBLIC_KEY
DOMAIN
EMAIL_SUBJECT
EMAIL_FROM
GOOGLE_CLIENT_EMAIL
SHLVL
HOME
STRIPE_PK
YARN_VERSION
PYAPI_PORT
RIEVENT_USERNAME
KEYMETRICS_MACHINE
KEYMETRICS_SECRET
TLS_CERT
REACTOR_DEBUG
RIEVENT_PASSWORD
PYAPI_EXTERN
GOOGLE_CLIENT_ID
```
My local has a bit more.
```
MACHINE_ZONE
GOOGLE_CLIENT_CERT_URL
EMAIL_BCC
GOOGLE_PROJECT_ID
RAYGUN_APP
WINSTON_LEVEL
SENDGRID_API_KEY
TERM_PROGRAM
NVM_CD_FLAGS
CRON_NAME
ES_URL
REPLICATION_COUNT
TERM
SHELL
INGRESS_VARIATION
TMPDIR
GOOGLE_PRIVATE_KEY
DOCKER_HOST
Apple_PubSub_Socket_Render
TERM_PROGRAM_VERSION
RAYGUN_API_KEY
GOOGLE_PRIVATE_KEY_ID
ALL_NAMES
CLUSTER_NAME
TERM_SESSION_ID
GOOGLE_TOKEN_URI
RIEVENT_PRIVATE_KEY
NVM_DIR
USER
CONFIGMAP_NAME
FIREBASE_DATABASE_URL
GITHUB_REPO
DOCKER_MACHINE_NAME
ES_VERS
STRIPE_SECRET
FIREBASE_MESSAGING_SENDER_ID
SSH_AUTH_SOCK
SECRETS_NAME
STRIPE_SK
GOOGLE_AUTH_URI
ES_USER
MACHINE_TYPE
FIREBASE_STORAGE_BUCKET
DOCKER_TLS_VERIFY
KEYRING
ES_PASS
EMAIL_TO
GOOGLE_AUTH_PROVIDER_CERT_URL
PATH
PDFLAYER_ACCESS_KEY
FIREBASE_API_KEY
PROJECT_NAME
REPLY_TO
PWD
SUBDOMAIN
DBUS_LAUNCHD_SESSION_BUS_SOCKET
RIEVENT_PUBLIC_KEY
FIREBASE_AUTH_DOMAIN
TLS_KEY
DOMAIN
LANG
SERVICE_NAME
EMAIL_SUBJECT
REPO_PROJECT
EMAIL_FROM
XPC_FLAGS
GOOGLE_CLIENT_EMAIL
XPC_SERVICE_NAME
STRIPE_PK
DOCKER_CERT_PATH
HOME
SHLVL
RIEVENT_USERNAME
RAYGUN_TOKEN
REPO_VERSION
HEAP_ID
SENTRY_ORG
LOGNAME
TLS_CERT
REACTOR_DEBUG
GOPATH
NVM_BIN
SENTRY_PROJ
RIEVENT_PASSWORD
RAYGUN_SOURCEMAP_AUTH
SECURITYSESSIONID
SITE_CONFIG
MACHINE_COUNT
GOOGLE_CLIENT_ID
```

None of them seem related to typescript or ts-node.

**Comment by sanketCactus** [comment]
Similar thing happened to me when I use ts-node there is no strict type checking but when I compile same files with tsc it gives type errors.
Any specific reason?

**Comment by cspotcode** [comment]
I'm going to close this issue because, as far as I can tell, it's missing the information we need to either fix bugs or help users solve a problem they're having.

We can always reopen this ticket if I'm wrong -- closing is not permanent -- and users are always welcome to open new tickets.
