### ISSUE TITLE
DeprecationWarning: The Buffer() and new Buffer() constructors are not recommended

### ISSUE THREAD

**Issue by dex4er** [TypeStrong/ts-node#587]
Hi,

With `NODE_OPTIONS='--pending-deprecation --throw-deprecation'` and Node 10:

```
DeprecationWarning: The Buffer() and new Buffer() constructors are not recommended for use due to security and usability concerns. Please use the new Buffer.alloc(), Buffer.allocUnsafe(), or Buffer.from() construction methods instead.
    at showFlaggedDeprecation (buffer.js:127:13)
    at new Buffer (buffer.js:148:3)
    at updateOutput (/Users/dexter/src/project/node_modules/ts-node/src/index.ts:530:21)
    at Object.compile (/Users/dexter/src/project/node_modules/ts-node/src/index.ts:517:20)
    at Module.m._compile (/Users/dexter/src/project/node_modules/ts-node/src/index.ts:403:43)
    at Module._extensions..js (module.js:663:10)
    at Object.require.extensions.(anonymous function) [as .ts] (/Users/dexter/src/project/node_modules/ts-node/src/index.ts:406:12)
    at Module.load (module.js:565:32)
    at tryModuleLoad (module.js:505:12)
    at Function.Module._load (module.js:497:3)
```

**Comment by blakeembrey** [comment]
Closed with https://github.com/TypeStrong/ts-node/commit/4f400269036bd569d5a7b25c9ff5e945ad37c243.
