### ISSUE TITLE
ts-node crashing without stacktrace

### ISSUE THREAD

**Issue by francocorreasosa** [TypeStrong/ts-node#593]
Hey guys 👋 

I'm currently trying to run a project that compiles with no problem with `tsc` but it crashes with `ts-node` like this:
```bash
$ ts-node core/server.ts
error An unexpected error occurred: "Command failed.
Exit code: 1
Command: sh
Arguments: -c ts-node core/server.ts
Output:
".
info If you think this is a bug, please open a bug report with the information provided in "/<absolute>/yarn-error.log".
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```

I'm running it with `ts-node core/server.ts`. Am I doing something wrong? Thanks.

**Comment by blakeembrey** [comment]
Can you share a reproduction or even the error if you run it without Yarn? There’s no information there that I can use to help you. Even the module version would help here.

**Comment by francocorreasosa** [comment]
Sure, sorry:
```
$ npm start

> fcs-forms-core@0.0.1 start <directory>
> ts-node core/server.ts

npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! fcs-forms-core@0.0.1 start: `ts-node core/server.ts`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the fcs-forms-core@0.0.1 start script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/francocorrea/.npm/_logs/2018-05-21T22_51_33_953Z-debug.log
```

and the `npm-error.log`:

```
0 info it worked if it ends with ok
1 verbose cli [ '/Users/<username>/.nvm/versions/node/v8.9.4/bin/node',
1 verbose cli   '/Users/<username>/.nvm/versions/node/v8.9.4/bin/npm',
1 verbose cli   'run',
1 verbose cli   'start' ]
2 info using npm@5.6.0
3 info using node@v8.9.4
4 verbose run-script [ 'prestart', 'start', 'poststart' ]
5 info lifecycle project-name@0.0.1~prestart: project-name@0.0.1
6 info lifecycle project-name@0.0.1~start: project-name@0.0.1
7 verbose lifecycle project-name@0.0.1~start: unsafe-perm in lifecycle true
8 verbose lifecycle project-name@0.0.1~start: PATH: /Users/<username>/.nvm/versions/node/v8.9.4/lib/node_modules/npm/node_modules/npm-lifecycle/node-gyp-bin:/Users/<username>/Code/project-name/node_modules/.bin:/Users/<username>/.sdkman/candidates/grails/current/bin:/Users/<username>/.rbenv/shims:/Users/<username>/.bin:/Users/<username>/.nvm/versions/node/v8.9.4/bin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/usr/local/share/dotnet:/Library/Frameworks/Mono.framework/Versions/Current/Commands:/Applications/Xamarin Workbooks.app/Contents/SharedSupport/path-bin:/Users/<username>/go/bin:/usr/local/opt/go/libexec/bin
9 verbose lifecycle project-name@0.0.1~start: CWD: /Users/<username>/Code/project-name
10 silly lifecycle project-name@0.0.1~start: Args: [ '-c', 'ts-node core/server.ts' ]
11 silly lifecycle project-name@0.0.1~start: Returned: code: 1  signal: null
12 info lifecycle project-name@0.0.1~start: Failed to exec start script
13 verbose stack Error: project-name@0.0.1 start: `ts-node core/server.ts`
13 verbose stack Exit status 1
13 verbose stack     at EventEmitter.<anonymous> (/Users/<username>/.nvm/versions/node/v8.9.4/lib/node_modules/npm/node_modules/npm-lifecycle/index.js:285:16)
13 verbose stack     at emitTwo (events.js:126:13)
13 verbose stack     at EventEmitter.emit (events.js:214:7)
13 verbose stack     at ChildProcess.<anonymous> (/Users/<username>/.nvm/versions/node/v8.9.4/lib/node_modules/npm/node_modules/npm-lifecycle/lib/spawn.js:55:14)
13 verbose stack     at emitTwo (events.js:126:13)
13 verbose stack     at ChildProcess.emit (events.js:214:7)
13 verbose stack     at maybeClose (internal/child_process.js:925:16)
13 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:209:5)
14 verbose pkgid project-name@0.0.1
15 verbose cwd /Users/<username>/Code/project-name
16 verbose Darwin 17.0.0
17 verbose argv "/Users/<username>/.nvm/versions/node/v8.9.4/bin/node" "/Users/<username>/.nvm/versions/node/v8.9.4/bin/npm" "run" "start"
18 verbose node v8.9.4
19 verbose npm  v5.6.0
20 error code ELIFECYCLE
21 error errno 1
22 error project-name@0.0.1 start: `ts-node core/server.ts`
22 error Exit status 1
23 error Failed at the project-name@0.0.1 start script.
23 error This is probably not a problem with npm. There is likely additional logging output above.
24 verbose exit [ 1, true ]
```

**Comment by francocorreasosa** [comment]
Apparently my code reached a `process.exit(1)` error, so that's what happened. There's not a `ts-node` problem. Thank you!
