### ISSUE TITLE
ts-node fails when invoked with webpack-dev-server

### ISSUE THREAD

**Issue by ljani** [TypeStrong/ts-node#595]
In my testing `ts-node` fails to properly parse `tsconfig.json` if it's invoked in combination with `webpack-dev-server`.

To reproduce run these commands *on Windows*:

```
git clone https://github.com/ljani/ts-node-issue-595.git
cd ts-node-issue-595
npm install
npm run test-ok-1
npm run test-fail-1
npm run test-fail-2
```

Expected output is:

```
[Function: Promise]
```

Actual output for the fails are:
```
TSError: Ô¿» Unable to compile TypeScript
webpackfile.ts (1,13): 'Promise' only refers to a type, but is being used as a value here. (2693)
    at getOutput (...\ts-node-issue-595\node_modules\ts-node\src\index.ts:330:15)
    at Object.compile (...\ts-node-issue-595\node_modules\ts-node\src\index.ts:516:11)
    at Module.m._compile (...\ts-node-issue-595\node_modules\ts-node\src\index.ts:403:43)
    at Module._extensions..js (internal/modules/cjs/loader.js:689:10)
    at Object.require.extensions.(anonymous function) [as .ts] (...\ts-node-issue-595\node_modules\ts-node\src\index.ts:406:12)
    at Module.load (internal/modules/cjs/loader.js:589:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:528:12)
    at Function.Module._load (internal/modules/cjs/loader.js:520:3)
    at Module.require (internal/modules/cjs/loader.js:626:17)
    at require (internal/modules/cjs/helpers.js:20:18)
```

and

```
TSError: Ô¿» Unable to compile TypeScript
webpackfile.ts: Cannot find name 'console'. (2304)
webpackfile.ts (2,1): Cannot find name 'process'. (2304)
    at getOutput (...\ts-node-issue-595\node_modules\ts-node\src\index.ts:330:15)
    at Object.compile (...\ts-node-issue-595\node_modules\ts-node\src\index.ts:516:11)
    at Module.m._compile (...\ts-node-issue-595\node_modules\ts-node\src\index.ts:403:43)
    at Module._extensions..js (internal/modules/cjs/loader.js:689:10)
    at require.extensions.(anonymous function) (...\ts-node-issue-595\node_modules\ts-node\src\index.ts:406:12)
    at Object.require.extensions.(anonymous function) [as .ts] (...\ts-node-issue-595\node_modules\ts-node\src\index.ts:406:12)
    at Module.load (internal/modules/cjs/loader.js:589:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:528:12)
    at Function.Module._load (internal/modules/cjs/loader.js:520:3)
    at Module.require (internal/modules/cjs/loader.js:626:17)
```

Everything works if I specify `TS_NODE_PROJECT` environment variable though.

EDIT: If it makes any difference, I'm on Windows:

```
ts-node-issue-595 ❯❯❯ npm -v
6.0.1
ts-node-issue-595 ❯❯❯ node -v
v10.1.0
```

**Comment by blakeembrey** [comment]
Thanks for the awesome reproduction. 

The first failure looks like it should be correct, you're running in a different directory so it won't find `tsconfig.json` automatically. This might need an update to the README to clarify though.

Interestingly these all worked fine for me:

![image](https://user-images.githubusercontent.com/1088987/40408374-82cb814c-5e91-11e8-9dd6-3cd9287714c5.png)

Could it be related to `webpack-dev-server` doing something with registering `ts-node` for you? I haven't looked into it.

**Comment by ljani** [comment]
Thank you for the fast reply!

> The first failure looks like it should be correct, you're running in a different directory so it won't find tsconfig.json automatically. This might need an update to the README to clarify though.

I thought `tsconfig.json` was supposed to be searched in parent directories as [`tsc` does this](https://www.typescriptlang.org/docs/handbook/tsconfig-json.html):

> By invoking tsc with no input files, in which case the compiler searches for the tsconfig.json file starting in the current directory and continuing up the parent directory chain.

Why shouldn't `ts-node` search parent directories until it finds one?

> Interestingly these all worked fine for me:

Hmm, this might be a Windows issue, because I ran the tests in a Docker container as well and they're okay.

**Comment by ljani** [comment]
So, I booted a fresh Windows 10 VM (you can get one [here](https://developer.microsoft.com/en-us/microsoft-edge/tools/vms/)), installed Node v10 and I can reproduce the issue there. Thus this is definitely a Windows issue.

> Could it be related to webpack-dev-server doing something with registering ts-node for you? I haven't looked into it.

`webpack` registers `ts-node` via [`js-interpret`](https://github.com/js-cli/js-interpret) when it finds a `.ts` file as far as I know (although [the docs say it's `node-interpret`](https://webpack.js.org/configuration/configuration-languages/)). Could this be related to #409 then? But that doesn't explain the difference between Windows and Linux/Mac.

**Comment by ljani** [comment]
I tried to play with the `register` function in `node_modules/ts-node/dist/index.js` and I made two observations. This does nott help the issue

```js
let skipReg = 0;
function register(opts) {
    console.log("aa" + skipReg);
    if (skipReg) {
        console.log("skipping reg");
        return;
    }
    console.log("registering");
    skipReg = 1;
    ...
```

But this will make the tests pass, but I have no idea why:

```js
function register(opts) {
    return;
}
```

**Comment by blakeembrey** [comment]
Closed with https://github.com/TypeStrong/ts-node/pull/596.
