### ISSUE TITLE
Compilation problem with Material UI Tooltip

### ISSUE THREAD

**Issue by tashburn** [TypeStrong/ts-node#603]
# Bug report

## Describe the bug

There seems to be something wrong with how `ts-node` compiles part of `material-ui`.

I've combined these canonical examples --

- https://github.com/zeit/next.js/tree/canary/examples/with-typescript
- https://github.com/zeit/next.js/tree/canary/examples/custom-server-express
- https://github.com/mui-org/material-ui/tree/master/examples/nextjs

-- into the repo https://github.com/tashburn/issue-tooltip

If you run `yarn dev`, which uses `ts-node`, you can see the error below.

If you transpile the typescript into JS with `yarn build` and then run it with `yarn start`, it works fine (from the `.next` folder).

If you transpile the typescript with `tsc` (after `npm install typescript@next -g`), it puts the JS into the `build` folder. If you `cd build` and `node server.js`, it works fine.

This is the error --

```
ModuleNotFoundError: Module not found: Error: [CaseSensitivePathsPlugin] `/Users/trent/home/projects/Grok/tmp/issue-tooltip/node_modules/react-popper/lib/popper.js` does not match the corresponding path on disk `Popper.js`.
    at factoryCallback (/Users/trent/home/projects/Grok/tmp/issue-tooltip/node_modules/webpack/lib/Compilation.js:276:40)
    at factory (/Users/trent/home/projects/Grok/tmp/issue-tooltip/node_modules/webpack/lib/NormalModuleFactory.js:235:20)
    at applyPluginsAsyncWaterfall (/Users/trent/home/projects/Grok/tmp/issue-tooltip/node_modules/webpack/lib/NormalModuleFactory.js:70:21)
    at /Users/trent/home/projects/Grok/tmp/issue-tooltip/node_modules/tapable/lib/Tapable.js:265:18
    at that.fileExistsWithCase (/Users/trent/home/projects/Grok/tmp/issue-tooltip/node_modules/case-sensitive-paths-webpack-plugin/index.js:156:15)
    at that.getFilenamesInDir (/Users/trent/home/projects/Grok/tmp/issue-tooltip/node_modules/case-sensitive-paths-webpack-plugin/index.js:97:7)
    at CaseSensitivePathsPlugin.getFilenamesInDir (/Users/trent/home/projects/Grok/tmp/issue-tooltip/node_modules/case-sensitive-paths-webpack-plugin/index.js:47:5)
    at CaseSensitivePathsPlugin.fileExistsWithCase (/Users/trent/home/projects/Grok/tmp/issue-tooltip/node_modules/case-sensitive-paths-webpack-plugin/index.js:85:8)
    at that.primeCache (/Users/trent/home/projects/Grok/tmp/issue-tooltip/node_modules/case-sensitive-paths-webpack-plugin/index.js:150:14)
    at CaseSensitivePathsPlugin.primeCache (/Users/trent/home/projects/Grok/tmp/issue-tooltip/node_modules/case-sensitive-paths-webpack-plugin/index.js:116:5)
    at NormalModuleFactory.nmf.plugin (/Users/trent/home/projects/Grok/tmp/issue-tooltip/node_modules/case-sensitive-paths-webpack-plugin/index.js:145:12)
    at NormalModuleFactory.applyPluginsAsyncWaterfall (/Users/trent/home/projects/Grok/tmp/issue-tooltip/node_modules/tapable/lib/Tapable.js:272:13)
    at resolver (/Users/trent/home/projects/Grok/tmp/issue-tooltip/node_modules/webpack/lib/NormalModuleFactory.js:69:10)
    at process.nextTick (/Users/trent/home/projects/Grok/tmp/issue-tooltip/node_modules/webpack/lib/NormalModuleFactory.js:194:7)
    at process._tickCallback (internal/process/next_tick.js:112:11)
ModuleNotFoundError: Module not found: Error: [CaseSensitivePathsPlugin] `/Users/trent/home/projects/Grok/tmp/issue-tooltip/node_modules/react-popper/lib/popper.js` does not match the corresponding path on disk `Popper.js`.
    at factoryCallback (/Users/trent/home/projects/Grok/tmp/issue-tooltip/node_modules/webpack/lib/Compilation.js:276:40)
    at factory (/Users/trent/home/projects/Grok/tmp/issue-tooltip/node_modules/webpack/lib/NormalModuleFactory.js:235:20)
    at applyPluginsAsyncWaterfall (/Users/trent/home/projects/Grok/tmp/issue-tooltip/node_modules/webpack/lib/NormalModuleFactory.js:70:21)
    at /Users/trent/home/projects/Grok/tmp/issue-tooltip/node_modules/tapable/lib/Tapable.js:265:18
    at that.fileExistsWithCase (/Users/trent/home/projects/Grok/tmp/issue-tooltip/node_modules/case-sensitive-paths-webpack-plugin/index.js:156:15)
    at that.getFilenamesInDir (/Users/trent/home/projects/Grok/tmp/issue-tooltip/node_modules/case-sensitive-paths-webpack-plugin/index.js:97:7)
    at CaseSensitivePathsPlugin.getFilenamesInDir (/Users/trent/home/projects/Grok/tmp/issue-tooltip/node_modules/case-sensitive-paths-webpack-plugin/index.js:47:5)
    at CaseSensitivePathsPlugin.fileExistsWithCase (/Users/trent/home/projects/Grok/tmp/issue-tooltip/node_modules/case-sensitive-paths-webpack-plugin/index.js:85:8)
    at that.primeCache (/Users/trent/home/projects/Grok/tmp/issue-tooltip/node_modules/case-sensitive-paths-webpack-plugin/index.js:150:14)
    at CaseSensitivePathsPlugin.primeCache (/Users/trent/home/projects/Grok/tmp/issue-tooltip/node_modules/case-sensitive-paths-webpack-plugin/index.js:116:5)
    at NormalModuleFactory.nmf.plugin (/Users/trent/home/projects/Grok/tmp/issue-tooltip/node_modules/case-sensitive-paths-webpack-plugin/index.js:145:12)
    at NormalModuleFactory.applyPluginsAsyncWaterfall (/Users/trent/home/projects/Grok/tmp/issue-tooltip/node_modules/tapable/lib/Tapable.js:272:13)
    at resolver (/Users/trent/home/projects/Grok/tmp/issue-tooltip/node_modules/webpack/lib/NormalModuleFactory.js:69:10)
    at process.nextTick (/Users/trent/home/projects/Grok/tmp/issue-tooltip/node_modules/webpack/lib/NormalModuleFactory.js:194:7)
    at process._tickCallback (internal/process/next_tick.js:112:11)


 ERROR  Failed to compile with 1 errors                                                                    13:45:07

This dependency was not found:

* popper.js in ./node_modules/react-popper/lib/Popper.js

To install it, you can run: npm install --save popper.js
```

The error might indicate some sort of casing problem.

## To Reproduce

1. `git clone https://github.com/tashburn/issue-tooltip`
2. `cd issue-tooltip`
3. `yarn install`
4. `yarn run dev` 
5. Go to http://localhost:3000. *It will fail.*
6. ^C to stop the server
7. `yarn build`
8. `yarn start`
9. Go to http://localhost:3000. *It will work.*

## System information
 - OS: macOS
 - Version of ts-node: 6.1.0
 - Version of Next.js: 6.0.3
 - Version of Material UI: 1.2.0
 - Version of Typescript: 2.9.1

**Comment by blakeembrey** [comment]
Why do you suspect `ts-node`? It looks like, from the error, it's webpack configuration to detect case issues.

**Comment by tashburn** [comment]
@blakeembrey I suspected `ts-node` because it works fine to bypass it by transpiling to typescript with `tsc` and running the JS. However, I've since found that the issue is not `ts-node`. When I entirely remove Typescript from the repo, I still get the issue.

Replacing my `package.json` script `NODE_PATH=. node server.js` with `node server.js` makes it work fine. Except I want `NODE_PATH=.` for absolute imports. I'm not sure how to track this down further, but it's not `ts-node`. Sorry for accusing `ts-node`!

**Comment by blakeembrey** [comment]
Confirmed. This is unrelated to `ts-node` and reproducible if you use `node`. Don't use `NODE_PATH` if you aren't sure what it does.

**Comment by blakeembrey** [comment]
Looks like it may be an issue (or even correct?) in Webpack. It appears to be using `NODE_PATH` literally, so every time it's resolving it uses `.`. So when resolving `popper.js` it finds the relative file `Popper.js` and that plugin errors because the case is different. You can work around this with `NODE_PATH=$(pwd)`, but I'd recommend you don't use `NODE_PATH` and instead use tooling in Webpack that already supports your use-case.

**Comment by tashburn** [comment]
Thanks for your ideas.
