### ISSUE TITLE
Error running in Node 5.9.1

### ISSUE THREAD

**Issue by burnnat** [TypeStrong/ts-node#608]
The `package.json` indicates that Node.js is supported back to version 4.2:
```
  "engines": {
    "node": ">=4.2.0"
  },
```

However, attempting to run with node 5.9.1 I get the following error:
```
TypeError: utf8 is not a function
    at Function.from (native)
    at Function.from (native)
    at updateOutput (C:\project\src\main\scripts\node_modules\ts-node\src\index.ts:559:28)
    at Object.compile (C:\project\src\main\scripts\node_modules\ts-node\src\index.ts:546:20)
    at Module.m._compile (C:\project\src\main\scripts\node_modules\ts-node\src\index.ts:430:43)
    at Module._extensions..js (module.js:422:10)
    at Object.require.extensions.(anonymous function) [as .ts] (C:\project\src\main\scripts\node_modules\ts-node\src\index.ts:433:12)
    at Module.load (module.js:357:32)
    at Function.Module._load (module.js:314:12)
    at Function.Module.runMain (module.js:447:10)
```

The problematic change appears to be [this commit](https://github.com/TypeStrong/ts-node/commit/4f400269036bd569d5a7b25c9ff5e945ad37c243), as `Buffer.from(string[, encoding])` was only introduced in [Node 5.10.0](https://nodejs.org/api/buffer.html#buffer_class_method_buffer_from_string_encoding).

**Comment by blakeembrey** [comment]
Feel free to update the `package.json` :+1:

**Comment by burnnat** [comment]
Well given I'm locked into this version of node for the time being (not of my own choice), I was hoping there would be a way to maintain compatibility... 😐

That said, I'm happy to update the `package.json` if 5.9 is too old for support at this point.

**Comment by blakeembrey** [comment]
You could replace `Buffer.from` with https://www.npmjs.com/package/buffer-from instead, if you'd like to submit that PR.
