### ISSUE TITLE
error TS2339: Property does not exist

### ISSUE THREAD

**Issue by carvalhoviniciusluiz** [TypeStrong/ts-node#646]
Hello
I am developing a project using node-ts and jest but when executing the test command I get an error. I noticed that this error only happens in the test environment. I do not know what can be happening so I am reporting, to facilitate I published a test project that has the same error at the following address

https://github.com/carvalhoviniciusluiz/app-api

**Comment by blakeembrey** [comment]
Can you share the error message?

**Comment by carvalhoviniciusluiz** [comment]
Apparently, the ts-node is not finding the index.d.ts file at the root of the project

```js
$ npm test
 
> api@1.0.0 test ~/cursos/api
> ts-node jest.startup.ts
 
 
~/cursos/api/node_modules/ts-node/src/index.ts:261
    return new TSError(diagnosticText, diagnosticCodes)
           ^
TSError: ⨯ Unable to compile TypeScript:
security/token.parser.ts(33,17): error TS2339: Property 'authenticated' does not exist on type 'Request'.
 
    at createTSError (~/cursos/api/node_modules/ts-node/src/index.ts:261:12)
    at getOutput (~/cursos/api/node_modules/ts-node/src/index.ts:367:40)
    at Object.compile (~/cursos/api/node_modules/ts-node/src/index.ts:557:11)
    at Module.m._compile (~/cursos/api/node_modules/ts-node/src/index.ts:439:43)
    at Module._extensions..js (internal/modules/cjs/loader.js:700:10)
    at Object.require.extensions.(anonymous function) [as .ts] (~/cursos/api/node_modules/ts-node/src/index.ts:442:12)
    at Module.load (internal/modules/cjs/loader.js:599:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:538:12)
    at Function.Module._load (internal/modules/cjs/loader.js:530:3)
    at Module.require (internal/modules/cjs/loader.js:637:17)
    at require (internal/modules/cjs/helpers.js:20:18)
    at Object.<anonymous> (~/cursos/api/server/server.ts:8:1)
    at Module._compile (internal/modules/cjs/loader.js:689:30)
    at Module.m._compile (~/cursos/api/node_modules/ts-node/src/index.ts:439:23)
    at Module._extensions..js (internal/modules/cjs/loader.js:700:10)
    at Object.require.extensions.(anonymous function) [as .ts] (~/cursos/api/node_modules/ts-node/src/index.ts:442:12)
npm ERR! Test failed.  See above for more details.
```

I was able to solve by changing the path from index.d.ts to another path, in my case types/default/index.d.ts

````js
// tsconfig.json
{
  "compilerOptions": {
    "typeRoots": [
      "./types"
    ],
    "types": [
      "default"
    ],
    "outDir": "dist",
    "target": "es2015",
    "module": "commonjs"
  },
  "exclude": [
    "**/*.test.ts"
  ]
}

````

**Comment by blakeembrey** [comment]
I see, thanks. There is a section documented in the README for this, let me know if it is not clear or could be improved!
