### ISSUE TITLE
Mocha tests not running because of folder name or structure

### ISSUE THREAD

**Issue by ArthurianX** [TypeStrong/ts-node#650]
Hey guys, I've been debugging this for the past three days and I'm at the end of my rope.

I'm not 100% it's a ts-node (`7.0`) issue, but this happened 'all of a sudden', the story goes like this:

- have a `observations` folder with `observations.controller.ts`, `observations.controller.spec.ts` and `observations.view.html`
- mocha tests fail, command is 
```
"test": "NODE_ENV=test TS_NODE_SKIP_PROJECT=YES TS_NODE_COMPILER_OPTIONS='{\"module\":\"commonjs\", \"baseUrl\":\".\", \"typeRoots\": [\"./node_modules/@types\"], \"moduleResolution\": \"node\", \"target\": \"ES6\", \"sourceMap\": true, \"inlineSourceMap\": true}' ./node_modules/nyc/bin/nyc.js ./node_modules/mocha/bin/mocha --timeout=3000 'app/scripts/**/*.spec.ts'",
```
- `mocha.opts`:
```
--require ts-node/register
--require source-map-support/register
--require ignore-styles
--require jsdom-global/register
--full-trace
--bail
```

It's an angular 1 app, written in TypeScript, tested with mocha tests written in TypeScript, **the tests fail at `observations.controller.ts`,** module not found err:
```
publisher@0.0.0 test /my-folder/structure/project
> NODE_ENV=test TS_NODE_SKIP_PROJECT=YES TS_NODE_COMPILER_OPTIONS='{"module":"commonjs", "baseUrl":".", "typeRoots": ["./node_modules/@types"], "moduleResolution": "node", "target": "ES6", "sourceMap": true, "inlineSourceMap": true}' ./node_modules/nyc/bin/nyc.js ./node_modules/mocha/bin/mocha --timeout=3000 'app/scripts/**/*.spec.ts'


/my-folder/structure/project/node_modules/angular/angular.js:2192
    return obj[name] || (obj[name] = factory());
                                     ^
Error: [$injector:nomod] Module 'mida.client' is not available! You either misspelled the module name or forgot to load it. If registering a module ensure that you specify the dependencies as the second argument.
https://errors.angularjs.org/1.7.0/$injector/nomod?p0=mida.client
    at /my-folder/structure/project/node_modules/angular/angular.js:125:12
    at /my-folder/structure/project/node_modules/angular/angular.js:2271:17
    at ensure (/my-folder/structure/project/node_modules/angular/angular.js:2192:38)
    at Object.module (/my-folder/structure/project/node_modules/angular/angular.js:2269:14)
    at Object.<anonymous> (/my-folder/structure/project/app/scripts/components/observations/observations.controller.ts:61:23)
    at Module._compile (module.js:652:30)
    at Module.replacementCompile (/my-folder/structure/project/node_modules/nyc/node_modules/append-transform/index.js:58:13)
    at Module.m._compile (/my-folder/structure/project/node_modules/ts-node/src/index.ts:439:23)
    at module.exports (/my-folder/structure/project/node_modules/nyc/node_modules/default-require-extensions/js.js:8:9)
    at /my-folder/structure/project/node_modules/nyc/node_modules/append-transform/index.js:62:4
    at require.extensions.(anonymous function) (/my-folder/structure/project/node_modules/ts-node/src/index.ts:442:12)
    at Object.<anonymous> (/my-folder/structure/project/node_modules/nyc/node_modules/append-transform/index.js:62:4)
    at Module.load (module.js:565:32)
    at tryModuleLoad (module.js:505:12)
    at Function.Module._load (module.js:497:3)
    at Module.require (module.js:596:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (/my-folder/structure/project/app/scripts/components/observations/observations.controller.spec.ts:6:1)
    at Module._compile (module.js:652:30)
    at Module.replacementCompile (/my-folder/structure/project/node_modules/nyc/node_modules/append-transform/index.js:58:13)
    at Module.m._compile (/my-folder/structure/project/node_modules/ts-node/src/index.ts:439:23)
    at module.exports (/my-folder/structure/project/node_modules/nyc/node_modules/default-require-extensions/js.js:8:9)
    at /my-folder/structure/project/node_modules/nyc/node_modules/append-transform/index.js:62:4
    at require.extensions.(anonymous function) (/my-folder/structure/project/node_modules/ts-node/src/index.ts:442:12)
    at Object.<anonymous> (/my-folder/structure/project/node_modules/nyc/node_modules/append-transform/index.js:62:4)
    at Module.load (module.js:565:32)
    at tryModuleLoad (module.js:505:12)
    at Function.Module._load (module.js:497:3)
    at Module.require (module.js:596:17)
    at require (internal/module.js:11:18)
    at /my-folder/structure/project/node_modules/mocha/lib/mocha.js:250:27
    at Array.forEach (<anonymous>)
    at Mocha.loadFiles (/my-folder/structure/project/node_modules/mocha/lib/mocha.js:247:14)
    at Mocha.run (/my-folder/structure/project/node_modules/mocha/lib/mocha.js:576:10)
    at Object.<anonymous> (/my-folder/structure/project/node_modules/mocha/bin/_mocha:637:18)
    at Module._compile (module.js:652:30)
    at Module.replacementCompile (/my-folder/structure/project/node_modules/nyc/node_modules/append-transform/index.js:58:13)
    at module.exports (/my-folder/structure/project/node_modules/nyc/node_modules/default-require-extensions/js.js:8:9)
    at Object.<anonymous> (/my-folder/structure/project/node_modules/nyc/node_modules/append-transform/index.js:62:4)
    at Module.load (module.js:565:32)
    at tryModuleLoad (module.js:505:12)
    at Function.Module._load (module.js:497:3)
    at Function.Module.runMain (module.js:693:10)
    at runMain (/Users/arthur/.node-spawn-wrap-19073-3b48967770f6/node:68:10)
    at Function.<anonymous> (/Users/arthur/.node-spawn-wrap-19073-3b48967770f6/node:171:5)
    at Object.<anonymous> (/my-folder/structure/project/node_modules/nyc/bin/wrap.js:23:4)
    at Module._compile (module.js:652:30)
    at Object.Module._extensions..js (module.js:663:10)
    at Module.load (module.js:565:32)
    at tryModuleLoad (module.js:505:12)
    at Function.Module._load (module.js:497:3)
    at Function.Module.runMain (module.js:693:10)
    at /Users/arthur/.node-spawn-wrap-19073-3b48967770f6/node:178:8
    at Object.<anonymous> (/Users/arthur/.node-spawn-wrap-19073-3b48967770f6/node:181:3)
    at Module._compile (module.js:652:30)
    at Object.Module._extensions..js (module.js:663:10)
    at Module.load (module.js:565:32)
    at tryModuleLoad (module.js:505:12)
    at Function.Module._load (module.js:497:3)
    at Function.Module.runMain (module.js:693:10)
    at startup (bootstrap_node.js:191:16)
    at bootstrap_node.js:612:3
```
What I found - and it's absolutely crazy - if I change the `observations` folder name to a name starting with `test`, `test_`, `test_pancake` in it, **the module is found and the test runs**.

I'm absolutely flabbergasted, I'm not sure whose fault it is,  have you encountered something like this before ?

**Comment by ArthurianX** [comment]
I ruled out Istanbul (`nyc`), `source-map-support`, `ignore-styles`, `jsdom-global` - I'
m left with Mocha or TS-Node :(

What I noticed, even when I change the folder name to test_something, in the Istanbul output, the folder structure still looks like `components/observations` - when in fact that folder is renamed.

![screenshot 2018-07-30 15 33 07](https://user-images.githubusercontent.com/2720451/43397591-0c37e608-940e-11e8-98be-627feb169b4f.png)

**Comment by ArthurianX** [comment]
What I've noticed is that for another file, if I switched directories it worked. I fail to understand the actual problem.

**Comment by RohanNg** [comment]
Maybe this was because of https://github.com/TypeStrong/ts-node/releases/tag/v7.0.0?

**Comment by cspotcode** [comment]
Sounds like this was a mocha error rather than a `ts-node` issue, since it relied on the directory starting with `test`.
