### ISSUE TITLE
Cannot import fork-ts-checker-webpack-plugin

### ISSUE THREAD

**Issue by septagram** [TypeStrong/ts-node#694]
I'm having a very odd issue: when I'm trying to import this plugin, it seems to resolve as `/lib/types/index.d.ts` instead of `lib/index.js`, so I receive undefined on import.

I've created a [minimal test case](https://github.com/septagram/fork-ts-no-import) to reproduce. Please help me figure out if this is my own configuration issue, `ts-node` issue, or the `fork-ts-checker-webpack-plugin` issue.

I have no issue with import in general, other modules (e.g., webpack plugins such as `html-webpack-plugin`) are being imported just fine.
```
$ node --version && npm --version
v10.11.0
6.3.0
```

**Comment by septagram** [comment]
Oops, sorry, I forgot to paste an actual link to the test case. Edited the post, fixed.

**Comment by alexandr-bbm** [comment]
@septagram in your `config.ts` file you noted
```
// Also does not work: import * as ForkTsCheckerWebpackPlugin from 'fork-ts-checker-webpack-plugin';
```

Are you sure? Changing to this import does not lead `ForkTsCheckerWebpackPlugin` to be undefined. It outputs correct error. Please see below.

```
~/Documents/web/fork-ts-no-import npm test

> fork-ts-no-import@1.0.0 test /Users/alexandr.bbm/Documents/web/fork-ts-no-import
> better-npm-run test

running better-npm-run in /Users/alexandr.bbm/Documents/web/fork-ts-no-import
Executing script: test

to be executed: "node_modules/.bin/webpack" --progress --colors --config "webpack/config.ts" 
fork-ts-checker-webpack-plugin is function ForkTsCheckerWebpackPlugin(options) {
        options = options || {};
        this.options = Object.assign({}, options);
        this.tsconfig = options.tsconfig || './tsconfig.json';
        this.tslint = options.tslint ?
            options.tslint === true ? './tslint.json' : options.tslint : undefined;
        this.watch = isString(options.watch) ? [options.watch] : options.watch || [];
        this.ignoreDiagnostics = options.ignoreDiagnostics || [];
        this.ignoreLints = options.ignoreLints || [];
        this.logger = options.logger || console;
        this.silent = options.silent === true; // default false
        this.async = options.async !== false; // default true
        this.checkSyntacticErrors = options.checkSyntacticErrors === true; // default false
        this.workersNumber = options.workers || ForkTsCheckerWebpackPlugin.ONE_CPU;
        this.memoryLimit = options.memoryLimit || ForkTsCheckerWebpackPlugin.DEFAULT_MEMORY_LIMIT;
        this.useColors = options.colors !== false; // default true
        this.colors = new chalk_1.default.constructor({ enabled: this.useColors });
        this.formatter = (options.formatter && isFunction(options.formatter))
            ? options.formatter
            : ForkTsCheckerWebpackPlugin.createFormatter(options.formatter || 'default', options.formatterOptions || {});
        this.tsconfigPath = undefined;
        this.tslintPath = undefined;
        this.watchPaths = [];
        this.compiler = undefined;
        this.started = undefined;
        this.elapsed = undefined;
        this.cancellationToken = undefined;
        this.isWatching = false;
        this.checkDone = false;
        this.compilationDone = false;
        this.diagnostics = [];
        this.lints = [];
        this.emitCallback = this.createNoopEmitCallback();
        this.doneCallback = this.createDoneCallback();
        this.typescriptVersion = require('typescript').version;
        this.tslintVersion = this.tslint ? require('tslint').Linter.VERSION : undefined;
        this.vue = options.vue === true; // default false
    }
                                                             
Insufficient number of arguments or no entry found.
Alternatively, run 'webpack(-cli) --help' for usage info.

```

**Comment by septagram** [comment]
@alexandr-bbm no, I'm getting this instead:
```
$ npm run test

> fork-ts-no-import@1.0.0 test d:\Dropbox\Code\fork-ts-no-import
> better-npm-run test

running better-npm-run in d:\Dropbox\Code\fork-ts-no-import
Executing script: test

to be executed: ""node_modules/.bin/webpack" --progress --colors --config "webpack/config.ts""

d:\Dropbox\Code\fork-ts-no-import\node_modules\ts-node\src\index.ts:261
    return new TSError(diagnosticText, diagnosticCodes)
           ^
TSError: ⨯ Unable to compile TypeScript:
webpack/config.ts(4,45): error TS2497: Module '"d:/Dropbox/Code/fork-ts-no-import/node_modules/fork-ts-checker-webpack-plugin/lib/types/index"' resolves to a non-module entity and cannot be imported using this construct.

    at createTSError (d:\Dropbox\Code\fork-ts-no-import\node_modules\ts-node\src\index.ts:261:12)
    at getOutput (d:\Dropbox\Code\fork-ts-no-import\node_modules\ts-node\src\index.ts:367:40)
    at Object.compile (d:\Dropbox\Code\fork-ts-no-import\node_modules\ts-node\src\index.ts:558:11)
    at Module.m._compile (d:\Dropbox\Code\fork-ts-no-import\node_modules\ts-node\src\index.ts:439:43)
    at Module._extensions..js (internal/modules/cjs/loader.js:700:10)
    at Object.require.extensions.(anonymous function) [as .ts] (d:\Dropbox\Code\fork-ts-no-import\node_modules\ts-node\src\index.ts:442:12)
    at Module.load (internal/modules/cjs/loader.js:599:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:538:12)
    at Function.Module._load (internal/modules/cjs/loader.js:530:3)
    at Module.require (internal/modules/cjs/loader.js:637:17)
    at require (d:\Dropbox\Code\fork-ts-no-import\node_modules\v8-compile-cache\v8-compile-cache.js:159:20)
    at WEBPACK_OPTIONS (d:\Dropbox\Code\fork-ts-no-import\node_modules\webpack-cli\bin\convert-argv.js:133:13)
    at requireConfig (d:\Dropbox\Code\fork-ts-no-import\node_modules\webpack-cli\bin\convert-argv.js:135:6)
    at d:\Dropbox\Code\fork-ts-no-import\node_modules\webpack-cli\bin\convert-argv.js:142:17
    at Array.forEach (<anonymous>)
    at module.exports (d:\Dropbox\Code\fork-ts-no-import\node_modules\webpack-cli\bin\convert-argv.js:140:15)
    at yargs.parse (d:\Dropbox\Code\fork-ts-no-import\node_modules\webpack-cli\bin\cli.js:241:39)
    at Object.parse (d:\Dropbox\Code\fork-ts-no-import\node_modules\yargs\yargs.js:563:18)
    at d:\Dropbox\Code\fork-ts-no-import\node_modules\webpack-cli\bin\cli.js:219:8
    at Object.<anonymous> (d:\Dropbox\Code\fork-ts-no-import\node_modules\webpack-cli\bin\cli.js:530:3)
    at Module._compile (internal/modules/cjs/loader.js:689:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:700:10)
    at Module.load (internal/modules/cjs/loader.js:599:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:538:12)
    at Function.Module._load (internal/modules/cjs/loader.js:530:3)
    at Module.require (internal/modules/cjs/loader.js:637:17)
    at require (internal/modules/cjs/helpers.js:20:18)
    at Object.<anonymous> (d:\Dropbox\Code\fork-ts-no-import\node_modules\webpack\bin\webpack.js:155:2)
    at Module._compile (internal/modules/cjs/loader.js:689:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:700:10)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! fork-ts-no-import@1.0.0 test: `better-npm-run test`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the fork-ts-no-import@1.0.0 test script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\Septi\AppData\Roaming\npm-cache\_logs\2018-09-27T10_12_13_710Z-debug.log
```

**Comment by septagram** [comment]
Workaround: it seems that importing with `require()` allows to get this running:
```
const ForkTsCheckerWebpackPlugin = require('fork-ts-checker-webpack-plugin');
```
However, this discards typing information from the plugin, so the issue stands.

**Comment by blakeembrey** [comment]
It could be because you have `allowSyntheticDefaultImports` in your configuration enabled.

**Comment by septagram** [comment]
@blakeembrey you're absolutely right, we do. Thanks for explaining what can be going on here )
