### ISSUE TITLE
Can't use @ notation for imports

### ISSUE THREAD

**Issue by med-qh** [TypeStrong/ts-node#735]
Hi, I am trying to use ts-node with inversify and I am issuing problems with the @ notation for the imports.
I am getting errors such as 
```
routes/index.ts(1,24): error TS2307: Cannot find module '@/logger'.

TSError: ⨯ Unable to compile TypeScript:
routes/index.ts(1,24): error TS2307: Cannot find module '@/logger'.

    at createTSError (/home/med-qh/.npm-global/lib/node_modules/ts-node/src/index.ts:261:12)
    at getOutput (/home/med-qh/.npm-global/lib/node_modules/ts-node/src/index.ts:367:40)
    at Object.compile (/home/med-qh/.npm-global/lib/node_modules/ts-node/src/index.ts:558:11)
    at Module.m._compile (/home/med-qh/.npm-global/lib/node_modules/ts-node/src/index.ts:439:43)
    at Module._extensions..js (internal/modules/cjs/loader.js:699:10)
    at Object.require.extensions.(anonymous function) [as .ts] (/home/med-qh/.npm-global/lib/node_modules/ts-node/src/index.ts:442:12)
    at Module.load (internal/modules/cjs/loader.js:598:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:537:12)
    at Function.Module._load (internal/modules/cjs/loader.js:529:3)
    at Module.require (internal/modules/cjs/loader.js:636:17) {"error":{"diagnosticText":"routes/index.ts(1,24): error TS2307: Cannot find module '@/logger'.\n","diagnosticCodes":[2307]},"stack":"TSError: ⨯ Unable to compile TypeScript:\nroutes/index.ts(1,24): error TS2307: Cannot find module '@/logger'.\n\n    at createTSError (/home/med-qh/.npm-global/lib/node_modules/ts-node/src/index.ts:261:12)\n    at getOutput (/home/med-qh/.npm-global/lib/node_modules/ts-node/src/index.ts:367:40)\n    at Object.compile (/home/med-qh/.npm-global/lib/node_modules/ts-node/src/index.ts:558:11)\n    at Module.m._compile (/home/med-qh/.npm-global/lib/node_modules/ts-node/src/index.ts:439:43)\n    at Module._extensions..js (internal/modules/cjs/loader.js:699:10)\n    at Object.require.extensions.(anonymous function) [as .ts] (/home/med-qh/.npm-global/lib/node_modules/ts-node/src/index.ts:442:12)\n    at Module.load (internal/modules/cjs/loader.js:598:32)\n    at tryModuleLoad (internal/modules/cjs/loader.js:537:12)\n    at Function.Module._load (internal/modules/cjs/loader.js:529:3)\n    at Module.require (internal/modules/cjs/loader.js:636:17)","exception":true,"date":"Fri Nov 23 2018 14:06:17 GMT-0500 (Eastern Standard Time)","process":{"pid":12652,"uid":1001,"gid":1001,"cwd":"/home/med-qh/Desktop/chain-interface/src","execPath":"/usr/local/bin/node","version":"v10.12.0","argv":["node","/home/med-qh/Desktop/chain-interface/src/index.ts"],"memoryUsage":{"rss":175558656,"heapTotal":124243968,"heapUsed":91380160,"external":97301}},"os":{"loadavg":[0.7109375,0.94775390625,1.00048828125],"uptime":12886},"trace":[{"column":12,"file":"/home/med-qh/.npm-global/lib/node_modules/ts-node/src/index.ts","function":"createTSError","line":261,"method":null,"native":false},{"column":40,"file":"/home/med-qh/.npm-global/lib/node_modules/ts-node/src/index.ts","function":"getOutput","line":367,"method":null,"native":false},{"column":11,"file":"/home/med-qh/.npm-global/lib/node_modules/ts-node/src/index.ts","function":"Object.compile","line":558,"method":"compile","native":false},{"column":43,"file":"/home/med-qh/.npm-global/lib/node_modules/ts-node/src/index.ts","function":"Module.m._compile","line":439,"method":"_compile","native":false},{"column":10,"file":"internal/modules/cjs/loader.js","function":"Module._extensions..js","line":699,"method":".js","native":false},{"column":12,"file":"/home/med-qh/.npm-global/lib/node_modules/ts-node/src/index.ts","function":"Object.require.extensions.(anonymous function) [as .ts]","line":442,"method":"ts]","native":false},{"column":32,"file":"internal/modules/cjs/loader.js","function":"Module.load","line":598,"method":"load","native":false},{"column":12,"file":"internal/modules/cjs/loader.js","function":"tryModuleLoad","line":537,"method":null,"native":false},{"column":3,"file":"internal/modules/cjs/loader.js","function":"Module._load","line":529,"method":"_load","native":false},{"column":17,"file":"internal/modules/cjs/loader.js","function":"Module.require","line":636,"method":"require","native":false}]}
```

Is it not implemented yet ?
Thanks

**Comment by blakeembrey** [comment]
This is a General TypeScript issue because it doesn’t know how to resolve your types for that module.
