### ISSUE TITLE
Call stack cannot locate source correctly.

### ISSUE THREAD

**Issue by hyurl** [TypeStrong/ts-node#742]
When using **ts-node** to run my program, it produced this error stackk:

    HttpError: 404 no such file
        at DocController.<anonymous> (/mnt/d/git/sfn/src/controllers/docs.ts:61:27)
        at Generator.next (<anonymous>)
        at fulfilled (/mnt/d/git/sfn/node_modules/tslib/tslib.js:104:62)

Which is incorrect because the real location in `/mnt/d/git/sfn/src/controllers/docs.ts` is `91:23`.

I double checked this issue by running a compiled version via node directly with source map support, which performed correctly, so I'm guessing there is bug in ts-node's source map support.

**Comment by blakeembrey** [comment]
Without any reproduction there's nothing I can really do with this. It's also most likely an issue with https://www.npmjs.com/package/source-map-support which is what we use to render the stack trace. Feel free to open an issue there if you narrow it down! Also make sure you aren't running from cache for some reason.

**Comment by hyurl** [comment]
I use the same module *source-map-support*, but it works well on the compiled version of the program. Now I've found new information that may help, the line number and column number `61:27` is actually the
coordinate in the compiled code located in `/mnt/d/git/sfn/dist/controllers/docs.js`. So now the problem is pretty much that the source-map-support has successfully replaced the filename, however, failed with line and column numbers.
