### ISSUE TITLE
Weird unexpected token error

### ISSUE THREAD

**Issue by ORESoftware** [TypeStrong/ts-node#744]
I am getting this error:

```
ts-node /home/oleg/codes/typeaware/doc-gen/apps/api-app/src/exp.ts
/home/oleg/codes/typeaware/doc-gen/apps/api-app/src/exp.ts:2
import { ReplaySubject } from "rxjs";
       ^

SyntaxError: Unexpected token {
    at new Script (vm.js:74:7)
    at createScript (vm.js:246:10)
    at Object.runInThisContext (vm.js:298:10)
    at Module._compile (internal/modules/cjs/loader.js:657:28)
    at Module.m._compile (/home/oleg/.nvm/versions/node/v10.7.0/lib/node_modules/ts-node/src/index.ts:439:23)
    at Module._extensions..js (internal/modules/cjs/loader.js:700:10)
    at Object.require.extensions.(anonymous function) [as .ts] (/home/oleg/.nvm/versions/node/v10.7.0/lib/node_modules/ts-node/src/index.ts:442:12)
    at Module.load (internal/modules/cjs/loader.js:599:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:538:12)
    at Function.Module._load (internal/modules/cjs/loader.js:530:3)

```

the file is called 'exp.ts':

```typescript
'use strict';

import {ReplaySubject} from "rxjs";
import {takeLast} from "rxjs/operators";

const rs = new ReplaySubject();

rs.next(1);
rs.next(2);
rs.next(3);

rs.pipe(takeLast(0)).subscribe(v => {
  console.log({v});
});


```

my only guess is that it thinks it's a .js file, but that's a mistake. maybe there is a cache that I need to clear?

Is there a force ts flag? someting like:

`ts-node --force-ts <muhfile>
`
?

**Comment by marcus-sa** [comment]
I solved it by specifying the `module` as `commonjs` instead of `es2015` in my root `tsconfig.json`

**Comment by balupton** [comment]
I had to change `module` from `esnext` to `commonjs` to solve this too, which is weird.

Here is my full prior tsconfig.json:

```
{
  "compilerOptions": {
    "allowJs": true,
    "jsx": "preserve",
    "lib": ["dom", "es2017"],
    "maxNodeModuleJsDepth": 5,
    "module": "esnext",
    "allowSyntheticDefaultImports": true,
    "moduleResolution": "node",
    "resolveJsonModule": true,
    "sourceMap": true,
    "strict": true,
    "target": "esnext"
  },
  "include": ["components", "pages", "api", "scripts"]
}
```

**Comment by blakeembrey** [comment]
That makes sense, node.js does not understand ES2015 modules yet.

**Comment by 0x80** [comment]
@blakeembrey  Is it maybe possible to catch this and print a more informative error message? I suspect there are quite a few people like me wasting time trying to figure out what that error means.

**Comment by SephReed** [comment]
I've been getting this error all over the place for a while now.

my module has been on common js the entire time.  Anyone know what else to check?
