### ISSUE TITLE
Gulp failing even with blank gulp file.  JavaScript works fine.

### ISSUE THREAD

**Issue by electricessence** [TypeStrong/ts-node#752]
## Environment
WebStorm 2018.3.2

```
node --version
v10.14.2
```

## Error
```
D:[ PROJECT PATH ]>gulp
[21:28:07] Requiring external module ts-node/register

D:[ PROJECT PATH ]\node_modules\ts-node\src\index.ts:312
          throw new TSError(formatDiagnostics(diagnosticList, cwd, ts, lineOffset))
                ^
TSError: ⨯ Unable to compile TypeScript
Cannot find type definition file for 'chokidar'. (2688)
Cannot find type definition file for 'events'. (2688)
Cannot find type definition file for 'glob'. (2688)
Cannot find type definition file for 'glob-stream'. (2688)
Cannot find type definition file for 'gulp'. (2688)
Cannot find type definition file for 'minimatch'. (2688)
Cannot find type definition file for 'mocha'. (2688)
Cannot find type definition file for 'node'. (2688)
Cannot find type definition file for 'qunit'. (2688)
Cannot find type definition file for 'semver'. (2688)
Cannot find type definition file for 'undertaker'. (2688)
Cannot find type definition file for 'undertaker-registry'. (2688)
Cannot find type definition file for 'vinyl'. (2688)
Cannot find type definition file for 'vinyl-fs'. (2688)
    at getOutput (D:[ PROJECT PATH ]\node_modules\ts-node\src\index.ts:312:17)
    at D:[ PROJECT PATH ]\node_modules\ts-node\src\index.ts:343:18
    at Object.compile (D:[ PROJECT PATH ]\node_modules\ts-node\src\index.ts:476:19)
    at Module.m._compile (D:[ PROJECT PATH ]\node_modules\ts-node\src\index.ts:406:44)
    at Module._extensions..js (internal/modules/cjs/loader.js:700:10)
    at Object.require.extensions.(anonymous function) [as .ts] (D:[ PROJECT PATH ]\node_modules\ts-node\src\index.ts:409:12)
    at Module.load (internal/modules/cjs/loader.js:599:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:538:12)
    at Function.Module._load (internal/modules/cjs/loader.js:530:3)
    at Module.require (internal/modules/cjs/loader.js:637:17)
```

The above happens even if `gulpfile.ts` is blank.

### package.json
```json
{
  "@types/gulp": "^4.0.5",
  "@types/mocha": "^2.2.48",
  "@types/node": "^10.12.18",
  "@types/qunit": "^2.5.3",
  "@types/semver": "^5.5.0",
  "assert": "^1.3.0",
  "gulp": "^4.0.0",
  "gulp-clean": "^0.4.0",
  "karma": "^3.1.4",
  "mocha": "^5.2.0",
  "semver": "^5.6.0",
  "ts-node": "^1.6.1",
  "typescript": "^3.1.3"
}
```

### Actual
```
+-- @types/gulp@4.0.5
+-- @types/mocha@2.2.48
+-- @types/node@10.12.18
+-- @types/qunit@2.5.3
+-- @types/semver@5.5.0
+-- assert@1.4.1
+-- gulp@4.0.0
+-- gulp-clean@0.4.0
+-- karma@3.1.4
+-- mocha@5.2.0
+-- semver@5.6.0
+-- ts-node@1.7.3
+-- tslib@1.9.3
`-- typescript@3.2.2
```

With NO global.

## tsconfig.json
```json
{
  "compileOnSave": true,
  "compilerOptions": {
    "module": "commonjs",
    "target": "es6",
    "moduleResolution": "node",
    "noEmit": true
  },
  "typeAcquisition": {
    "enable": true
  }
}
```

**Comment by blakeembrey** [comment]
@electricessence Do you have any way to reproduce this consistently? I think I've only seen something similar when my `node_modules` was funky.

**Comment by cspotcode** [comment]
Closing due to inactivity.
