### ISSUE TITLE
ts-node cannot find typescript module on npx after version up

### ISSUE THREAD

**Issue by hojin-choi** [TypeStrong/ts-node#764]
I'm using ts-node on npx for a small program.
```
$ npx -p ts-node -p typescript ts-node sample.ts
```

However, this command is not working and prints error message after ts-node version up from 7.0.x to 8.0.x.
```
Error: Cannot find module 'typescript'
    at Function.Module._resolveFilename (module.js:548:15)
    at Function.resolve (internal/module.js:18:19)
    at Object.register (/Users/hojinchoi/.npm/_npx/9027/lib/node_modules/ts-node/src/index.ts:208:28)
    at Object.<anonymous> (/Users/hojinchoi/.npm/_npx/9027/lib/node_modules/ts-node/src/bin.ts:108:17)
    at Module._compile (module.js:653:30)
    at Object.Module._extensions..js (module.js:664:10)
    at Module.load (module.js:566:32)
    at tryModuleLoad (module.js:506:12)
    at Function.Module._load (module.js:498:3)
    at Function.Module.runMain (module.js:694:10)
```

I tried to specify ts-node version and it's working well.
```
$ npx -p ts-node@7.0.1 -p typescript ts-node sample.ts
```
So I think it's a bug after version up.

**Comment by blakeembrey** [comment]
I don't think this is a bug, just a change. Do you have `typescript` installed locally? It resolves according to CWD now instead of a global compiler instance. This is because of https://github.com/TypeStrong/ts-node/issues/697.
