### ISSUE TITLE
Unable to load an NPM module installed from GitHub

### ISSUE THREAD

**Issue by bioball** [TypeStrong/ts-node#78]
I'm using an NPM module installed from GitHub, and am receiving this error:

```
src/server.ts (1,27): Cannot find module 'ww-nodejs'. (2307)
src/typings/ww-nodejs.d.ts (4,16): Invalid module name in augmentation, module 'ww-nodejs' cannot be found. (2664)
    at getOutput (<ROOT_DIR>node_modules/ts-node/src/ts-node.ts:209:13)
    at Object.loader (<ROOT_DIR>node_modules/ts-node/src/ts-node.ts:236:4)
    at Module.load (module.js:343:32)
    at Function.Module._load (module.js:300:12)
    at Module.require (module.js:353:17)
    at require (internal/module.js:12:17)
    at Object.<anonymous> (<ROOT_DIR>main.js:2:1)
    at Module._compile (module.js:409:26)
    at Object.Module._extensions..js (module.js:416:10)
    at Module.load (module.js:343:32)
```

This isn't happening to any other node module. I'm guessing it's due to the module being installed GitHub rather than the NPM registry.

Here's the source code for where I'm requiring this module:

```ts
import { clusterer } from "ww-nodejs";
import { app } from "./app";
```

If I just `require("ww-nodejs")` in javascript, I get no issues.

**Comment by bioball** [comment]
Here's my package.json:

```json
{
  "name": "some-project",
  "version": "1.0.0",
  "description": "",
  "main": "index.js",
  "scripts": {
    "test": "echo \"Error: no test specified\" && exit 1"
  },
  "author": "",
  "license": "ISC",
  "dependencies": {
    "angular": "^1.5.1",
    "angular-ui-router": "^0.2.18",
    "express": "^4.13.4",
    "ts-node": "^0.6.2",
    "ww-nodejs": "playi/ww-nodejs"
  }
}
```

**Comment by blakeembrey** [comment]
@bioball That is a TypeScript error. You need a type definition to exist to use the module. Projects like https://github.com/typings/typings exist for this.

**Comment by blakeembrey** [comment]
Oh wait, you have some sort of typings for this? I'm a little confused, but it looks like they're invalid.

**Comment by blakeembrey** [comment]
Can you share `ww-nodejs.d.ts`? I suspect that's your error. You can not do both an `export` or `import` at the top level and `declare module "..."`.

**Comment by bioball** [comment]
The type definitions do exist. So the directory structure looks something like this:

```
- src/
| - conf/
| - typings/
| - - ww-nodejs.d.ts
```

Here's ww-nodejs.d.ts:

```ts
import { Express } from "express";
import { Handler } from "express";

declare module "ww-nodejs" {

  class Clusterer {
    setLogs(loggerOpts: LoggerOpts): Clusterer;
    heartbeat(heartbeatOpts): Clusterer;
    fork(size?: number): Clusterer;
    listen(port: number): Clusterer;
  }

  interface LogstashConfigs {
    host: string;
    port: number;
  }

  interface LoggerOpts {
    serviceName?: string;
    useLogstash?: boolean;
    logstashConfigs?: LogstashConfigs;
    useStandard?: boolean;
    useDisk?: boolean;
    logDir?: string;
    stage?: string;
  }

  interface HealthCheckOpts {
    buildFile?: string;
    body?: Object;
    bodyFn?: () => Object;
  }

  export const healthCheckController: {
    healthcheck(opts: HealthCheckOpts): Handler;
  };

  export const clusterer: {
    setupCluster(app: Express, serviceName?: string): Clusterer;
  }
}

```

**Comment by blakeembrey** [comment]
See this:

> You can not do both an export or import at the top level and declare module "...".

Your type definition is invalid. It should be:

```ts
declare module "ww-nodejs" {
  import { Express } from "express";
  import { Handler } from "express";

  class Clusterer {
    setLogs(loggerOpts: LoggerOpts): Clusterer;
    heartbeat(heartbeatOpts): Clusterer;
    fork(size?: number): Clusterer;
    listen(port: number): Clusterer;
  }

  interface LogstashConfigs {
    host: string;
    port: number;
  }

  interface LoggerOpts {
    serviceName?: string;
    useLogstash?: boolean;
    logstashConfigs?: LogstashConfigs;
    useStandard?: boolean;
    useDisk?: boolean;
    logDir?: string;
    stage?: string;
  }

  interface HealthCheckOpts {
    buildFile?: string;
    body?: Object;
    bodyFn?: () => Object;
  }

  export const healthCheckController: {
    healthcheck(opts: HealthCheckOpts): Handler;
  };

  export const clusterer: {
    setupCluster(app: Express, serviceName?: string): Clusterer;
  }
}
```

Notice that I moved the import into the declaration and out of the top level.

**Comment by bioball** [comment]
Ah, gotcha. Thanks, Blake.

What the hell, TypeScript!

**Comment by bioball** [comment]
Aside: This should be its own issue, but why does ts-node error out on compile errors? TypeScript eagerly compiles even if it finds errors, and a lot of the time the errors we get at runtime is more useful than the compile error warnings that get emitted by TypeScript.

**Comment by blakeembrey** [comment]
There's an option to disable all errors, as well as ignore specific issues. There should really be a `--transpile` mode too. Also https://github.com/TypeStrong/ts-node/issues/34 is tracking only warning and not erroring out.
