### ISSUE TITLE
ts-node run failed, tsc compile success

### ISSUE THREAD

**Issue by guotie** [TypeStrong/ts-node#799]
# ts-node -v
v8.0.3

# tsc -v
Version 3.3.3333

test code:

```
enum ContentType {
    Article = 'a',
    Video = 'v'
  }
  
window.alert(Object.keys(ContentType).some(x => ContentType[x] === 'v'))

```

Error:
```
    return new TSError(diagnosticText, diagnosticCodes)
           ^
TSError: ⨯ Unable to compile TypeScript:
src/index.ts:8:61 - error TS7015: Element implicitly has an 'any' type because index expression is not of type 'number'.

  window.alert(Object.keys(ContentType).some(x => ContentType[x] === 'v'))
```

**Comment by 3mard** [comment]
Can you share your tsconfig.json ?

**Comment by guotie** [comment]
```
{
  "compilerOptions": {
    /* Basic Options */
    "target": "es5",                          /* Specify ECMAScript target version: 'ES3' (default), 'ES5', 'ES2015', 'ES2016', 'ES2017','ES2018' or 'ESNEXT'. */
    "module": "commonjs",                     /* Specify module code generation: 'none', 'commonjs', 'amd', 'system', 'umd', 'es2015', or 'ESNext'. */
    /* Strict Type-Checking Options */
    "strict": true,                           /* Enable all strict type-checking options. */
    // "allowSyntheticDefaultImports": true,  /* Allow default imports from modules with no default export. This does not affect code emit, just typechecking. */
    "esModuleInterop": true                   /* Enables emit interoperability between CommonJS and ES Modules via creation of namespace objects for all imports. Implies 'allowSyntheticDefaultImports'. */
    // "preserveSymlinks": true,              /* Do not resolve the real path of symlinks. */

    /* Source Map Options */
    // "sourceRoot": "",                      /* Specify the location where debugger should locate TypeScript files instead of source locations. */
    // "mapRoot": "",                         /* Specify the location where debugger should locate map files instead of generated locations. */
    // "inlineSourceMap": true,               /* Emit a single file with source maps instead of having a separate file. */
    // "inlineSources": true,                 /* Emit the source alongside the sourcemaps within a single file; requires '--inlineSourceMap' or '--sourceMap' to be set. */

    /* Experimental Options */
    // "experimentalDecorators": true,        /* Enables experimental support for ES7 decorators. */
    // "emitDecoratorMetadata": true,         /* Enables experimental support for emitting type metadata for decorators. */
  }
}
```

**Comment by binki** [comment]
I also have something like this.

**Comment by resynth1943** [comment]
Same. Here's my source:

```ts
import { isPrompting, currentCLI, promptText, killCLIPrompt, startCLIPrompt } from './cli';

export const baseDebug = require('debug');

export function patchedDebug (name: string) {
	const base = baseDebug(name);
	return function (...args: any[]) {
		if (isPrompting) {
			console.log('\n');
		}

		if (currentCLI) {
			killCLIPrompt(currentCLI);
		}

		const result = base(...args);

		if (currentCLI) {
			startCLIPrompt(currentCLI);
		}

		return result;
	}
}

export const onMessageLog = patchedDebug('msg-listener');
export const replyLog = patchedDebug('f. reply');
export const mainLog = patchedDebug('rebot');
export const commandLog = patchedDebug('command');
export const sharderLog = patchedDebug('sharder');
export const subcommandLog = patchedDebug('subcommand');
export const databaseLog = patchedDebug('database');
export const cliLog = patchedDebug('cli');
```

This is then imported from my main file, like so:
```ts
import { mainLog } from './util/log';
```

I really don't know why this runs **fine** with `tsc`, but fails with:

```
/home/def14nt/Desktop/code/rebot/src/rebot.ts:44
        mainLog('Using development account. Maintenance mode has been activated.');
 ^
TypeError: log_1.mainLog is not a function
    at Object.<anonymous> (/home/def14nt/Desktop/code/rebot/src/rebot.ts:44:2)
    at Module._compile (internal/modules/cjs/loader.js:689:30)
    at Module.m._compile (/home/def14nt/.nvm/versions/node/v10.15.0/lib/node_modules/ts-node/src/index.ts:415:23)
    at Module._extensions..js (internal/modules/cjs/loader.js:700:10)
    at Object.require.extensions.(anonymous function) [as .ts] (/home/def14nt/.nvm/versions/node/v10.15.0/lib/node_modules/ts-node/src/index.ts:418:12)
    at Module.load (internal/modules/cjs/loader.js:599:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:538:12)
    at Function.Module._load (internal/modules/cjs/loader.js:530:3)
    at Module.require (internal/modules/cjs/loader.js:637:17)
    at require (internal/modules/cjs/helpers.js:22:18)
```

when `ts-node` is used.

**Comment by resynth1943** [comment]
turns out a circular dependency was doing the harm, makes sense

**Comment by sapolang** [comment]
I also have something like this.

**Comment by blakeembrey** [comment]
If anyone wants to share a reproduction I can take a look at it.

**Comment by chadbr** [comment]
@blakeembrey Hey - I ran into this today and created a small repo:

https://github.com/chadbr/tsnode-compile-issue

things work fine when target is "es6" - but changing it to "ES2020" or "ESNext" or something similar, causes ts-node via mocha to fail.

I hope that helps -- Chad

**Comment by cspotcode** [comment]
@chadbr When target is ES2020 or ESNext, TypeScript is keeping the `??` operator in the code.  Your version of `node` cannot understand the `??` operator.  The error you are seeing comes from `node`, not `ts-node` nor TypeScript.

The original issue from @guotie is a typescript diagnostics which is not caused by ts-node.  It reproduces in the playground, for example: https://www.typescriptlang.org/play?#code/KYOwrgtgBAwg9iALqRAVAngB2FA3gKCiKgEEAnRASwGMAbHAXigHIBDZgGkOIDVKATYHChNmAN2bcAvt3wB3SiH5w5AOlb0KACgDyAIwBWwaolUBrYOgDOW+EhQZsASlVW4EYFoAeIgHywEZCRHYABtLwBdEQZRCScnIA
