### ISSUE TITLE
SyntaxError: Unexpected token ] in JSON at position 384

### ISSUE THREAD

**Issue by ShintaroNippon** [TypeStrong/ts-node#834]
package.json

"ts-node": "^3.3.0",

```
run: node -r ts-node/register index.ts

SyntaxError: Unexpected token ] in JSON at position 384
    at JSON.parse (<anonymous>)
    at parse (/home/shintaro/Desktop/projects/github/New-MyBoxIt-Api-master/node_modules/tsconfig/src/tsconfig.ts:195:15)
    at readFileSync (/home/shintaro/Desktop/projects/github/New-MyBoxIt-Api-master/node_modules/tsconfig/src/tsconfig.ts:181:10)
    at Object.loadSync (/home/shintaro/Desktop/projects/github/New-MyBoxIt-Api-master/node_modules/tsconfig/src/tsconfig.ts:151:18)
    at readConfig (/home/shintaro/Desktop/projects/github/New-MyBoxIt-Api-master/node_modules/ts-node/src/index.ts:425:18)
    at Object.register (/home/shintaro/Desktop/projects/github/New-MyBoxIt-Api-master/node_modules/ts-node/src/index.ts:189:18)
    at Object.<anonymous> (/home/shintaro/Desktop/projects/github/New-MyBoxIt-Api-master/node_modules/ts-node/register.js:1:15)
    at Module._compile (internal/modules/cjs/loader.js:701:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:712:10)
    at Module.load (internal/modules/cjs/loader.js:600:32)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! sequelize-typescript-starter@1.0.0 watch:serve: `node -r ts-node/register index.ts`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the sequelize-typescript-starter@1.0.0 watch:serve script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/shintaro/.npm/_logs/2019-05-15T17_44_29_544Z-debug.log
[nodemon] app crashed - waiting for file changes befor
```

**Comment by blakeembrey** [comment]
Update your version.
