### ISSUE TITLE
about compilerOptions { "module": "esnext" } with SyntaxError: Unexpected identifier

### ISSUE THREAD

**Issue by bluelovers** [TypeStrong/ts-node#842]
tsconfig.json
```json
{
  "compilerOptions": {
    "module": "esnext"
  }
}

```

temp.ts
```ts
// @ts-ignore
import path from 'path';

console.dir(path);
```

> showing error

```
import path from 'path';
       ^^^^

SyntaxError: Unexpected identifier
    at Module._compile (internal/modules/cjs/loader.js:718:23)
    at Module.m._compile (C:\Users\User\AppData\Roaming\npm\node_modules\ts-node\src\index.ts:439:23)
    at Module._extensions..js (internal/modules/cjs/loader.js:785:10)
    at Object.require.extensions.<computed> [as .ts] (C:\Users\User\AppData\Roaming\npm\node_modules\ts-node\src\index.ts:442:12)
    at Module.load (internal/modules/cjs/loader.js:641:32)
    at Function.Module._load (internal/modules/cjs/loader.js:556:12)
    at Function.Module.runMain (internal/modules/cjs/loader.js:837:10)
    at Object.<anonymous> (C:\Users\User\AppData\Roaming\npm\node_modules\ts-node\src\bin.ts:154:12)
    at Module._compile (internal/modules/cjs/loader.js:774:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:785:10)

```

this only error with ts-node, with tsc it just no error and ping undefined

**Comment by blakeembrey** [comment]
This is a node.js error, not a TypeScript error. Node.js doesn't support ES Modules without a flag on the latest version.

**Comment by leizhao4** [comment]
@blakeembrey I'm not sure I follow (I ran in to the same problem). Are you saying `esnext` is not the latest version?

The weird part is that `"module": "commonjs"` works, but `"module": "esnext"` doesn't.
