### ISSUE TITLE
No error code (exit code) when failing

### ISSUE THREAD

**Issue by marcotuna** [TypeStrong/ts-node#857]
When running ts-node and when it fails it should throw an exit code greater than 0 (meaning error), however this is not happening.

ts-node version: 8.1.0
typescript: 3.3.3 (tested also with version 3.5.3)
mocha: 6.2.0
@types/mocha: 5.2.7

```
bob@bob-desktop:~/test-project$ npx ts-node -r source-map-support/register tests/runner.ts
(node:10736) UnhandledPromiseRejectionWarning: TSError: ⨯ Unable to compile TypeScript:
tests/modules/account/datamodel.spec.ts:289:20 - error TS2345: Argument of type '{ description: string; }' is not assignable to parameter of type 'DeepPartial<IAccount>'.
  Object literal may only specify known properties, and 'description' does not exist in type 'DeepPartial<IAccount>'.

88             description: 'testAccountError',
               ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

    at createTSError (/home/bob/test-project/node_modules/ts-node/src/index.ts:245:12)
    at reportTSError (/home/bob/test-project/node_modules/ts-node/src/index.ts:249:19)
    at getOutput (/home/bob/test-project/node_modules/ts-node/src/index.ts:362:34)
    at Object.compile (/home/bob/test-project/node_modules/ts-node/src/index.ts:395:32)
    at Module.m._compile (/home/bob/test-project/node_modules/ts-node/src/index.ts:473:43)
    at Module._extensions..js (module.js:663:10)
    at Object.require.extensions.(anonymous function) [as .ts] (/home/bob/test-project/node_modules/ts-node/src/index.ts:476:12)
    at Module.load (module.js:565:32)
    at tryModuleLoad (module.js:505:12)
    at Function.Module._load (module.js:497:3)
    at Module.require (module.js:596:17)
    at require (internal/module.js:11:18)
    at /home/bob/test-project/node_modules/mocha/lib/mocha.js:334:36
    at Array.forEach (<anonymous>)
    at Mocha.loadFiles (/home/bob/test-project/node_modules/mocha/lib/mocha.js:331:14)
    at Mocha.run (/home/bob/test-project/node_modules/mocha/lib/mocha.js:811:10)
(node:10736) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 4)
(node:10736) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
bob@bob-desktop:~/test-project$ echo $?
0
```

Any hints about what might be happening? Is this normal? I see some warnings at the end

**Comment by blakeembrey** [comment]
@marcotuna It looks like you've imported a TypeScript file from within a promise. Those are node.js warnings because you aren't handling your promise rejections. These errors are outside of `ts-node`'s control because this module does not **exit** for you, it throws errors that your application or node.js handles as expected. Because you don't handle it, whatever script you wrote has continued running until the end successfully.
