### ISSUE TITLE
bug with `type`: unreadable error

### ISSUE THREAD

**Issue by zaoqi** [TypeStrong/ts-node#860]
```
[zaoqi@555485319f56 typescript]$ ./node_modules/.bin/ts-node -T a.ts

/home/zaoqi/src/the-language/core/pure/typescript/a.ts:2
async function f():c<any>{
                   ^
ReferenceError: c is not defined
    at f (/home/zaoqi/src/the-language/core/pure/typescript/a.ts:2:20)
    at Object.<anonymous> (/home/zaoqi/src/the-language/core/pure/typescript/a.ts:5:13)
    at Module._compile (internal/modules/cjs/loader.js:816:30)
    at Module.m._compile (/home/zaoqi/src/the-language/core/pure/typescript/node_modules/ts-node/src/index.ts:473:23)
    at Module._extensions..js (internal/modules/cjs/loader.js:827:10)
    at Object.require.extensions.(anonymous function) [as .ts] (/home/zaoqi/src/the-language/core/pure/typescript/node_modules/ts-node/src/index.ts:476:12)
    at Module.load (internal/modules/cjs/loader.js:685:32)
    at Function.Module._load (internal/modules/cjs/loader.js:620:12)
    at Function.Module.runMain (internal/modules/cjs/loader.js:877:12)
    at Object.<anonymous> (/home/zaoqi/src/the-language/core/pure/typescript/node_modules/ts-node/src/bin.ts:158:12)
[zaoqi@555485319f56 typescript]$ cat a.ts
type c<x>=Promise<x>
async function f():c<any>{
return 1;
}
console.log(f())
```

**Comment by blakeembrey** [comment]
Did you try it without transpile mode? It might give you a better error, I see:

```
a.ts:2:20 - error TS1055: Type 'c' is not a valid async function return type in ES5/ES3 because it does not refer to a Promise-compatible constructor value.
```
