### ISSUE TITLE
error TS7022: '__importDefault' implicitly has type 'any' because it does not have a type annotation and is referenced directly or indirectly in its own initializer.

### ISSUE THREAD

**Issue by chadarsenault** [TypeStrong/ts-node#883]
OS: Windows 10 64
Environment: node v10.14.2, ts-node v8.3.0, typescript v3.6.2

I receive this error only while running ts-node as the loader, but not while compiling with typescript directly.  I've attached the contents of my project's root\api dir, `C:\www\node-framework\api` for inspection.  The only two files currently being touched by typescript should be `C:\www\node-framework\api\src\framework.ts` and `C:\www\node-framework\api\src\app.ts`

Full error:

```javascript
$ node_modules/.bin/ts-node --require ts-node/register ./src/framework.ts

C:\www\node-framework\api\node_modules\ts-node\src\index.ts:245
    return new TSError(diagnosticText, diagnosticCodes)
           ^
TSError: ⨯ Unable to compile TypeScript:
src/framework.ts:2:5 - error TS7022: '__importDefault' implicitly has type 'any' because it does not have a type annotation and is referenced directly or indirectly in its own initializer.

2 var __importDefault = (this && this.__importDefault) || function (mod) {
      ~~~~~~~~~~~~~~~
src/framework.ts:2:67 - error TS7006: Parameter 'mod' implicitly has an 'any' type.

2 var __importDefault = (this && this.__importDefault) || function (mod) {
                                                                    ~~~

    at createTSError (C:\www\node-framework\api\node_modules\ts-node\src\index.ts:245:12)
    at reportTSError (C:\www\node-framework\api\node_modules\ts-node\src\index.ts:249:19)
    at getOutput (C:\www\node-framework\api\node_modules\ts-node\src\index.ts:362:34)
    at Object.compile (C:\www\node-framework\api\node_modules\ts-node\src\index.ts:395:32)
    at Module.m._compile (C:\www\node-framework\api\node_modules\ts-node\src\index.ts:473:43)
    at Module.m._compile (C:\www\node-framework\api\node_modules\ts-node\src\index.ts:473:23)
    at Module._extensions..js (internal/modules/cjs/loader.js:700:10)
    at require.extensions.(anonymous function) (C:\www\node-framework\api\node_modules\ts-node\src\index.ts:476:12)
    at Object.require.extensions.(anonymous function) [as .ts] (C:\www\node-framework\api\node_modules\ts-node\src\index.ts:476:12)
[www_node-framework_api.zip](https://github.com/TypeStrong/ts-node/files/3588384/www_node-framework_api.zip)

    at Module.load (internal/modules/cjs/loader.js:599:32)
```

**Comment by blakeembrey** [comment]
It looks like you've registered `ts-node` twice, so it's compiling your TypeScript then again with the output from TypeScript.

**Comment by blakeembrey** [comment]
It actually says so in your CLI: `ts-node --require ts-node/register` - use one or the other, not both at the same time.

**Comment by reduardo7** [comment]
Like @blakeembrey said, you should use `node_modules/.bin/ts-node ./src/framework.ts` or `node --require ts-node/register ./src/framework.ts`

**Comment by dev-isho** [comment]
> It looks like you've registered `ts-node` twice, so it's compiling your TypeScript then again with the output from TypeScript.

Woo Thanks it works

**Comment by rxliuli** [comment]
Is there a way to check whether ts-node is used to run the code in the code?
