### ISSUE TITLE
In "nodejs" version v13.2.0, using "ts-node" ,".ts" files cannot be compiled into "ES2015" modules and work 

### ISSUE THREAD

**Issue by masx200** [TypeStrong/ts-node#923]
In "nodejs" version v13.2.0, ".ts" files cannot be compiled into "ES2015" modules using "ts-node"

Running "ts-node ./rename-by-md5.ts" will report an error.

but Run "tsc && node ./rename-by-md5.js", the program will work normally

```powershell
 ts-node ./rename-by-md5.ts
(node:1784) ExperimentalWarning: The ESM module loader is experimental.
SyntaxError: Unexpected token ':'
    at Loader.moduleStrategy (internal/modules/esm/translators.js:84:18)
    at link (internal/modules/esm/module_job.js:36:21)
error Command failed with exit code 1.
```
tsconfig.json
```json
{
    "compilerOptions": {
        "declaration": true,
        "noUnusedLocals": true,
        "checkJs": true,
        "importHelpers": true,
        "removeComments": true,
        "allowJs": true,
        "target": "esnext",
        "module": "es2015",
        "strict": true,
        "noImplicitReturns": true,
        "noFallthroughCasesInSwitch": true,
        "esModuleInterop": true,
        "forceConsistentCasingInFileNames": true
    }
}
```

package.json
```json
{
  "type": "module",
  "types": "rename-by-md5.ts",
  "name": "@masx200/rename-by-md5",
  "version": "1.0.0",
  "main": "rename-by-md5.js",
  "license": "MIT",
  "scripts": {
    "start": "tsc && node ./rename-by-md5.js"
  },
  "dependencies": {
    "@types/find": "^0.2.1",
    "@types/md5-file": "^4.0.0",
    "@types/node": "^12.12.17",
    "find": "^0.3.0",
    "md5-file": "^4.0.0",
    "ts-node": "^8.5.4",
    "tslib": "^1.10.0",
    "typescript": "^3.7.3"
  },
  "devDependencies": {},
  "keywords": [],
  "author": "masx200 <34191203+masx200@users.noreply.github.com>",
  "description": "批量使用文件的md5值给文件重命名",
  "repository": "git+https://github.com/masx200/rename-by-md5.git",
  "bugs": {
    "url": "https://github.com/masx200/rename-by-md5/issues"
  },
  "homepage": "https://github.com/masx200/rename-by-md5#readme"
}

```

rename-by-md5.ts
```typescript
import find from "find";
import fs from "fs";
import md5file from "md5-file";
import path from "path";
function md5FileAsPromised(filename: string): Promise<string> {
  return new Promise(function(resolve, reject) {
    md5file(filename, function(err, hash) {
      if (err) {
        return reject(err);
      } else {
        resolve(hash);
      }
    });
  });
}
```

**Comment by blakeembrey** [comment]
This is unfortunately expected behavior, see https://github.com/TypeStrong/ts-node/issues/436 if you’d like to help support it. I haven’t had the capacity to dive into the latest module loader configuration yet, or figure out the trickier cases of actually allowing an import of a file that doesn’t exist yet because you need to specify extensions now.
