### ISSUE TITLE
Exported array is undefined when using `--transpileOnly`

### ISSUE THREAD

**Issue by dancrumb** [TypeStrong/ts-node#955]
I have an application, written in TypeScript, that I start with the following invocation:
```
node -r ts-node/register/transpile-only  -r tsconfig-paths/register src/server.ts
```

It errors out on startup with:
```

/Users/danrumney/WebstormProjects/ohana/src/routers/mp2s.ts:52
  ...userCanAttachFiles.map(can => ifUser(...can)),
                        ^
TypeError: Cannot read property 'map' of undefined
    at Object.<anonymous> (/Users/danrumney/WebstormProjects/ohana/src/routers/mp2s.ts:52:25)
    at Module._compile (internal/modules/cjs/loader.js:956:30)
    at Module.m._compile (/Users/danrumney/WebstormProjects/ohana/node_modules/ts-node/src/index.ts:814:23)
    at Module._extensions..js (internal/modules/cjs/loader.js:973:10)
    at Object.require.extensions.<computed> [as .ts] (/Users/danrumney/WebstormProjects/ohana/node_modules/ts-node/src/index.ts:817:12)
    at Module.load (internal/modules/cjs/loader.js:812:32)
    at Function.Module._load (internal/modules/cjs/loader.js:724:14)
    at Module.require (internal/modules/cjs/loader.js:849:19)
    at require (internal/modules/cjs/helpers.js:74:18)
    at Object.<anonymous> (/Users/danrumney/WebstormProjects/ohana/src/controllers/MP2Controller.ts:17:1)
    at Module._compile (internal/modules/cjs/loader.js:956:30)
    at Module.m._compile (/Users/danrumney/WebstormProjects/ohana/node_modules/ts-node/src/index.ts:814:23)
    at Module._extensions..js (internal/modules/cjs/loader.js:973:10)
    at Object.require.extensions.<computed> [as .ts] (/Users/danrumney/WebstormProjects/ohana/node_modules/ts-node/src/index.ts:817:12)
    at Module.load (internal/modules/cjs/loader.js:812:32)
    at Function.Module._load (internal/modules/cjs/loader.js:724:14)
    at Module.require (internal/modules/cjs/loader.js:849:19)
    at require (internal/modules/cjs/helpers.js:74:18)
    at Object.<anonymous> (/Users/danrumney/WebstormProjects/ohana/src/controllers/PatientController.ts:44:1)
    at Module._compile (internal/modules/cjs/loader.js:956:30)
    at Module.m._compile (/Users/danrumney/WebstormProjects/ohana/node_modules/ts-node/src/index.ts:814:23)
    at Module._extensions..js (internal/modules/cjs/loader.js:973:10)
```

In `src/routers/mp2s.ts`, I have
```
import {MP2Controller, userCanAttachFiles} from '../controllers/MP2Controller';
```

And `userCanAttachFiles` is defined thus:
```
export const userCanAttachFiles = [
  [hasScopes(['file:upload'])],
  [
    is(ofType(UserType.Provider)).and(
      owns(MP2Service.getMP2Patient, ProviderService.isInCareTeam)
    ),
    is(ofType(UserType.Provider)).and(
      owns(MP2Service.getMP2Patient, ProviderService.ownsPatient)
    ),
    is(ofType(UserType.Guardian)).and(owns(MP2Service.getMP2Patient, 'Patient')),
  ],
];
```

My understanding of `transpile-only` is that it just skips type checking. I can't understand why an exported array would lead me to problems.

Is this a bug? Am I misunderstanding `transpile-only`? Is there a third question I'm neglecting to ask?

FWIW, `UserType` is an enum that is exported from another file.

**Versions**:
node: v12.13.0
ts-node@8.6.2 
typescript@3.7.3 
tsconfig-paths@3.9.0

**Comment by dancrumb** [comment]
For completeness, I get the same outcome with
```
ts-node -T  -r tsconfig-paths/register src/server.ts 
```

**Comment by cspotcode** [comment]
@dancrumb 

I'm unable to reproduce the behavior you're seeing.  I created this reproduction:

https://github.com/cspotcode/ts-node-repros/tree/955
https://github.com/cspotcode/ts-node-repros/runs/423916409?check_suite_focus=true

It finishes without errors.  Without a reproduction we won't be able to fix any bugs.

You can fork my reproduction, modify it to show the error you're seeing, and submit it as a pull request to https://github.com/cspotcode/ts-node-repros/  Then post a link here.

**Comment by dancrumb** [comment]
I spent some time on the recreate and figured out the problem.

`controllers/MP2Controller.ts` had a dependency on `routers/mp2s.ts` and vice versa.

I'm curious why this was only apparent with `--transpile-only` enabled. However, by refactoring my code to remove the dependency cycle, things are now running correctly.

I'm going to close this as it doesn't appear to be a bug with `ts-node`
