### ISSUE TITLE
TSError: ⨯ Unable to compile TypeScript:2304

### ISSUE THREAD

**Issue by susanforme** [TypeStrong/ts-node#968]
My English is very rubbish,but i need your help,thank you.

this is my first time to write typescript code
```typescript
let loggedObj = new Proxy({ name: "tom" }, {
  set(target, pKey: string, value: string, receiver): boolean {
    console.log("set");
    return Reflect.set(target, pKey, value, receiver)
  },
  get(target, key: string) {
    console.log("get");
    return Reflect.get(target, key);
  }
});
loggedObj.name = "jerry";
loggedObj.name;
```

then i use ts-node ,The following error occurred,i try `tsc test.ts`,the same error occurred,
But when I try `tsc --lib "es6,dom" test`,I succeeded.Because I want to compile in real time instead of generating a JavaScript file, please give me some help about TS-node
```
TSError: ⨯ Unable to compile TypeScript:
es6/test.ts(1,21): error TS2304: Cannot find name 'Proxy'.
es6/test.ts(4,12): error TS2304: Cannot find name 'Reflect'.
es6/test.ts(8,12): error TS2304: Cannot find name 'Reflect'.

    at createTSError (C:\Users\30785\AppData\Roaming\npm\node_modules\ts-node\src\index.ts:421:12)
    at reportTSError (C:\Users\30785\AppData\Roaming\npm\node_modules\ts-node\src\index.ts:425:19)
    at getOutput (C:\Users\30785\AppData\Roaming\npm\node_modules\ts-node\src\index.ts:530:36)
    at Object.compile (C:\Users\30785\AppData\Roaming\npm\node_modules\ts-node\src\index.ts:735:32)
    at Module._compile (C:\Users\30785\AppData\Roaming\npm\node_modules\ts-node\src\index.ts:814:43)
    at internal/modules/cjs/loader.js:991:10
    at Object..ts (C:\Users\30785\AppData\Roaming\npm\node_modules\ts-node\src\index.ts:817:12)
    at Module.load (internal/modules/cjs/loader.js:811:32)
    at Function._load (internal/modules/cjs/loader.js:723:14)
    at Function.runMain (internal/modules/cjs/loader.js:1043:10)
```

Not sure if this can help but here is my launch.json,i use vscode "run and debuuger"
```json
{
      "name": "TS",
      "type": "node",
      "request": "launch",
      "args": [
        "${relativeFile}"
      ],
      "cwd": "${workspaceRoot}",
      "protocol": "inspector",
      "runtimeArgs": [
        "--nolazy",
        "-r",
        "C:/Users/30785/AppData/Roaming/npm/node_modules/ts-node/register"
      ]
    }
```

**Comment by blakeembrey** [comment]
You need to create a `tsconfig.json` file that contains your configuration (e.g. `"lib": ["es6", "dom"]`). Right now it's compiling to ES5 so can't find ES6 features.
