### ISSUE TITLE
TypeScript 3.8: Getting ReferenceError on a type declaration

### ISSUE THREAD

**Issue by AlCalzone** [TypeStrong/ts-node#972]
I'm currently trying to migrate my project to TS 3.8 to use the new features like type-only imports. However, `ts-node` now fails with an error I cannot understand. If you look at `src/lib/commandclass/MultiChannelCC.ts`, you can see that `Driver` is imported in the very first line. And `tsc` compiles the code just fine.

Repro:
1. clone https://github.com/AlCalzone/node-zwave-js/tree/df85c588ec9d659d327afcbb47c9eeb94fc400bd
2. `npm i`
3. run `npx ts-node ./test/run.ts`
4. Error:
```bash
c:\Repositories\node-zwave-js\src\lib\commandclass\MultiChannelCC.ts:244
        public constructor(driver: Driver, options: CommandClassOptions) {
                            ^
ReferenceError: Driver is not defined
    at Object.<anonymous> (c:\Repositories\node-zwave-js\src\lib\commandclass\MultiChannelCC.ts:244:29)
    at Module._compile (internal/modules/cjs/loader.js:759:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:770:10)
    at Module.load (internal/modules/cjs/loader.js:628:32)
    at Function.Module._load (internal/modules/cjs/loader.js:555:12)
    at Module.require (internal/modules/cjs/loader.js:666:19)
    at require (internal/modules/cjs/helpers.js:16:16)
    at Object.<anonymous> (c:\Repositories\node-zwave-js\src\lib\driver\Driver.ts:16:1)
    at Module._compile (internal/modules/cjs/loader.js:759:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:770:10)
```

**Comment by AlCalzone** [comment]
In the meantime, I made this work with `-r ts-node/register/transpile-only.js` instead of  `-r ts-node/register`. 

However I still think the behavior described above is a bug.

**Comment by blakeembrey** [comment]
@AlCalzone Took a quick look and I think it's because of your import. The stack trace above shows it never even used `ts-node`. I cloned and tried testing, got this:

```
test/run.ts:2:24 - error TS2307: Cannot find module '../'.
```

However, once I run `npm run build` it worked correctly. Potentially this is Windows related?

**Comment by AlCalzone** [comment]
> The stack trace above shows it never even used `ts-node`.

How can that be if I execute the file with `ts-node`?

**Comment by blakeembrey** [comment]
@AlCalzone Hard to tell because it executes for me, but I suspect it imported the `.js` file and then had the source map rewrite to `.ts`.

**Comment by AlCalzone** [comment]
@blakeembrey I just did another test with a different import. Still the same error - but this time, `ts-node` is in the stack trace.

1. clone https://github.com/AlCalzone/node-zwave-js/tree/ts-node-repro
2. npm i
3. run npx ts-node ./test/run.ts
4. Error:

```
ReferenceError: Driver is not defined
    at Object.<anonymous> (D:\repository\src\lib\commandclass\MultiChannelCC.ts:244:29)
    at Module._compile (internal/modules/cjs/loader.js:1158:30)
    at Module.m._compile (D:\repository\node_modules\ts-node\src\index.ts:814:23)
    at Module._extensions..js (internal/modules/cjs/loader.js:1178:10)
    at Object.require.extensions.<computed> [as .ts] (D:\repository\node_modules\ts-node\src\index.ts:817:12)
    at Module.load (internal/modules/cjs/loader.js:1002:32)
    at Function.Module._load (internal/modules/cjs/loader.js:901:14)
    at Module.require (internal/modules/cjs/loader.js:1044:19)
    at require (internal/modules/cjs/helpers.js:77:18)
    at Object.<anonymous> (D:\repository\src\lib\driver\Driver.ts:16:1)
```

**Comment by AlCalzone** [comment]
@blakeembrey I believe we've found the root cause. See https://github.com/AlCalzone/node-zwave-js/issues/749 for details.

**Comment by blakeembrey** [comment]
Nice catch! I’m going to close this one out now that you’ve got the TypeScript issue open. Thanks!
